/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for image sprite generation files
 */
export interface Sprite {
  /**
   * Define custom CSS declarations to inject into the generated stylesheet.
   */
  customstyles?: {
    /**
     * A custom CSS declaration (property: value).
     */
    [k: string]: string | number;
  };
  /**
   * The image resolution of the generated image sprite
   */
  dpi?: number;
  /**
   * An array of file paths relative to this document. The name must be unique.
   */
  images: {
    /**
     * A source image for the sprite.
     */
    [k: string]: string;
  };
  /**
   * Optimizes the generated image either lossy or lossless. Requires the "Image Optimizer" extension for Visual Studio
   */
  optimize?: "lossless" | "lossy" | "none";
  /**
   * The orientation of the individual images inside the generated sprite.
   */
  orientation?: "horizontal" | "vertical";
  /**
   * Output format of the generated image sprite.
   */
  output?: "png" | "jpg" | "gif";
  /**
   * The padding arround each individual image in the sprite. The value is in pixels.
   */
  padding?: number;
  /**
   * Add any path root in front of the generated. Example: "/images/"
   */
  pathprefix?: string;
  /**
   * Define stylesheets (css, less, sass) to be generated as part of the sprite generation process.
   */
  stylesheet?: "none" | "css" | "less" | "scss" | "styl";
  [k: string]: unknown;
}
