/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface JSONSchemaForComponentJsonFiles {
  /**
   * A boolean specifying whether the component is private, defaulting to  false.
   */
  private?: boolean;
  /**
   * A public component MUST have a 'name'. This is what will be passed to  require().
   */
  name?: string;
  /**
   * The public component MUST have a 'repository' property, this is registry end-point consisting of  <username>/<project> , for example 'visionmedia/page.js' or 'component/dialog'.
   */
  repo?: string;
  /**
   * The component SHOULD have a 'description' property. This helps people find and understand your component.
   */
  description?: string;
  /**
   * The public component MUST include a version, allowing other scripts to depend on specific releases of the component.
   */
  version?: string;
  /**
   * Keywords are used when searching for a component. A public component SHOULD list a few keywords.
   */
  keywords?: string[];
  /**
   * It is recommended that you use 'index.js' for the main component file, however if you use another filename, you MUST define a 'main' field for that.
   */
  main?: string;
  /**
   * The  scripts  field explicitly specifies the scripts for this component. For public components, these must be regular JavaScript files. For private components, these should be regular Javascript files.
   */
  scripts?: string[];
  /**
   * The  styles  field explicitly specifies the stylesheets for this component. For public components, these must be regular CSS files. For private components, these should be regular CSS files.
   */
  styles?: string[];
  /**
   * The  json  field explicitly specifies the  JSON  files for this component. Each file must be valid  JSON .
   */
  json?: string[];
  /**
   * The  images  field MUST be supported and fetched upon installation, this allows component build tools to rewrite stylesheet  url() s in order to accomodate various file serving techniques.
   */
  images?: string[];
  /**
   * The  fonts  field MUST be supported and fetched upon installation, this allows component build tools to rewrite stylesheet  url() s in order to accomodate various file serving techniques.
   */
  fonts?: string[];
  /**
   * In the future we will classify more file types, however for those which are not treated uniquely such as fonts may be placed in a  files  array to aid build and installation tools.
   */
  files?: string[];
  /**
   * Runtime dependencies.
   */
  dependencies?: {
    [k: string]: string;
  };
  /**
   * Local dependencies are already located on disk, these are not installed, but are however included in the builds, thus no versions need to be defined. Local components should be located in a directory specified within .paths.
   */
  locals?: string[];
  /**
   * The public component must not contain any remotes.
   */
  remotes?: string[];
  /**
   * The public component must not contain any paths.
   */
  paths?: string[];
  /**
   * The templates array MUST provide the contents of each file as a require-able module. For example the following must provide the HTML string via require('user.html').
   */
  templates?: string[];
  demo?: string;
  development?: JSONSchemaForComponentJsonFiles;
  /**
   * The license string such as 'MIT' may be used for search output and other reporting, developers SHOULD specify this field
   */
  license?: string;
  [k: string]: unknown;
}
