/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Shared schema definitions for 'Import Manifest' and 'Update Manifest'.
 */
export interface JSONSchemaDefinitionsForAzureDeviceUpdateForIoTHubManifestsVersion50 {
  [k: string]: unknown | undefined;
}
