version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
    versioning-strategy: increase
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '> 26'
    cooldown:
      default-days: 5
      exclude:
        - '@ffflorian/*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
    cooldown:
      default-days: 5
      exclude:
        - 'ffflorian/*'
