updates:
  - assignees:
      - ffflorian
    commit-message:
      prefix: fix(deps)
      prefix-development: chore(deps-dev)
    cooldown:
      default-days: 5
      exclude:
        - '@ffflorian/*'
    directory: /
    groups:
      oxlint:
        patterns:
          - oxlint
          - eslint-plugin-oxlint
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - version-update:semver-major
    open-pull-requests-limit: 99
    package-ecosystem: npm
    schedule:
      interval: weekly
    versioning-strategy: increase
  - assignees:
      - ffflorian
    commit-message:
      prefix: ci(deps)
    cooldown:
      default-days: 5
      exclude:
        - ffflorian/*
    directory: /
    groups:
      ffflorian:
        patterns:
          - ffflorian/actions/*
    open-pull-requests-limit: 99
    package-ecosystem: github-actions
    schedule:
      interval: weekly
version: 2
