/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface JSONSchemaForTheASPNETGlobalConfigurationFiles {
  /**
   * Specify information about the SDK.
   */
  sdk?: {
    /**
     * The version of the SDK to use.
     */
    version?: string;
    allowPrerelease?: boolean;
    /**
     * The roll-forward policy when selecting an SDK version, either as a fallback to accommodate missing a specific SDK version or as a directive to use a later version.
     */
    rollForward?:
      | "patch"
      | "feature"
      | "minor"
      | "major"
      | "latestPatch"
      | "latestFeature"
      | "latestMinor"
      | "latestMajor"
      | "disable";
    [k: string]: any;
  };
  [k: string]: any;
}
