approvedGitRepositories: []

defaultSemverRangePrefix: ""

enableScripts: false

enableTelemetry: false

nodeLinker: node-modules

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.14.1.cjs
