approvedGitRepositories: []

defaultSemverRangePrefix: ""

enableScripts: false

enableTelemetry: false

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.17.0.cjs
