/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface JSONSchemaForExpoSDK37AppManifest {
  expo: {
    /**
     * The name of your app as it appears both within Expo and on your home screen as a standalone app.
     */
    name: string;
    /**
     * A short description of what your app is and why it is great.
     */
    description?: string;
    /**
     * The friendly url name for publishing. eg: `expo.io/@your-username/slug`.
     */
    slug: string;
    /**
     * The username of the account under which this app is published. If not specified, the app is published as the currently signed-in user.
     */
    owner?: string;
    /**
     * Either `public` or `unlisted`. If not provided, defaults to `unlisted`. In the future `private` will be supported. `unlisted` hides the experience from search results.
     */
    privacy?: ("public" | "unlisted") | null;
    /**
     * The Expo sdkVersion to run the project on. This should line up with the version specified in your package.json.
     */
    sdkVersion?: string;
    /**
     * Your app version, use whatever versioning scheme that you like.
     */
    version?: string;
    /**
     * Platforms that your project explicitly supports. If not specified, it defaults to `["ios", "android"]`.
     */
    platforms?: ("android" | "ios" | "web")[];
    /**
     * If you would like to share the source code of your app on Github, enter the URL for the repository here and it will be linked to from your Expo project page.
     */
    githubUrl?: string;
    /**
     * Lock your app to a specific orientation with `portrait` or `landscape`. Defaults to no lock.
     */
    orientation?: ("default" | "portrait" | "landscape") | null;
    /**
     * Configuration to force the app to always use the light or dark user-interface appearance, such as "dark mode", or make it automatically adapt to the system preferences. If not provided, defaults to `light`.
     */
    userInterfaceStyle?: "light" | "dark" | "automatic";
    /**
     * The background color for your app, behind any of your React views.
     */
    backgroundColor?: string;
    /**
     * On Android, this will determine the color of your app in the multitasker. Currently this is not used on iOS, but it may be used for other purposes in the future.
     */
    primaryColor?: string;
    /**
     * Local path or remote url to an image to use for your app's icon. We recommend that you use a 1024x1024 png file. This icon will appear on the home screen and within the Expo app.
     */
    icon?: string;
    /**
     * Configuration for remote (push) notifications.
     */
    notification?: {
      /**
       * Local path or remote url to an image to use as the icon for push notifications. 96x96 png grayscale with transparency.
       */
      icon?: string;
      /**
       * Tint color for the push notification image when it appears in the notification tray.
       */
      color?: string;
      /**
       * Display the notification when the app is in foreground on iOS.
       */
      iosDisplayInForeground?: boolean;
      /**
       * Show each push notification individually (`default`) or collapse into one (`collapse`).
       */
      androidMode?: ("default" | "collapse") | null;
      /**
       * If `androidMode` is set to `collapse`, this title is used for the collapsed notification message. eg: `'#{unread_notifications} new interactions'`.
       */
      androidCollapsedTitle?: string;
    };
    /**
     * DEPREACTED: Use `splash` instead. Configuration for the loading screen that users see when opening your app, while fetching & caching bundle and assets.
     */
    loading?: {
      /**
       * Local path or remote url to an image to display while starting up the app. Image size and aspect ratio are up to you. Must be a .png.
       */
      icon?: string;
      /**
       * If no icon is provided, we will show the Expo logo. You can choose between `white` and `blue`.
       */
      exponentIconColor?: ("white" | "blue") | null;
      /**
       * Similar to `exponentIconColor` but instead indicate if it should be grayscale (`1`) or not (`0`).
       */
      exponentIconGrayscale?: number;
      /**
       * Local path or remote url to an image to fill the background of the loading screen. Image size and aspect ratio are up to you. Must be a .png.
       */
      backgroundImage?: string;
      /**
       * Color to fill the loading screen background
       */
      backgroundColor?: string;
      /**
       * By default, Expo shows some text at the bottom of the loading screen. Set this to `true` to disable.
       */
      hideExponentText?: boolean;
      /**
       * DEPRECATED: was used in the past for changing the style of the iOS loading indicator.
       */
      loadingIndicatorStyleExperimental?: string;
    };
    /**
     * By default, Expo looks for the application registered with the AppRegistry as `main`. If you would like to change this, you can specify the name in this property.
     */
    appKey?: string;
    /**
     * DEPRECATED. Use `androidStatusBar` instead.
     */
    androidStatusBarColor?: string;
    /**
     * Configuration for the status bar on Android.
     */
    androidStatusBar?: {
      /**
       * Configures the status bar icons to have a light or dark color.
       */
      barStyle?: "light-content" | "dark-content";
      /**
       * Specifies the background color of the status bar.
       */
      backgroundColor?: string;
      [k: string]: unknown;
    };
    /**
     * Configuration for the bottom navigation bar on Android.
     */
    androidNavigationBar?: {
      /**
       * Determines how and when the navigation bar is shown.
       */
      visible?: "leanback" | "immersive" | "sticky-immersive";
      /**
       * Configure the navigation bar icons to have a light or dark color. Supported on Android Oreo and newer.
       */
      barStyle?: "light-content" | "dark-content";
      /**
       * Specifies the background color of the navigation bar.
       */
      backgroundColor?: string;
      [k: string]: unknown;
    };
    /**
     * Adds a notification to your standalone app with refresh button and debug info.
     */
    androidShowExponentNotificationInShellApp?: boolean;
    /**
     * URL scheme to link into your app. For example, if we set this to `'demo'`, then demo:// URLs would open your app when tapped.
     */
    scheme?: string;
    /**
     * The relative path to your main JavaScript file.
     */
    entryPoint?: string;
    /**
     * Any extra fields you want to pass to your experience. Values are accessible via `Expo.Constants.manifest.extra` ([read more](../sdk/constants.html#expoconstantsmanifest))
     */
    extra?: {
      [k: string]: unknown;
    };
    rnCliPath?: string;
    packagerOpts?: {
      [k: string]: unknown;
    };
    ignoreNodeModulesValidation?: boolean;
    nodeModulesPath?: string;
    /**
     * Configuration for how and when the app should request OTA JavaScript updates
     */
    updates?: {
      /**
       * If set to false, your standalone app will never download any code, and will only use code bundled locally on the device. In that case, all updates to your app must be submitted through Apple review. Defaults to true. (Note that this will not work out of the box with ExpoKit projects)
       */
      enabled?: boolean;
      /**
       * By default, Expo will check for updates every time the app is loaded. Set this to `'ON_ERROR_RECOVERY'` to disable automatic checking unless recovering from an error.
       */
      checkAutomatically?: ("ON_ERROR_RECOVERY" | "ON_LOAD") | null;
      /**
       * How long (in ms) to allow for fetching OTA updates before falling back to a cached version of the app. Defaults to 30000 (30 sec).
       */
      fallbackToCacheTimeout?: number;
    };
    /**
     * Provide overrides by locale for System Dialog prompts like Permissions Boxes
     */
    locales?: {
      [k: string]: unknown;
    };
    /**
     * iOS standalone app specific configuration
     */
    ios?: {
      /**
       * The manifest for the Android version of your app will be written to this path during publish.
       */
      publishManifestPath?: string;
      /**
       * The bundle for the Android version of your app will be written to this path during publish.
       */
      publishBundlePath?: string;
      /**
       * The bundle identifier for your iOS standalone app. You make it up, but it needs to be unique on the App Store. See [this StackOverflow question](http://stackoverflow.com/questions/11347470/what-does-bundle-identifier-mean-in-the-ios-project).
       */
      bundleIdentifier?: string;
      /**
       * Build number for your iOS standalone app. Must be a string that matches Apple's [format for CFBundleVersion](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102364).
       */
      buildNumber?: string;
      /**
       * The background color for your iOS app, behind any of your React views. Overrides the top-level `backgroundColor` key if it is present.
       */
      backgroundColor?: string;
      /**
       * Local path or remote URL to an image to use for your app's icon on iOS. If specified, this overrides the top-level `icon` key. Use a 1024x1024 icon which follows Apple's interface guidelines for icons, including color profile and transparency. Expo will generate the other required sizes. This icon will appear on the home screen and within the Expo app.
       */
      icon?: string;
      /**
       * Merchant ID for use with Apple Pay in your standalone app.
       */
      merchantId?: string;
      /**
       * URL to your app on the Apple App Store, if you have deployed it there. This is used to link to your store page from your Expo project page if your app is public.
       */
      appStoreUrl?: string;
      config?: {
        /**
         * [Branch](https://branch.io/) key to hook up Branch linking services.
         */
        branch?: {
          /**
           * Your Branch API key
           */
          apiKey?: string;
        };
        /**
         * Sets `ITSAppUsesNonExemptEncryption` in the standalone ipa's Info.plist to the given boolean value.
         */
        usesNonExemptEncryption?: boolean;
        /**
         * [Google Maps iOS SDK](https://developers.google.com/maps/documentation/ios-sdk/start) key for your standalone app.
         */
        googleMapsApiKey?: string;
        /**
         * [Google Mobile Ads App ID](https://support.google.com/admob/answer/6232340) Google AdMob App ID.
         */
        googleMobileAdsAppId?: string;
        /**
         * A boolean indicating whether to initialize Google App Measurement and begin sending user-level event data to Google immediately when the app starts. The default in Expo (Client and in standalone apps) is `false`.
         */
        googleMobileAdsAutoInit?: boolean;
        /**
         * [Google Sign-In iOS SDK](https://developers.google.com/identity/sign-in/ios/start-integrating) keys for your standalone app.
         */
        googleSignIn?: {
          /**
           * The reserved client ID URL scheme. Can be found in `GoogeService-Info.plist`.
           */
          reservedClientId?: string;
        };
      };
      /**
       * DEPRECATED: use `updates.enabled` instead.
       */
      isRemoteJSEnabled?: boolean;
      /**
       * [Firebase Configuration File](https://support.google.com/firebase/answer/7015592) GoogleService-Info.plist file for configuring Firebase.
       */
      googleServicesFile?: string;
      /**
       * DEPRECATED: use `updates` key with `fallbackToCacheTimeout: 0` instead.
       */
      loadJSInBackgroundExperimental?: boolean;
      /**
       * Whether your standalone iOS app supports tablet screen sizes. Defaults to `false`.
       */
      supportsTablet?: boolean;
      /**
       * If true, indicates that your standalone iOS app does not support handsets, and only supports tablets.
       */
      isTabletOnly?: boolean;
      /**
       * If true, indicates that your standalone iOS app does not support Slide Over and Split View on iPad. Defaults to `true` currently, but will change to `false` in a future SDK version.
       */
      requireFullScreen?: boolean;
      /**
       * Configuration to force the app to always use the light or dark user-interface appearance, such as "dark mode", or make it automatically adapt to the system preferences. If not provided, defaults to `light`.
       */
      userInterfaceStyle?: "light" | "dark" | "automatic";
      /**
       * Dictionary of arbitrary configuration to add to your standalone app's native Info.plist. Applied prior to all other Expo-specific configuration. No other validation is performed, so use this at your own risk of rejection from the App Store.
       */
      infoPlist?: {
        [k: string]: unknown;
      };
      /**
       * An array that contains Associated Domains for the standalone app.
       */
      associatedDomains?: unknown[];
      /**
       * A boolean indicating if the app uses iCloud Storage for DocumentPicker. See DocumentPicker docs for details.
       */
      usesIcloudStorage?: boolean;
      /**
       * A boolean indicating if the app uses Apple Sign-In. See AppleAuthentication docs for details.
       */
      usesAppleSignIn?: boolean;
      /**
       * A Boolean value that indicates whether the app may access the notes stored in contacts. You must receive permission from Apple before you can submit your app for review with this capability: https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_contacts_notes.
       */
      accessesContactNotes?: boolean;
      /**
       * Configuration for loading and splash screen for standalone iOS apps.
       */
      splash?: {
        /**
         * Local path to a XIB file as the loading screen. It overrides other loading screen options.
         */
        xib?: string;
        /**
         * Color to fill the loading screen background
         */
        backgroundColor?: string;
        /**
         * Determines how the `image` will be displayed in the splash loading screen. Must be one of `cover` or `contain`, defaults to `contain`.
         */
        resizeMode?: ("cover" | "contain") | null;
        /**
         * Local path or remote url to an image to fill the background of the loading screen. Image size and aspect ratio are up to you. Must be a .png.
         */
        image?: string;
        /**
         * Local path or remote url to an image to fill the background of the loading screen. Image size and aspect ratio are up to you. Must be a .png.
         */
        tabletImage?: string;
        [k: string]: unknown;
      };
    };
    /**
     * Android standalone app specific configuration
     */
    android?: {
      /**
       * The manifest for the Android version of your app will be written to this path during publish.
       */
      publishManifestPath?: string;
      /**
       * The bundle for the Android version of your app will be written to this path during publish.
       */
      publishBundlePath?: string;
      /**
       * The package name for your Android standalone app. You make it up, but it needs to be unique on the Play Store. See [this StackOverflow question](http://stackoverflow.com/questions/6273892/android-package-name-convention).
       */
      package?: string;
      /**
       * Version number required by Google Play. Increment by one for each release. Must be an integer. https://developer.android.com/studio/publish/versioning.html
       */
      versionCode?: number;
      /**
       * The background color for your Android app, behind any of your React views. Overrides the top-level `backgroundColor` key if it is present.
       */
      backgroundColor?: string;
      /**
       * Configuration to force the app to always use the light or dark user-interface appearance, such as "dark mode", or make it automatically adapt to the system preferences. If not provided, defaults to `light`.
       */
      userInterfaceStyle?: "light" | "dark" | "automatic";
      /**
       * Local path or remote url to an image to use for your app's icon on Android. If specified, this overrides the top-level `icon` key. We recommend that you use a 1024x1024 png file (transparency is recommended for the Google Play Store). This icon will appear on the home screen and within the Expo app.
       */
      icon?: string;
      adaptiveIcon?: {
        /**
         * Local path or remote url to an image to use for your app's icon on Android. If specified, this overrides the top-level `icon` and the `android.icon` keys. Should follow the guidelines specified at https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive. This icon will appear on the home screen.
         */
        foregroundImage?: string;
        /**
         * Local path or remote url to a background image for your app's Adaptive Icon on Android. If specified, this overrides the `backgroundColor` key. Should follow the guidelines specified at https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.
         */
        backgroundImage?: string;
        /**
         * Color to use as the background for your app's Adaptive Icon on Android.
         */
        backgroundColor?: string;
      };
      /**
       * URL to your app on the Google Play Store, if you have deployed it there. This is used to link to your store page from your Expo project page if your app is public.
       */
      playStoreUrl?: string;
      /**
       * List of permissions used by the standalone app. Remove the field to use the default list of permissions.
       *
       *   Example: `[ "CAMERA", "ACCESS_FINE_LOCATION" ]`.
       *
       *   You can specify the following permissions depending on what you need:
       *
       * - `ACCESS_COARSE_LOCATION`
       * - `ACCESS_FINE_LOCATION`
       * - `CAMERA`
       * - `MANAGE_DOCUMENTS`
       * - `READ_CONTACTS`
       * - `READ_EXTERNAL_STORAGE`
       * - `READ_INTERNAL_STORAGE`
       * - `READ_PHONE_STATE`
       * - `RECORD_AUDIO`
       * - `USE_FINGERPRINT`
       * - `VIBRATE`
       * - `WAKE_LOCK`
       * - `WRITE_EXTERNAL_STORAGE`
       * - `com.anddoes.launcher.permission.UPDATE_COUNT`
       * - `com.android.launcher.permission.INSTALL_SHORTCUT`
       * - `com.google.android.c2dm.permission.RECEIVE`
       * - `com.google.android.gms.permission.ACTIVITY_RECOGNITION`
       * - `com.google.android.providers.gsf.permission.READ_GSERVICES`
       * - `com.htc.launcher.permission.READ_SETTINGS`
       * - `com.htc.launcher.permission.UPDATE_SHORTCUT`
       * - `com.majeur.launcher.permission.UPDATE_BADGE`
       * - `com.sec.android.provider.badge.permission.READ`
       * - `com.sec.android.provider.badge.permission.WRITE`
       * - `com.sonyericsson.home.permission.BROADCAST_BADGE`
       */
      permissions?: unknown[];
      /**
       * [Firebase Configuration File](https://support.google.com/firebase/answer/7015592) google-services.json file for configuring Firebase.
       */
      googleServicesFile?: string;
      config?: {
        /**
         * [Branch](https://branch.io/) key to hook up Branch linking services.
         */
        branch?: {
          /**
           * Your Branch API key
           */
          apiKey?: string;
        };
        /**
         * [Google Developers Fabric](https://get.fabric.io/) keys to hook up Crashlytics and other services.
         */
        fabric?: {
          /**
           * Your Fabric API key
           */
          apiKey?: string;
          /**
           * Your Fabric build secret
           */
          buildSecret?: string;
        };
        /**
         * [Google Maps Android SDK](https://developers.google.com/maps/documentation/android-api/signup) key for your standalone app.
         */
        googleMaps?: {
          /**
           * Your Google Maps Android SDK API key
           */
          apiKey?: string;
        };
        /**
         * [Google Mobile Ads App ID](https://support.google.com/admob/answer/6232340) Google AdMob App ID.
         */
        googleMobileAdsAppId?: string;
        /**
         * A boolean indicating whether to initialize Google App Measurement and begin sending user-level event data to Google immediately when the app starts. The default in Expo (Client and in standalone apps) is `false`.
         */
        googleMobileAdsAutoInit?: boolean;
        /**
         * [Google Sign-In Android SDK](https://developers.google.com/identity/sign-in/android/start-integrating) keys for your standalone app.
         */
        googleSignIn?: {
          /**
           * The Android API key. Can be found in the credentials section of the developer console or in `google-services.json`.
           */
          apiKey?: string;
          /**
           * The SHA-1 hash of the signing certificate used to build the apk without any separator `:`. Can be found in `google-services.json`. https://developers.google.com/android/guides/client-auth
           */
          certificateHash?: string;
        };
      };
      /**
       * Configuration for loading and splash screen for standalone Android apps.
       */
      splash?: {
        /**
         * Color to fill the loading screen background
         */
        backgroundColor?: string;
        /**
         * Determines how the `image` will be displayed in the splash loading screen. Must be one of `cover`, `contain` or `native`, defaults to `contain`.
         */
        resizeMode?: ("cover" | "contain" | "native") | null;
        /**
         * Local path or remote url to an image to fill the background of the loading screen. Image size and aspect ratio are up to you. Must be a .png.
         */
        mdpi?: string;
        /**
         * Local path or remote url to an image to fill the background of the loading screen. Image size and aspect ratio are up to you. Must be a .png.
         */
        hdpi?: string;
        /**
         * Local path or remote url to an image to fill the background of the loading screen. Image size and aspect ratio are up to you. Must be a .png.
         */
        xhdpi?: string;
        /**
         * Local path or remote url to an image to fill the background of the loading screen. Image size and aspect ratio are up to you. Must be a .png.
         */
        xxhdpi?: string;
        /**
         * Local path or remote url to an image to fill the background of the loading screen. Image size and aspect ratio are up to you. Must be a .png.
         */
        xxxhdpi?: string;
        [k: string]: unknown;
      };
      /**
       * An array of intent filters.
       */
      intentFilters?: {
        autoVerify?: boolean;
        action: string;
        data?:
          | {
              scheme?: string;
              host?: string;
              port?: string;
              path?: string;
              pathPattern?: string;
              pathPrefix?: string;
              mimeType?: string;
            }[]
          | {
              scheme?: string;
              host?: string;
              port?: string;
              path?: string;
              pathPattern?: string;
              pathPrefix?: string;
              mimeType?: string;
            }[];
        category?: unknown[] | string;
      }[];
    };
    /**
     * Web platform specific configuration
     */
    web?: {
      /**
       * Relative path of an image to use for your app's favicon.
       */
      favicon?: string;
      /**
       * Defines the title of the document, defaults to the outer level name
       */
      name?: string;
      /**
       * A short version of the app's name, 12 characters or fewer. Used in app launcher and new tab pages. Maps to `short_name` in the PWA manifest.json. Defaults to the `name` property.
       */
      shortName?: string;
      /**
       * Specifies the primary language for the values in the name and short_name members. This value is a string containing a single language tag.
       */
      lang?: string;
      /**
       * Defines the navigation scope of this website's context. This restricts what web pages can be viewed while the manifest is applied. If the user navigates outside the scope, it returns to a normal web page inside a browser tab/window. If the scope is a relative URL, the base URL will be the URL of the manifest.
       */
      scope?: string;
      /**
       * Defines the color of the Android tool bar, and may be reflected in the app's preview in task switchers.
       */
      themeColor?: string;
      /**
       * Provides a general description of what the pinned website does.
       */
      description?: string;
      /**
       * Specifies the primary text direction for the name, short_name, and description members. Together with the lang member, it helps the correct display of right-to-left languages.
       */
      dir?: "auto" | "ltr" | "rtl";
      /**
       * Defines the developers’ preferred display mode for the website.
       */
      display?: "fullscreen" | "standalone" | "minimal-ui" | "browser";
      /**
       * The URL that loads when a user launches the application (e.g. when added to home screen), typically the index. Note that this has to be a relative URL, relative to the manifest URL.
       */
      startUrl?: string;
      /**
       * Defines the default orientation for all the website's top level browsing contexts.
       */
      orientation?:
        | "any"
        | "natural"
        | "landscape"
        | "landscape-primary"
        | "landscape-secondary"
        | "portrait"
        | "portrait-primary"
        | "portrait-secondary";
      /**
       * Defines the expected “background color” for the website. This value repeats what is already available in the site’s CSS, but can be used by browsers to draw the background color of a shortcut when the manifest is available before the stylesheet has loaded. This creates a smooth transition between launching the web application and loading the site's content.
       */
      backgroundColor?: string;
      /**
       * If content is set to default, the status bar appears normal. If set to black, the status bar has a black background. If set to black-translucent, the status bar is black and translucent. If set to default or black, the web content is displayed below the status bar. If set to black-translucent, the web content is displayed on the entire screen, partially obscured by the status bar.
       */
      barStyle?: "default" | "black" | "black-translucent";
      /**
       * Hints for the user agent to indicate to the user that the specified native applications (defined in expo.ios and expo.android) are recommended over the website.
       */
      preferRelatedApplications?: boolean;
      /**
       * DEPRECATED: Use the dedicated adapters like Next.js, Gatsby, Electron, etc...
       */
      use?: "default" | "nextjs";
      /**
       * Basic customization options for dangerously configuring the default webpack config. Please use `expo customize:web` to modify the versioned Webpack config directly instead.
       */
      build?: {
        /**
         * ID of the root DOM element in your index.html. By default this is "root".
         */
        rootId?: string;
        /**
         * DEPRECATED: Modify the Webpack config directly. Choose a custom style of source mapping to enhance the debugging process. These values can affect build and rebuild speed dramatically.
         */
        devtool?: string;
        /**
         * DEPRECATED: Modify the Webpack config directly. Allows you to specify the base path for all the assets within your application.
         */
        publicPath?: string;
        /**
         * DEPRECATED: Modify the Webpack config directly. Configuration for customizing webpack report. See `HtmlWebpackPlugin.Options` from `html-webpack-plugin`.
         */
        minifyHTML?: {
          [k: string]: unknown;
        };
        /**
         * DEPRECATED: Modify the Webpack config directly. Configuration for enabling webpack report and `stats.json`. See `BundleAnalyzerPlugin.Options` from `webpack-bundle-analyzer`.
         */
        report?: {
          [k: string]: unknown;
        };
        /**
         * DEPRECATED: Modify the Webpack config directly. Configuration for customizing the service worker. See `GenerateSWOptions` from `workbox-webpack-plugin`.
         */
        serviceWorker?: {
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      /**
       * DEPRECATED. Defines the meta tag elements that will be added to the head element of your index.html.
       */
      meta?: {
        /**
         * ID provided by the Google Site Verification API: https://developers.google.com/site-verification/
         */
        googleSiteVerification?: string;
        /**
         * Apple PWA-specific meta elements. By default these values will be inferred from fields in the scope above, but you can override them here.
         */
        apple?: {
          /**
           * Enables PWA functionality on iOS devices.
           */
          mobileWebAppCapable?: string;
          /**
           * If content is set to "default", the status bar appears normal. If set to "black", the status bar has a black background. If set to "black-translucent", the status bar is black and translucent. If set to "default" or "black", the web content is displayed below the status bar. If set to "black-translucent", the web content is displayed on the entire screen, partially obscured by the status bar.
           */
          barStyle?: "default" | "black" | "black-translucent";
          [k: string]: unknown;
        };
        /**
         * Twitter card protocol: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup.html
         */
        twitter?: {
          [k: string]: unknown;
        };
        /**
         * The Open Graph protocol: http://ogp.me/
         */
        openGraph?: {
          [k: string]: unknown;
        };
        /**
         * X-UA protocol
         */
        microsoft?: {
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      /**
       * Experimental features. These will break without deprecation notice.
       */
      dangerous?: {
        /**
         * Viewport meta tag for your index.html. By default this is optimized for mobile usage, disabling zooming, and resizing for iPhone X.
         */
        viewport?: string;
        /**
         * Message that is rendered when the browser using your page doesn't have JS enabled.
         */
        noJavaScriptMessage?: string;
        [k: string]: unknown;
      };
      /**
       * Configuration for PWA splash screens.
       */
      splash?: {
        /**
         * Color to fill the loading screen background
         */
        backgroundColor?: string;
        /**
         * Determines how the `image` will be displayed in the splash loading screen. Must be one of `cover` or `contain`, defaults to `contain`.
         */
        resizeMode?: ("cover" | "contain") | null;
        /**
         * Local path or remote url to an image to fill the background of the loading screen. Image size and aspect ratio are up to you. Must be a .png.
         */
        image?: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    /**
     * Used for all Facebook libraries. Set up your Facebook App ID at https://developers.facebook.com.
     */
    facebookAppId?: string;
    /**
     * Whether the Facebook SDK should be initialized automatically. The default in Expo (Client and in standalone apps) is `false`.
     */
    facebookAutoInitEnabled?: boolean;
    /**
     * Whether the Facebook SDK log app events automatically. If you don't set this property, Facebook's default will be used. (Applicable only to standalone apps.)
     */
    facebookAutoLogAppEventsEnabled?: boolean;
    /**
     * Whether the Facebook SDK should collect advertiser ID properties, like the Apple IDFA and Android Advertising ID, automatically. If you don't set this property, Facebook's default policy will be used. (Applicable only to standalone apps.)
     */
    facebookAdvertiserIDCollectionEnabled?: boolean;
    /**
     * Used for native Facebook login.
     */
    facebookDisplayName?: string;
    /**
     * Used for Facebook native login. Starts with 'fb' and followed by a string of digits, like 'fb1234567890'. You can find your scheme at https://developers.facebook.com/docs/facebook-login/ios in the 'Configuring Your info.plist' section.
     */
    facebookScheme?: string;
    /**
     * Is app detached
     */
    isDetached?: boolean;
    /**
     * Extra fields needed by detached apps
     */
    detach?: {
      [k: string]: unknown;
    };
    /**
     * Configuration for loading and splash screen for standalone apps.
     */
    splash?: {
      /**
       * Color to fill the loading screen background
       */
      backgroundColor?: string;
      /**
       * Determines how the `image` will be displayed in the splash loading screen. Must be one of `cover` or `contain`, defaults to `contain`.
       */
      resizeMode?: ("cover" | "contain") | null;
      /**
       * Local path or remote url to an image to fill the background of the loading screen. Image size and aspect ratio are up to you. Must be a .png.
       */
      image?: string;
      [k: string]: unknown;
    };
    /**
     * Configuration for scripts to run to hook into the publish process
     */
    hooks?: {
      postPublish?: unknown[];
    };
    /**
     * An array of file glob strings which point to assets that will be bundled within your standalone app binary. Read more in the [Offline Support guide](https://docs.expo.io/versions/latest/guides/offline-support.html)
     */
    assetBundlePatterns?: unknown[];
  };
}
