/* eslint-disable */

/**
 * Paths are /-separated sequences of names, optionally rooted at the package root (a leading
 * /). #path is the general grammar; #relative_path and #absolute_path specialize it to one or
 * the other for contexts where only one is legal.
 */
export type Path = string;
/**
 * A named subdivision of `secret`, nested to any depth, such as "secret/group1" or
 * "secret/group1/sub". Never bare "secret" itself -- secret may only depend on sample
 * (via the separate "sample" literal in require_pass below), never on itself.
 */
export type TestDataGroup = string;
export type TestCase =
  | Command
  | {
      /**
       * Generate an .ans-file whose contents are this string literal.
       */
      ans?: string;
      'ans.download'?:
        | string
        | {
            [k: string]: unknown | undefined;
          };
      'ans.statement'?:
        | string
        | {
            [k: string]: unknown | undefined;
          };
      /**
       * Create this test case by copying files from the given path.
       * The path is relative to "/generators/" and ends in a test case name,
       * such as "manual/samples/3".
       */
      copy?: string;
      count: (number | number[] | string) & number[];
      /**
       * Create this test case by invoking a generator, like "generate: gen_tree -n 5"
       */
      generate?: string;
      /**
       * Generate an .in-file whose contents are this string literal.
       */
      in?: string;
      'in.download'?:
        | string
        | {
            [k: string]: unknown | undefined;
          };
      'in.statement'?:
        | string
        | {
            [k: string]: unknown | undefined;
          };
      interaction?: string;
      /**
       * Check that the generated test case matches the given regex pattern(s).
       */
      match?:
        | string
        | string[]
        | {
            ans?: string | string[];
            in?: string | string[];
          };
      /**
       * Generate an .out-file whose contents are this string literal.
       */
      out?: string;
      /**
       * A string that is be prepended to each command before computing its {seed}.
       * May be used to regenerate all random cases and to prevent predictable seeds.
       */
      random_salt?: string;
      /**
       * The maximum number of invocation that will be tried if the generator fails.
       * Each generator invocation uses a different value for {seed}.
       */
      retries?: number;
      /**
       * A model solution used for generating answer files, like "/submissions/accepted/intended.py"
       */
      solution?: string;
      yaml?: TestCaseConfiguration;
    };
export type Command = string;
/**
 * Paths are /-separated sequences of names, optionally rooted at the package root (a leading
 * /). #path is the general grammar; #relative_path and #absolute_path specialize it to one or
 * the other for contexts where only one is legal.
 */
export type RelativePath = string;

export interface ProblemPackageGenerators {
  data: {
    fuzz?: TestGroup;
    invalid_answer?: TestGroup;
    invalid_input?: TestGroup;
    invalid_output?: TestGroup;
    sample: TestGroup;
    secret: TestGroup;
    valid_output?: TestGroup;
  };
  /**
   * Generators are named like files or test cases, like "tree.py" or "a".
   * Each consists of a nonempty list of paths of dependencies relative to "/generators/",
   * such as ["tree_generator/tree.py", "lib.py"].
   */
  generators?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9_][a-zA-Z0-9_.-]{0,254}$".
     */
    [k: string]: [RelativePath, ...RelativePath[]] | undefined;
  };
  /**
   * A string that is be prepended to each command before computing its {seed}.
   * May be used to regenerate all random cases and to prevent predictable seeds.
   */
  random_salt?: string;
  /**
   * The maximum number of invocation that will be tried if the generator fails.
   * Each generator invocation uses a different value for {seed}.
   */
  retries?: number;
  /**
   * A model solution used for generating answer files, like "/submissions/accepted/intended.py"
   */
  solution?: string;
  'test_group.yaml'?: TestGroupConfiguration;
  version?: string;
  [k: string]: unknown | undefined;
}
/**
 * Test cases generated by "bt fuzz"
 */
export interface TestGroup {
  data?: DataDict | DataList[];
  include?: Path[];
  /**
   * A string that is be prepended to each command before computing its {seed}.
   * May be used to regenerate all random cases and to prevent predictable seeds.
   */
  random_salt?: string;
  /**
   * The maximum number of invocation that will be tried if the generator fails.
   * Each generator invocation uses a different value for {seed}.
   */
  retries?: number;
  /**
   * A model solution used for generating answer files, like "/submissions/accepted/intended.py"
   */
  solution?: string;
  'test_group.yaml'?: TestGroupConfiguration;
}
export interface DataDict {
  /**
   * This interface was referenced by `DataDict`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_][a-zA-Z0-9_.-]{0,254}$".
   */
  [k: string]: TestGroup | TestCase | undefined;
}
/**
 * Configuration for test_group.yaml (2025-09 format only -- legacy uses testdata.yaml,
 * #testdata_configuration, with an unrelated set of keys).
 */
export interface TestGroupConfiguration {
  max_score?: number | 'unbounded';
  require_pass?: 'sample' | TestDataGroup | ('sample' | TestDataGroup)[];
  score_aggregation?: 'pass-fail' | 'sum' | 'min';
  static_validation_score?: number | 'pass-fail';
}
/**
 * Test data configuration
 */
export interface TestCaseConfiguration {
  description?: string;
  hint?: string;
}
export interface DataList {
  [k: string]: unknown | undefined;
}
