/* eslint-disable */

/**
 * Paths are separated by /,  they may start with (but not end with) /.
 * Paths can both refer to objects like the test group "data/secret/huge" or
 * a program file like "/submissions/accepted/x.cpp"
 */
export type Path = string;
export type TestDataGroup = string;
export type TestCase =
  | Command
  | {
      /**
       * Generate an .ans-file whose contents are this string literal.
       */
      ans?: string;
      'ans.download'?:
        | string
        | {
            [k: string]: unknown | undefined;
          };
      'ans.statement'?:
        | string
        | {
            [k: string]: unknown | undefined;
          };
      /**
       * Create this test case by copying files from the given path.
       * The path is relative to "/generators/" and ends in a test case name,
       * such as "manual/samples/3".
       */
      copy?: string;
      count: (number | number[] | string) & number[];
      /**
       * Create this testcase by invoking a generator, like "generate: gen_tree -n 5"
       */
      generate?: string;
      /**
       * Generate an .in-file whose contents are this string literal.
       */
      in?: string;
      'in.download'?:
        | string
        | {
            [k: string]: unknown | undefined;
          };
      'in.statement'?:
        | string
        | {
            [k: string]: unknown | undefined;
          };
      interaction?: string;
      /**
       * Check that the generated testcase matches the given regex pattern(s).
       */
      match?:
        | string
        | string[]
        | {
            ans?: string | string[];
            in?: string | string[];
          };
      /**
       * Generate an .out-file whose contents are this string literal.
       */
      out?: string;
      /**
       * A string that is be prepended to each command before computing its {seed}.
       * May be used to regenerate all random cases and to prevent predictable seeds.
       */
      random_salt?: string;
      /**
       * The maximum number of invocation that will be tried if the generator fails.
       * Each generator invocation uses a different value for {seed}.
       */
      retries?: number;
      /**
       * A model solution used for generating answer files, like "/submissions/accepted/intended.py"
       */
      solution?: string;
      yaml?: TestCaseConfiguration;
    };
export type Command = string;
/**
 * Paths are separated by /,  they may start with (but not end with) /.
 * Paths can both refer to objects like the test group "data/secret/huge" or
 * a program file like "/submissions/accepted/x.cpp"
 */
export type RelativePath = string;

export interface ProblemPackageGenerators {
  data: {
    fuzz?: TestGroup;
    invalid_answer?: TestGroup2;
    invalid_input?: TestGroup3;
    invalid_output?: TestGroup4;
    sample: TestGroup5;
    secret: TestGroup6;
    valid_output?: TestGroup7;
  };
  /**
   * Generators are named like files or test cases, like "tree.py" or "a".
   * Each consists of a nonempty list of paths of dependencies relative to "/generators/",
   * such as ["tree_generator/tree.py", "lib.py"].
   */
  generators?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9_][a-zA-Z0-9_.-]{0,254}$".
     */
    [k: string]: {
      [k: string]: unknown | undefined;
    } & [RelativePath, ...RelativePath[]];
  };
  /**
   * A string that is be prepended to each command before computing its {seed}.
   * May be used to regenerate all random cases and to prevent predictable seeds.
   */
  random_salt?: string;
  /**
   * The maximum number of invocation that will be tried if the generator fails.
   * Each generator invocation uses a different value for {seed}.
   */
  retries?: number;
  /**
   * A model solution used for generating answer files, like "/submissions/accepted/intended.py"
   */
  solution?: string;
  'test_group.yaml'?: TestGroupConfiguration;
  version?: string;
  [k: string]: unknown | undefined;
}
/**
 * Test cases generated by "bt fuzz"
 */
export interface TestGroup {
  data?: DataDict | DataList[];
  include?: Path[];
  /**
   * A string that is be prepended to each command before computing its {seed}.
   * May be used to regenerate all random cases and to prevent predictable seeds.
   */
  random_salt?: string;
  /**
   * The maximum number of invocation that will be tried if the generator fails.
   * Each generator invocation uses a different value for {seed}.
   */
  retries?: number;
  /**
   * A model solution used for generating answer files, like "/submissions/accepted/intended.py"
   */
  solution?: string;
  'test_group.yaml'?: TestGroupConfiguration;
}
export interface DataDict {
  /**
   * This interface was referenced by `DataDict`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_][a-zA-Z0-9_.-]{0,254}$".
   */
  [k: string]: TestGroup1 | TestCase;
}
export interface TestGroup1 {
  data?: DataDict | DataList[];
  include?: Path[];
  /**
   * A string that is be prepended to each command before computing its {seed}.
   * May be used to regenerate all random cases and to prevent predictable seeds.
   */
  random_salt?: string;
  /**
   * The maximum number of invocation that will be tried if the generator fails.
   * Each generator invocation uses a different value for {seed}.
   */
  retries?: number;
  /**
   * A model solution used for generating answer files, like "/submissions/accepted/intended.py"
   */
  solution?: string;
  'test_group.yaml'?: TestGroupConfiguration;
}
export interface TestGroupConfiguration {
  answer_validator_args?:
    | string[]
    | {
        [k: string]: string[] | undefined;
      };
  args?: string[];
  full_feedback?: boolean;
  input_validator_args?:
    | string[]
    | {
        [k: string]: string[] | undefined;
      };
  input_visualizer_args?: string[];
  max_score?: number | 'unbounded';
  output_validator_args?: string[];
  output_visualizer_args?: string[];
  require_pass?: 'sample' | TestDataGroup | ('sample' | TestDataGroup)[];
  score_aggregation?: 'pass-fail' | 'sum' | 'min';
  static_validation_score?: number | 'pass-fail';
}
export interface TestCaseConfiguration {
  answer_validator_args?:
    | string[]
    | {
        [k: string]: string[] | undefined;
      };
  args?: string[];
  description?: string;
  full_feedback?: boolean;
  hint?: string;
  input_validator_args?:
    | string[]
    | {
        [k: string]: string[] | undefined;
      };
  input_visualizer_args?: string[];
  output_validator_args?: string[];
  output_visualizer_args?: string[];
}
export interface DataList {
  [k: string]: unknown | undefined;
}
/**
 * Invalid answer files that are used to test answer validation
 */
export interface TestGroup2 {
  data?: DataDict | DataList[];
  include?: Path[];
  /**
   * A string that is be prepended to each command before computing its {seed}.
   * May be used to regenerate all random cases and to prevent predictable seeds.
   */
  random_salt?: string;
  /**
   * The maximum number of invocation that will be tried if the generator fails.
   * Each generator invocation uses a different value for {seed}.
   */
  retries?: number;
  /**
   * A model solution used for generating answer files, like "/submissions/accepted/intended.py"
   */
  solution?: string;
  'test_group.yaml'?: TestGroupConfiguration;
}
/**
 * Invalid input files that are used to test input validation
 */
export interface TestGroup3 {
  data?: DataDict | DataList[];
  include?: Path[];
  /**
   * A string that is be prepended to each command before computing its {seed}.
   * May be used to regenerate all random cases and to prevent predictable seeds.
   */
  random_salt?: string;
  /**
   * The maximum number of invocation that will be tried if the generator fails.
   * Each generator invocation uses a different value for {seed}.
   */
  retries?: number;
  /**
   * A model solution used for generating answer files, like "/submissions/accepted/intended.py"
   */
  solution?: string;
  'test_group.yaml'?: TestGroupConfiguration;
}
/**
 * Files that describe invalid outputs for non-interactive problems.
 * They consist of three files. The input file tc.in, which must contain valid input. The output file tc.out
 * must fail output validation with the given answer file tc.ans.
 */
export interface TestGroup4 {
  data?: DataDict | DataList[];
  include?: Path[];
  /**
   * A string that is be prepended to each command before computing its {seed}.
   * May be used to regenerate all random cases and to prevent predictable seeds.
   */
  random_salt?: string;
  /**
   * The maximum number of invocation that will be tried if the generator fails.
   * Each generator invocation uses a different value for {seed}.
   */
  retries?: number;
  /**
   * A model solution used for generating answer files, like "/submissions/accepted/intended.py"
   */
  solution?: string;
  'test_group.yaml'?: TestGroupConfiguration;
}
/**
 * Test cases that are shared with solvers as part of the problem statement.
 */
export interface TestGroup5 {
  data?: DataDict | DataList[];
  include?: Path[];
  /**
   * A string that is be prepended to each command before computing its {seed}.
   * May be used to regenerate all random cases and to prevent predictable seeds.
   */
  random_salt?: string;
  /**
   * The maximum number of invocation that will be tried if the generator fails.
   * Each generator invocation uses a different value for {seed}.
   */
  retries?: number;
  /**
   * A model solution used for generating answer files, like "/submissions/accepted/intended.py"
   */
  solution?: string;
  'test_group.yaml'?: TestGroupConfiguration;
}
/**
 * Test cases that are not with solvers.
 */
export interface TestGroup6 {
  data?: DataDict | DataList[];
  include?: Path[];
  /**
   * A string that is be prepended to each command before computing its {seed}.
   * May be used to regenerate all random cases and to prevent predictable seeds.
   */
  random_salt?: string;
  /**
   * The maximum number of invocation that will be tried if the generator fails.
   * Each generator invocation uses a different value for {seed}.
   */
  retries?: number;
  /**
   * A model solution used for generating answer files, like "/submissions/accepted/intended.py"
   */
  solution?: string;
  'test_group.yaml'?: TestGroupConfiguration;
}
/**
 * Files that describe valid outputs for non-interactive problems. They consist of three files.
 *  The input file tc.in, which must contain valid input. The output file tc.out must pass output
 * validation with the given answer file tc.ans
 */
export interface TestGroup7 {
  data?: DataDict | DataList[];
  include?: Path[];
  /**
   * A string that is be prepended to each command before computing its {seed}.
   * May be used to regenerate all random cases and to prevent predictable seeds.
   */
  random_salt?: string;
  /**
   * The maximum number of invocation that will be tried if the generator fails.
   * Each generator invocation uses a different value for {seed}.
   */
  retries?: number;
  /**
   * A model solution used for generating answer files, like "/submissions/accepted/intended.py"
   */
  solution?: string;
  'test_group.yaml'?: TestGroupConfiguration;
}
