/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TheDownstreampathtemplateSchema = string;
export type TheUpstreampathtemplateSchema = string;
export type TheItemsSchema1 = string;
export type TheUpstreamhttpmethodSchema = TheItemsSchema1[];
export type TheRequestidkeySchema = string;
export type TheTtlsecondsSchema = number;
export type TheRegionSchema = string;
export type TheRouteiscasesensitiveSchema = boolean;
export type TheServicenameSchema = string;
export type TheDownstreamschemeSchema = string;
export type TheHostSchema = string;
export type ThePortSchema = number;
export type TheDownstreamhostandportsSchema = TheItemsSchema2[];
export type TheExceptionsallowedbeforebreakingSchema = number;
export type TheDurationofbreakSchema = number;
export type TheTimeoutvalueSchema = number;
export type TheLoadbalancerSchema = string;
export type TheClientwhitelistSchema = unknown[];
export type TheEnableratelimitingSchema = boolean;
export type ThePeriodSchema = string;
export type ThePeriodtimespanSchema = number;
export type TheLimitSchema = number;
export type TheAuthenticationproviderkeySchema = string;
export type TheAllowedscopesSchema = unknown[];
export type TheAllowautoredirectSchema = boolean;
export type TheUsecookiecontainerSchema = boolean;
export type TheUsetracingSchema = boolean;
export type TheDangerousacceptanyservercertificatevalidatorSchema = boolean;
export type TheRoutesSchema = TheItemsSchema[];
export type TheRequestidkeySchema1 = string;

export interface JSONSchemaForOcelotJson {
  Routes: TheRoutesSchema;
  GlobalConfiguration?: TheGlobalconfigurationSchema;
  [k: string]: unknown | undefined;
}
export interface TheItemsSchema {
  DownstreamPathTemplate?: TheDownstreampathtemplateSchema;
  UpstreamPathTemplate?: TheUpstreampathtemplateSchema;
  UpstreamHttpMethod?: TheUpstreamhttpmethodSchema;
  AddHeadersToRequest?: TheAddHeadersToRequestSchema;
  AddClaimsToRequest?: TheAddClaimsToRequestSchema;
  RouteClaimsRequirement?: TheRouteclaimsrequirementSchema;
  AddQueriesToRequest?: TheAddQueriesToRequestSchema;
  RequestIdKey?: TheRequestidkeySchema;
  FileCacheOptions?: TheFilecacheoptionsSchema;
  RouteIsCaseSensitive?: TheRouteiscasesensitiveSchema;
  ServiceName?: TheServicenameSchema;
  DownstreamScheme?: TheDownstreamschemeSchema;
  DownstreamHostAndPorts?: TheDownstreamhostandportsSchema;
  QoSOptions?: TheQosoptionsSchema;
  LoadBalancer?: TheLoadbalancerSchema;
  RateLimitOptions?: TheRatelimitoptionsSchema;
  AuthenticationOptions?: TheAuthenticationoptionsSchema;
  HttpHandlerOptions?: TheHttphandleroptionsSchema;
  DangerousAcceptAnyServerCertificateValidator?: TheDangerousacceptanyservercertificatevalidatorSchema;
  [k: string]: unknown | undefined;
}
export interface TheAddHeadersToRequestSchema {
  [k: string]: unknown | undefined;
}
export interface TheAddClaimsToRequestSchema {
  [k: string]: unknown | undefined;
}
export interface TheRouteclaimsrequirementSchema {
  [k: string]: unknown | undefined;
}
export interface TheAddQueriesToRequestSchema {
  [k: string]: unknown | undefined;
}
export interface TheFilecacheoptionsSchema {
  TtlSeconds?: TheTtlsecondsSchema;
  Region?: TheRegionSchema;
  [k: string]: unknown | undefined;
}
export interface TheItemsSchema2 {
  Host?: TheHostSchema;
  Port?: ThePortSchema;
  [k: string]: unknown | undefined;
}
export interface TheQosoptionsSchema {
  ExceptionsAllowedBeforeBreaking?: TheExceptionsallowedbeforebreakingSchema;
  DurationOfBreak?: TheDurationofbreakSchema;
  TimeoutValue?: TheTimeoutvalueSchema;
  [k: string]: unknown | undefined;
}
export interface TheRatelimitoptionsSchema {
  ClientWhitelist?: TheClientwhitelistSchema;
  EnableRateLimiting?: TheEnableratelimitingSchema;
  Period?: ThePeriodSchema;
  PeriodTimespan?: ThePeriodtimespanSchema;
  Limit?: TheLimitSchema;
  [k: string]: unknown | undefined;
}
export interface TheAuthenticationoptionsSchema {
  AuthenticationProviderKey?: TheAuthenticationproviderkeySchema;
  AllowedScopes?: TheAllowedscopesSchema;
  [k: string]: unknown | undefined;
}
export interface TheHttphandleroptionsSchema {
  AllowAutoRedirect?: TheAllowautoredirectSchema;
  UseCookieContainer?: TheUsecookiecontainerSchema;
  UseTracing?: TheUsetracingSchema;
  [k: string]: unknown | undefined;
}
export interface TheGlobalconfigurationSchema {
  RequestIdKey?: TheRequestidkeySchema1;
  [k: string]: unknown | undefined;
}
