/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Static Analysis Results Format (SARIF) Version 2.0.0-csd.2.beta-2019-01-24 JSON Schema: a standard format for the output of static analysis tools.
 */
export interface StaticAnalysisResultsFormatSARIFVersion200Csd2Beta20190124JSONSchema {
  /**
   * The URI of the JSON schema corresponding to the version.
   */
  $schema?: string;
  /**
   * The SARIF format version of this log file.
   */
  version: "2.0.0-csd.2.beta.2019-01-24";
  /**
   * The set of runs contained in this log file.
   *
   * @minItems 0
   */
  runs: Run[];
  /**
   * Key/value pairs that provide additional information about the log file.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Describes a single run of an analysis tool, and contains the reported output of that run.
 */
export interface Run {
  tool: Tool;
  /**
   * Describes the invocation of the analysis tool.
   *
   * @minItems 0
   */
  invocations?: Invocation[];
  conversion?: Conversion;
  /**
   * Specifies the revision in version control of the artifacts that were scanned.
   *
   * @minItems 0
   */
  versionControlProvenance?: VersionControlDetails[];
  /**
   * The artifact location specified by each uriBaseId symbol on the machine where the tool originally ran.
   */
  originalUriBaseIds?: {
    [k: string]: ArtifactLocation;
  };
  /**
   * An array of artifact objects relevant to the run.
   *
   * @minItems 0
   */
  artifacts?: Artifact[];
  /**
   * An array of logical locations such as namespaces, types or functions.
   *
   * @minItems 0
   */
  logicalLocations?: LogicalLocation[];
  /**
   * A dictionary, each of whose keys is the id of a graph and each of whose values is a 'graph' object with that id.
   */
  graphs?: {
    [k: string]: Graph;
  };
  /**
   * The set of results contained in an SARIF log. The results array can be omitted when a run is solely exporting rules metadata. It must be present (but may be empty) if a log file represents an actual scan.
   *
   * @minItems 0
   */
  results?: Result[];
  id?: RunAutomationDetails;
  /**
   * Automation details that describe the aggregate of runs to which this run belongs.
   *
   * @minItems 0
   */
  aggregateIds?: RunAutomationDetails1[];
  /**
   * The 'instanceGuid' property of a previous SARIF 'run' that comprises the baseline that was used to compute result 'baselineState' properties for the run.
   */
  baselineInstanceGuid?: string;
  /**
   * The MIME type of all Markdown text message properties in the run. Default: "text/markdown;variant=GFM"
   */
  markdownMessageMimeType?: string;
  /**
   * The string used to replace sensitive information in a redaction-aware property.
   */
  redactionToken?: string;
  /**
   * Specifies the default encoding for any artifact object that refers to a text file.
   */
  defaultFileEncoding?: string;
  /**
   * Specifies the default source language for any artifact object that refers to a text file that contains source code.
   */
  defaultSourceLanguage?: string;
  /**
   * An ordered list of character sequences that were treated as line breaks when computing region information for the run.
   *
   * @minItems 1
   */
  newlineSequences?: [string, ...string[]];
  /**
   * Specifies the unit in which the tool measures columns.
   */
  columnKind?: "utf16CodeUnits" | "unicodeCodePoints";
  externalPropertyFiles?: ExternalPropertyFiles;
  /**
   * Key/value pairs that provide additional information about the run.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Information about the tool or tool pipeline that generated the results in this run. A run can only contain results produced by a single tool or tool pipeline. A run can aggregate results from multiple log files, as long as context around the tool run (tool command-line arguments and the like) is identical for all aggregated files.
 */
export interface Tool {
  /**
   * The tool language (expressed as an ISO 649 two-letter lowercase culture code) and region (expressed as an ISO 3166 two-letter uppercase subculture code associated with a country or region).
   */
  language?: string;
  driver: ToolComponent;
  /**
   * Tool extensions that contributed to or reconfigured the analysis tool that was run.
   *
   * @minItems 0
   */
  extensions?: ToolComponent1[];
  /**
   * Key/value pairs that provide additional information about the tool.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * The analysis tool that was run.
 */
export interface ToolComponent {
  /**
   * The name of the component.
   */
  name: string;
  /**
   * The name of the component along with its version and any other useful identifying information, such as its locale.
   */
  fullName?: string;
  /**
   * The component version, in whatever format the component natively provides.
   */
  version?: string;
  /**
   * The component version in the format specified by Semantic Versioning 2.0.
   */
  semanticVersion?: string;
  /**
   * The binary version of the component's primary executable file expressed as four non-negative integers separated by a period (for operating systems that express file versions in this way).
   */
  dottedQuadFileVersion?: string;
  /**
   * The absolute URI from which the component can be downloaded.
   */
  downloadUri?: string;
  /**
   * A dictionary, each of whose keys is a resource identifier and each of whose values is a multiformatMessageString object, which holds message strings in plain text and (optionally) Markdown format. The strings can include placeholders, which can be used to construct a message in combination with an arbitrary number of additional string arguments.
   */
  globalMessageStrings?: {
    [k: string]: MultiformatMessageString;
  };
  /**
   * An array of reportDescriptor objects relevant to the notifications related to the configuration and runtime execution of the component.
   *
   * @minItems 0
   */
  notificationDescriptors?: ReportingDescriptor[];
  /**
   * An array of reportDescriptor objects relevant to the analysis performed by the component.
   *
   * @minItems 0
   */
  ruleDescriptors?: ReportingDescriptor[];
  /**
   * The index within the run artifacts array of the artifact object associated with the component.
   */
  artifactIndex?: number;
  /**
   * Key/value pairs that provide additional information about the component.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A message string or message format string rendered in multiple formats.
 */
export interface MultiformatMessageString {
  /**
   * A plain text message string or format string.
   */
  text?: string;
  /**
   * A Markdown message string or format string.
   */
  markdown?: string;
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Metadata that describes a specific report produced by the tool, as part of the analysis it provides or its runtime reporting.
 */
export interface ReportingDescriptor {
  /**
   * A stable, opaque identifier for the report.
   */
  id?: string;
  /**
   * An array of stable, opaque identifiers by which this report was known in some previous version of the analysis tool.
   *
   * @minItems 0
   */
  deprecatedIds?: string[];
  name?: Message;
  shortDescription?: Message1;
  fullDescription?: Message2;
  /**
   * A set of name/value pairs with arbitrary names. Each value is a multiformatMessageString object, which holds message strings in plain text and (optionally) Markdown format. The strings can include placeholders, which can be used to construct a message in combination with an arbitrary number of additional string arguments.
   */
  messageStrings?: {
    [k: string]: MultiformatMessageString;
  };
  defaultConfiguration?: ReportingConfiguration;
  /**
   * A URI where the primary documentation for the report can be found.
   */
  helpUri?: string;
  help?: Message3;
  /**
   * Key/value pairs that provide additional information about the report.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A report identifier that is understandable to an end user.
 */
export interface Message {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A concise description of the report. Should be a single sentence that is understandable when visible space is limited to a single line of text.
 */
export interface Message1 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A description of the report. Should, as far as possible, provide details sufficient to enable resolution of any problem indicated by the result.
 */
export interface Message2 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Default reporting configuration information.
 */
export interface ReportingConfiguration {
  /**
   * Specifies whether the report may be produced during the scan.
   */
  enabled?: boolean;
  /**
   * Specifies the failure level for the report.
   */
  level?: "none" | "note" | "warning" | "error";
  /**
   * Specifies the relative priority of the report. Used for analysis output only.
   */
  rank?: number;
  parameters?: PropertyBag;
  /**
   * Key/value pairs that provide additional information about the reporting configuration.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Contains configuration information specific to a report.
 */
export interface PropertyBag {
  /**
   * A set of distinct strings that provide additional information.
   *
   * @minItems 0
   */
  tags?: string[];
  [k: string]: unknown;
}
/**
 * Provides the primary documentation for the report, useful when there is no online documentation.
 */
export interface Message3 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A component, such as a plug-in or the default driver, of the analysis tool that was run.
 */
export interface ToolComponent1 {
  /**
   * The name of the component.
   */
  name: string;
  /**
   * The name of the component along with its version and any other useful identifying information, such as its locale.
   */
  fullName?: string;
  /**
   * The component version, in whatever format the component natively provides.
   */
  version?: string;
  /**
   * The component version in the format specified by Semantic Versioning 2.0.
   */
  semanticVersion?: string;
  /**
   * The binary version of the component's primary executable file expressed as four non-negative integers separated by a period (for operating systems that express file versions in this way).
   */
  dottedQuadFileVersion?: string;
  /**
   * The absolute URI from which the component can be downloaded.
   */
  downloadUri?: string;
  /**
   * A dictionary, each of whose keys is a resource identifier and each of whose values is a multiformatMessageString object, which holds message strings in plain text and (optionally) Markdown format. The strings can include placeholders, which can be used to construct a message in combination with an arbitrary number of additional string arguments.
   */
  globalMessageStrings?: {
    [k: string]: MultiformatMessageString;
  };
  /**
   * An array of reportDescriptor objects relevant to the notifications related to the configuration and runtime execution of the component.
   *
   * @minItems 0
   */
  notificationDescriptors?: ReportingDescriptor[];
  /**
   * An array of reportDescriptor objects relevant to the analysis performed by the component.
   *
   * @minItems 0
   */
  ruleDescriptors?: ReportingDescriptor[];
  /**
   * The index within the run artifacts array of the artifact object associated with the component.
   */
  artifactIndex?: number;
  /**
   * Key/value pairs that provide additional information about the component.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * The runtime environment of the analysis tool run.
 */
export interface Invocation {
  /**
   * The command line used to invoke the tool.
   */
  commandLine?: string;
  /**
   * An array of strings, containing in order the command line arguments passed to the tool from the operating system.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * The locations of any response files specified on the tool's command line.
   *
   * @minItems 0
   */
  responseFiles?: ArtifactLocation[];
  /**
   * A set of artifacts relevant to the invocation of the tool.
   *
   * @minItems 0
   */
  attachments?: Attachment[];
  /**
   * The Coordinated Universal Time (UTC) date and time at which the run started. See "Date/time properties" in the SARIF spec for the required format.
   */
  startTimeUtc?: string;
  /**
   * The Coordinated Universal Time (UTC) date and time at which the run ended. See "Date/time properties" in the SARIF spec for the required format.
   */
  endTimeUtc?: string;
  /**
   * The process exit code.
   */
  exitCode?: number;
  /**
   * An array of reportingConfigurationOverride objects that describe runtime reporting behavior.
   *
   * @minItems 0
   */
  reportingConfigurationOverrides?: ReportingConfigurationOverride[];
  /**
   * A list of runtime conditions detected by the tool during the analysis.
   *
   * @minItems 0
   */
  toolNotifications?: Notification[];
  /**
   * A list of conditions detected by the tool that are relevant to the tool's configuration.
   *
   * @minItems 0
   */
  configurationNotifications?: Notification[];
  /**
   * The reason for the process exit.
   */
  exitCodeDescription?: string;
  /**
   * The name of the signal that caused the process to exit.
   */
  exitSignalName?: string;
  /**
   * The numeric value of the signal that caused the process to exit.
   */
  exitSignalNumber?: number;
  /**
   * The reason given by the operating system that the process failed to start.
   */
  processStartFailureMessage?: string;
  /**
   * A value indicating whether the tool's execution completed successfully.
   */
  toolExecutionSuccessful?: boolean;
  /**
   * The machine that hosted the analysis tool run.
   */
  machine?: string;
  /**
   * The account that ran the analysis tool.
   */
  account?: string;
  /**
   * The process id for the analysis tool run.
   */
  processId?: number;
  executableLocation?: ArtifactLocation3;
  workingDirectory?: ArtifactLocation4;
  /**
   * The environment variables associated with the analysis tool process, expressed as key/value pairs.
   */
  environmentVariables?: {
    [k: string]: string;
  };
  stdin?: ArtifactLocation5;
  stdout?: ArtifactLocation6;
  stderr?: ArtifactLocation7;
  stdoutStderr?: ArtifactLocation8;
  /**
   * Key/value pairs that provide additional information about the invocation.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Specifies the location of an artifact.
 */
export interface ArtifactLocation {
  /**
   * A string containing a valid relative or absolute URI.
   */
  uri: string;
  /**
   * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
   */
  uriBaseId?: string;
  /**
   * The index within the run artifacts array of the artifact object associated with the artifact location.
   */
  index?: number;
  /**
   * Key/value pairs that provide additional information about the artifact location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * An artifact relevant to a tool invocation or to a result.
 */
export interface Attachment {
  description?: Message4;
  artifactLocation: ArtifactLocation1;
  /**
   * An array of regions of interest within the attachment.
   *
   * @minItems 0
   */
  regions?: Region[];
  /**
   * An array of rectangles specifying areas of interest within the image.
   *
   * @minItems 0
   */
  rectangles?: Rectangle[];
  /**
   * Key/value pairs that provide additional information about the attachment.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A message describing the role played by the attachment.
 */
export interface Message4 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * The location of the attachment.
 */
export interface ArtifactLocation1 {
  /**
   * A string containing a valid relative or absolute URI.
   */
  uri: string;
  /**
   * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
   */
  uriBaseId?: string;
  /**
   * The index within the run artifacts array of the artifact object associated with the artifact location.
   */
  index?: number;
  /**
   * Key/value pairs that provide additional information about the artifact location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A region within an artifact where a result was detected.
 */
export interface Region {
  /**
   * The line number of the first character in the region.
   */
  startLine?: number;
  /**
   * The column number of the first character in the region.
   */
  startColumn?: number;
  /**
   * The line number of the last character in the region.
   */
  endLine?: number;
  /**
   * The column number of the character following the end of the region.
   */
  endColumn?: number;
  /**
   * The zero-based offset from the beginning of the artifact of the first character in the region.
   */
  charOffset?: number;
  /**
   * The length of the region in characters.
   */
  charLength?: number;
  /**
   * The zero-based offset from the beginning of the artifact of the first byte in the region.
   */
  byteOffset?: number;
  /**
   * The length of the region in bytes.
   */
  byteLength?: number;
  snippet?: ArtifactContent;
  message?: Message5;
  /**
   * Specifies the source language, if any, of the portion of the artifact specified by the region object.
   */
  sourceLanguage?: string;
  /**
   * Key/value pairs that provide additional information about the region.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * The portion of the artifact contents within the specified region.
 */
export interface ArtifactContent {
  /**
   * UTF-8-encoded content from a text artifact.
   */
  text?: string;
  /**
   * MIME Base64-encoded content from a binary artifact, or from a text artifact in its original encoding.
   */
  binary?: string;
  /**
   * Key/value pairs that provide additional information about the artifact content.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A message relevant to the region.
 */
export interface Message5 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * An area within an image.
 */
export interface Rectangle {
  /**
   * The Y coordinate of the top edge of the rectangle, measured in the image's natural units.
   */
  top?: number;
  /**
   * The X coordinate of the left edge of the rectangle, measured in the image's natural units.
   */
  left?: number;
  /**
   * The Y coordinate of the bottom edge of the rectangle, measured in the image's natural units.
   */
  bottom?: number;
  /**
   * The X coordinate of the right edge of the rectangle, measured in the image's natural units.
   */
  right?: number;
  message?: Message6;
  /**
   * Key/value pairs that provide additional information about the rectangle.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A message relevant to the rectangle.
 */
export interface Message6 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Information about how a specific tool report was reconfigured at runtime.
 */
export interface ReportingConfigurationOverride {
  configuration?: ReportingConfiguration1;
  /**
   * The index within the toolComponent.notificationDescriptors array of the reportingDescriptor associated with this override.
   */
  notificationIndex?: number;
  /**
   * The index within the toolComponent.ruleDescriptors array of the reportingDescriptor associated with this override.
   */
  ruleIndex?: number;
  /**
   * The index within the run.tool.extensions array of the toolComponent object which describes the plug-in or tool extension that produced the report.
   */
  extensionIndex?: number;
  /**
   * Key/value pairs that provide additional information about the reporting configuration.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Specifies how the report was configured during the scan.
 */
export interface ReportingConfiguration1 {
  /**
   * Specifies whether the report may be produced during the scan.
   */
  enabled?: boolean;
  /**
   * Specifies the failure level for the report.
   */
  level?: "none" | "note" | "warning" | "error";
  /**
   * Specifies the relative priority of the report. Used for analysis output only.
   */
  rank?: number;
  parameters?: PropertyBag;
  /**
   * Key/value pairs that provide additional information about the reporting configuration.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Describes a condition relevant to the tool itself, as opposed to being relevant to a target being analyzed by the tool.
 */
export interface Notification {
  /**
   * An identifier for the condition that was encountered.
   */
  id?: string;
  /**
   * The stable, unique identifier of the rule, if any, to which this notification is relevant.
   */
  ruleId?: string;
  /**
   * The index within the run resources array of the rule object, if any, associated with this notification.
   */
  ruleIndex?: number;
  physicalLocation?: PhysicalLocation;
  message: Message7;
  /**
   * A value specifying the severity level of the notification.
   */
  level?: "none" | "note" | "warning" | "error";
  /**
   * The thread identifier of the code that generated the notification.
   */
  threadId?: number;
  /**
   * The Coordinated Universal Time (UTC) date and time at which the analysis tool generated the notification.
   */
  timeUtc?: string;
  exception?: Exception;
  /**
   * Key/value pairs that provide additional information about the notification.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * The artifact and region relevant to this notification.
 */
export interface PhysicalLocation {
  /**
   * Value that distinguishes this physical location from all other physical locations in this run object.
   */
  id?: number;
  artifactLocation: ArtifactLocation2;
  region?: Region1;
  contextRegion?: Region2;
  /**
   * Key/value pairs that provide additional information about the physical location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * The location of the artifact.
 */
export interface ArtifactLocation2 {
  /**
   * A string containing a valid relative or absolute URI.
   */
  uri: string;
  /**
   * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
   */
  uriBaseId?: string;
  /**
   * The index within the run artifacts array of the artifact object associated with the artifact location.
   */
  index?: number;
  /**
   * Key/value pairs that provide additional information about the artifact location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A region within an artifact where a result was detected.
 */
export interface Region1 {
  /**
   * The line number of the first character in the region.
   */
  startLine?: number;
  /**
   * The column number of the first character in the region.
   */
  startColumn?: number;
  /**
   * The line number of the last character in the region.
   */
  endLine?: number;
  /**
   * The column number of the character following the end of the region.
   */
  endColumn?: number;
  /**
   * The zero-based offset from the beginning of the artifact of the first character in the region.
   */
  charOffset?: number;
  /**
   * The length of the region in characters.
   */
  charLength?: number;
  /**
   * The zero-based offset from the beginning of the artifact of the first byte in the region.
   */
  byteOffset?: number;
  /**
   * The length of the region in bytes.
   */
  byteLength?: number;
  snippet?: ArtifactContent;
  message?: Message5;
  /**
   * Specifies the source language, if any, of the portion of the artifact specified by the region object.
   */
  sourceLanguage?: string;
  /**
   * Key/value pairs that provide additional information about the region.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A region within an artifact where a result was detected.
 */
export interface Region2 {
  /**
   * The line number of the first character in the region.
   */
  startLine?: number;
  /**
   * The column number of the first character in the region.
   */
  startColumn?: number;
  /**
   * The line number of the last character in the region.
   */
  endLine?: number;
  /**
   * The column number of the character following the end of the region.
   */
  endColumn?: number;
  /**
   * The zero-based offset from the beginning of the artifact of the first character in the region.
   */
  charOffset?: number;
  /**
   * The length of the region in characters.
   */
  charLength?: number;
  /**
   * The zero-based offset from the beginning of the artifact of the first byte in the region.
   */
  byteOffset?: number;
  /**
   * The length of the region in bytes.
   */
  byteLength?: number;
  snippet?: ArtifactContent;
  message?: Message5;
  /**
   * Specifies the source language, if any, of the portion of the artifact specified by the region object.
   */
  sourceLanguage?: string;
  /**
   * Key/value pairs that provide additional information about the region.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A message that describes the condition that was encountered.
 */
export interface Message7 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * The runtime exception, if any, relevant to this notification.
 */
export interface Exception {
  /**
   * A string that identifies the kind of exception, for example, the fully qualified type name of an object that was thrown, or the symbolic name of a signal.
   */
  kind?: string;
  message?: Message8;
  stack?: Stack;
  /**
   * An array of exception objects each of which is considered a cause of this exception.
   *
   * @minItems 0
   */
  innerExceptions?: Exception1[];
  /**
   * Key/value pairs that provide additional information about the exception.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * A message that describes the exception.
 */
export interface Message8 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * The sequence of function calls leading to the exception.
 */
export interface Stack {
  message?: Message9;
  /**
   * An array of stack frames that represents a sequence of calls, rendered in reverse chronological order, that comprise the call stack.
   *
   * @minItems 0
   */
  frames: StackFrame[];
  /**
   * Key/value pairs that provide additional information about the stack.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A message relevant to this call stack.
 */
export interface Message9 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A function call within a stack trace.
 */
export interface StackFrame {
  location?: Location;
  /**
   * The name of the module that contains the code of this stack frame.
   */
  module?: string;
  /**
   * The thread identifier of the stack frame.
   */
  threadId?: number;
  /**
   * The address of the method or function that is executing.
   */
  address?: number;
  /**
   * The offset from the method or function that is executing.
   */
  offset?: number;
  /**
   * The parameters of the call that is executing.
   *
   * @minItems 0
   */
  parameters?: string[];
  /**
   * Key/value pairs that provide additional information about the stack frame.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * The location to which this stack frame refers.
 */
export interface Location {
  physicalLocation?: PhysicalLocation1;
  /**
   * The human-readable fully qualified name of the logical location. If run.logicalLocations is present, this value matches a property name within that object, from which further information about the logical location can be obtained.
   */
  fullyQualifiedLogicalName?: string;
  /**
   * The index within the logical locations array of the logical location associated with the result.
   */
  logicalLocationIndex?: number;
  message?: Message10;
  /**
   * A set of regions relevant to the location.
   *
   * @minItems 0
   */
  annotations?: Region[];
  /**
   * Key/value pairs that provide additional information about the location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Identifies the artifact and region.
 */
export interface PhysicalLocation1 {
  /**
   * Value that distinguishes this physical location from all other physical locations in this run object.
   */
  id?: number;
  artifactLocation: ArtifactLocation2;
  region?: Region1;
  contextRegion?: Region2;
  /**
   * Key/value pairs that provide additional information about the physical location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A message relevant to the location.
 */
export interface Message10 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
export interface Exception1 {
  /**
   * A string that identifies the kind of exception, for example, the fully qualified type name of an object that was thrown, or the symbolic name of a signal.
   */
  kind?: string;
  message?: Message8;
  stack?: Stack;
  /**
   * An array of exception objects each of which is considered a cause of this exception.
   *
   * @minItems 0
   */
  innerExceptions?: Exception1[];
  /**
   * Key/value pairs that provide additional information about the exception.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Specifies the location of an artifact.
 */
export interface ArtifactLocation3 {
  /**
   * A string containing a valid relative or absolute URI.
   */
  uri: string;
  /**
   * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
   */
  uriBaseId?: string;
  /**
   * The index within the run artifacts array of the artifact object associated with the artifact location.
   */
  index?: number;
  /**
   * Key/value pairs that provide additional information about the artifact location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Specifies the location of an artifact.
 */
export interface ArtifactLocation4 {
  /**
   * A string containing a valid relative or absolute URI.
   */
  uri: string;
  /**
   * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
   */
  uriBaseId?: string;
  /**
   * The index within the run artifacts array of the artifact object associated with the artifact location.
   */
  index?: number;
  /**
   * Key/value pairs that provide additional information about the artifact location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Specifies the location of an artifact.
 */
export interface ArtifactLocation5 {
  /**
   * A string containing a valid relative or absolute URI.
   */
  uri: string;
  /**
   * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
   */
  uriBaseId?: string;
  /**
   * The index within the run artifacts array of the artifact object associated with the artifact location.
   */
  index?: number;
  /**
   * Key/value pairs that provide additional information about the artifact location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Specifies the location of an artifact.
 */
export interface ArtifactLocation6 {
  /**
   * A string containing a valid relative or absolute URI.
   */
  uri: string;
  /**
   * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
   */
  uriBaseId?: string;
  /**
   * The index within the run artifacts array of the artifact object associated with the artifact location.
   */
  index?: number;
  /**
   * Key/value pairs that provide additional information about the artifact location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Specifies the location of an artifact.
 */
export interface ArtifactLocation7 {
  /**
   * A string containing a valid relative or absolute URI.
   */
  uri: string;
  /**
   * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
   */
  uriBaseId?: string;
  /**
   * The index within the run artifacts array of the artifact object associated with the artifact location.
   */
  index?: number;
  /**
   * Key/value pairs that provide additional information about the artifact location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Specifies the location of an artifact.
 */
export interface ArtifactLocation8 {
  /**
   * A string containing a valid relative or absolute URI.
   */
  uri: string;
  /**
   * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
   */
  uriBaseId?: string;
  /**
   * The index within the run artifacts array of the artifact object associated with the artifact location.
   */
  index?: number;
  /**
   * Key/value pairs that provide additional information about the artifact location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A conversion object that describes how a converter transformed an analysis tool's native reporting format into the SARIF format.
 */
export interface Conversion {
  tool: Tool1;
  invocation?: Invocation1;
  /**
   * The locations of the analysis tool's per-run log files.
   *
   * @minItems 0
   */
  analysisToolLogFiles?: ArtifactLocation[];
  /**
   * Key/value pairs that provide additional information about the conversion.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A tool object that describes the converter.
 */
export interface Tool1 {
  /**
   * The tool language (expressed as an ISO 649 two-letter lowercase culture code) and region (expressed as an ISO 3166 two-letter uppercase subculture code associated with a country or region).
   */
  language?: string;
  driver: ToolComponent;
  /**
   * Tool extensions that contributed to or reconfigured the analysis tool that was run.
   *
   * @minItems 0
   */
  extensions?: ToolComponent1[];
  /**
   * Key/value pairs that provide additional information about the tool.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * An invocation object that describes the invocation of the converter.
 */
export interface Invocation1 {
  /**
   * The command line used to invoke the tool.
   */
  commandLine?: string;
  /**
   * An array of strings, containing in order the command line arguments passed to the tool from the operating system.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * The locations of any response files specified on the tool's command line.
   *
   * @minItems 0
   */
  responseFiles?: ArtifactLocation[];
  /**
   * A set of artifacts relevant to the invocation of the tool.
   *
   * @minItems 0
   */
  attachments?: Attachment[];
  /**
   * The Coordinated Universal Time (UTC) date and time at which the run started. See "Date/time properties" in the SARIF spec for the required format.
   */
  startTimeUtc?: string;
  /**
   * The Coordinated Universal Time (UTC) date and time at which the run ended. See "Date/time properties" in the SARIF spec for the required format.
   */
  endTimeUtc?: string;
  /**
   * The process exit code.
   */
  exitCode?: number;
  /**
   * An array of reportingConfigurationOverride objects that describe runtime reporting behavior.
   *
   * @minItems 0
   */
  reportingConfigurationOverrides?: ReportingConfigurationOverride[];
  /**
   * A list of runtime conditions detected by the tool during the analysis.
   *
   * @minItems 0
   */
  toolNotifications?: Notification[];
  /**
   * A list of conditions detected by the tool that are relevant to the tool's configuration.
   *
   * @minItems 0
   */
  configurationNotifications?: Notification[];
  /**
   * The reason for the process exit.
   */
  exitCodeDescription?: string;
  /**
   * The name of the signal that caused the process to exit.
   */
  exitSignalName?: string;
  /**
   * The numeric value of the signal that caused the process to exit.
   */
  exitSignalNumber?: number;
  /**
   * The reason given by the operating system that the process failed to start.
   */
  processStartFailureMessage?: string;
  /**
   * A value indicating whether the tool's execution completed successfully.
   */
  toolExecutionSuccessful?: boolean;
  /**
   * The machine that hosted the analysis tool run.
   */
  machine?: string;
  /**
   * The account that ran the analysis tool.
   */
  account?: string;
  /**
   * The process id for the analysis tool run.
   */
  processId?: number;
  executableLocation?: ArtifactLocation3;
  workingDirectory?: ArtifactLocation4;
  /**
   * The environment variables associated with the analysis tool process, expressed as key/value pairs.
   */
  environmentVariables?: {
    [k: string]: string;
  };
  stdin?: ArtifactLocation5;
  stdout?: ArtifactLocation6;
  stderr?: ArtifactLocation7;
  stdoutStderr?: ArtifactLocation8;
  /**
   * Key/value pairs that provide additional information about the invocation.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Specifies the information necessary to retrieve a desired revision from a version control system.
 */
export interface VersionControlDetails {
  /**
   * The absolute URI of the repository.
   */
  repositoryUri: string;
  /**
   * A string that uniquely and permanently identifies the revision within the repository.
   */
  revisionId?: string;
  /**
   * The name of a branch containing the revision.
   */
  branch?: string;
  /**
   * A tag that has been applied to the revision.
   */
  revisionTag?: string;
  /**
   * A Coordinated Universal Time (UTC) date and time that can be used to synchronize an enlistment to the state of the repository at that time.
   */
  asOfTimeUtc?: string;
  mappedTo?: ArtifactLocation9;
  /**
   * Key/value pairs that provide additional information about the version control details.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Specifies the location of an artifact.
 */
export interface ArtifactLocation9 {
  /**
   * A string containing a valid relative or absolute URI.
   */
  uri: string;
  /**
   * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
   */
  uriBaseId?: string;
  /**
   * The index within the run artifacts array of the artifact object associated with the artifact location.
   */
  index?: number;
  /**
   * Key/value pairs that provide additional information about the artifact location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A single artifact. In some cases, this artifact might be nested within another artifact.
 */
export interface Artifact {
  location?: ArtifactLocation10;
  /**
   * Identifies the index of the immediate parent of the artifact, if this artifact is nested.
   */
  parentIndex?: number;
  /**
   * The offset in bytes of the artifact within its containing artifact.
   */
  offset?: number;
  /**
   * The length of the artifact in bytes.
   */
  length?: number;
  /**
   * The role or roles played by the artifact in the analysis.
   *
   * @minItems 0
   */
  roles?: (
    | "analysisTarget"
    | "toolComponent"
    | "attachment"
    | "responseFile"
    | "resultFile"
    | "standardStream"
    | "traceFile"
    | "unmodifiedFile"
    | "modifiedFile"
    | "addedFile"
    | "deletedFile"
    | "renamedFile"
    | "uncontrolledFile"
  )[];
  /**
   * The MIME type (RFC 2045) of the artifact.
   */
  mimeType?: string;
  contents?: ArtifactContent1;
  /**
   * Specifies the encoding for an artifact object that refers to a text file.
   */
  encoding?: string;
  /**
   * Specifies the source language for any artifact object that refers to a text file that contains source code.
   */
  sourceLanguage?: string;
  /**
   * A dictionary, each of whose keys is the name of a hash function and each of whose values is the hashed value of the artifact produced by the specified hash function.
   */
  hashes?: {
    [k: string]: string;
  };
  /**
   * The Coordinated Universal Time (UTC) date and time at which the artifact was most recently modified. See "Date/time properties" in the SARIF spec for the required format.
   */
  lastModifiedTimeUtc?: string;
  /**
   * Key/value pairs that provide additional information about the artifact.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * The location of the artifact.
 */
export interface ArtifactLocation10 {
  /**
   * A string containing a valid relative or absolute URI.
   */
  uri: string;
  /**
   * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
   */
  uriBaseId?: string;
  /**
   * The index within the run artifacts array of the artifact object associated with the artifact location.
   */
  index?: number;
  /**
   * Key/value pairs that provide additional information about the artifact location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * The contents of the artifact.
 */
export interface ArtifactContent1 {
  /**
   * UTF-8-encoded content from a text artifact.
   */
  text?: string;
  /**
   * MIME Base64-encoded content from a binary artifact, or from a text artifact in its original encoding.
   */
  binary?: string;
  /**
   * Key/value pairs that provide additional information about the artifact content.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A logical location of a construct that produced a result.
 */
export interface LogicalLocation {
  /**
   * Identifies the construct in which the result occurred. For example, this property might contain the name of a class or a method.
   */
  name?: string;
  /**
   * The human-readable fully qualified name of the logical location.
   */
  fullyQualifiedName?: string;
  /**
   * The machine-readable name for the logical location, such as a mangled function name provided by a C++ compiler that encodes calling convention, return type and other details along with the function name.
   */
  decoratedName?: string;
  /**
   * Identifies the index of the immediate parent of the construct in which the result was detected. For example, this property might point to a logical location that represents the namespace that holds a type.
   */
  parentIndex?: number;
  /**
   * The type of construct this logical location component refers to. Should be one of 'function', 'member', 'module', 'namespace', 'parameter', 'resource', 'returnType', 'type', or 'variable', if any of those accurately describe the construct.
   */
  kind?: string;
  /**
   * Key/value pairs that provide additional information about the logical location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A network of nodes and directed edges that describes some aspect of the structure of the code (for example, a call graph).
 */
export interface Graph {
  /**
   * A string that uniquely identifies the graph within a run.graphs or result.graphs array.
   */
  id: string;
  description?: Message11;
  /**
   * An array of node objects representing the nodes of the graph.
   *
   * @minItems 0
   */
  nodes?: Node[];
  /**
   * An array of edge objects representing the edges of the graph.
   *
   * @minItems 0
   */
  edges?: Edge[];
  /**
   * Key/value pairs that provide additional information about the graph.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A description of the graph.
 */
export interface Message11 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Represents a node in a graph.
 */
export interface Node {
  /**
   * A string that uniquely identifies the node within its graph.
   */
  id: string;
  label?: Message12;
  location?: Location1;
  /**
   * Array of child nodes.
   *
   * @minItems 0
   */
  children?: Node[];
  /**
   * Key/value pairs that provide additional information about the node.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A short description of the node.
 */
export interface Message12 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A code location associated with the node.
 */
export interface Location1 {
  physicalLocation?: PhysicalLocation1;
  /**
   * The human-readable fully qualified name of the logical location. If run.logicalLocations is present, this value matches a property name within that object, from which further information about the logical location can be obtained.
   */
  fullyQualifiedLogicalName?: string;
  /**
   * The index within the logical locations array of the logical location associated with the result.
   */
  logicalLocationIndex?: number;
  message?: Message10;
  /**
   * A set of regions relevant to the location.
   *
   * @minItems 0
   */
  annotations?: Region[];
  /**
   * Key/value pairs that provide additional information about the location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Represents a directed edge in a graph.
 */
export interface Edge {
  /**
   * A string that uniquely identifies the edge within its graph.
   */
  id: string;
  label?: Message13;
  /**
   * Identifies the source node (the node at which the edge starts).
   */
  sourceNodeId: string;
  /**
   * Identifies the target node (the node at which the edge ends).
   */
  targetNodeId: string;
  /**
   * Key/value pairs that provide additional information about the edge.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A short description of the edge.
 */
export interface Message13 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A result produced by an analysis tool.
 */
export interface Result {
  /**
   * The stable, unique identifier of the rule, if any, to which this notification is relevant. This member can be used to retrieve rule metadata from the rules dictionary, if it exists.
   */
  ruleId?: string;
  /**
   * The index within the run resources array of the rule object associated with this result.
   */
  ruleIndex?: number;
  /**
   * The index within the run.tool.extensions array of the tool component object which describes the plug-in or tool extension that produced the result.
   */
  ruleExtensionIndex?: number;
  /**
   * A value that categorizes results by evaluation state.
   */
  kind?: "notApplicable" | "pass" | "fail" | "review" | "open";
  /**
   * A value specifying the severity level of the result.
   */
  level?: "none" | "note" | "warning" | "error";
  message: Message14;
  analysisTarget?: ArtifactLocation11;
  /**
   * The set of locations where the result was detected. Specify only one location unless the problem indicated by the result can only be corrected by making a change at every specified location.
   *
   * @minItems 0
   */
  locations?: Location2[];
  /**
   * A stable, unique identifier for the result in the form of a GUID.
   */
  instanceGuid?: string;
  /**
   * A stable, unique identifier for the equivalence class of logically identical results to which this result belongs, in the form of a GUID.
   */
  correlationGuid?: string;
  /**
   * A positive integer specifying the number of times this logically unique result was observed in this run.
   */
  occurrenceCount?: number;
  /**
   * A set of strings that contribute to the stable, unique identity of the result.
   */
  partialFingerprints?: {
    [k: string]: string;
  };
  /**
   * A set of strings each of which individually defines a stable, unique identity for the result.
   */
  fingerprints?: {
    [k: string]: string;
  };
  /**
   * An array of 'stack' objects relevant to the result.
   *
   * @minItems 0
   */
  stacks?: Stack1[];
  /**
   * An array of 'codeFlow' objects relevant to the result.
   *
   * @minItems 0
   */
  codeFlows?: CodeFlow[];
  /**
   * A dictionary, each of whose keys is the id of a graph and each of whose values is a 'graph' object with that id.
   */
  graphs?: {
    [k: string]: Graph;
  };
  /**
   * An array of one or more unique 'graphTraversal' objects.
   *
   * @minItems 1
   */
  graphTraversals?: [GraphTraversal, ...GraphTraversal[]];
  /**
   * A set of locations relevant to this result.
   *
   * @minItems 0
   */
  relatedLocations?: Location2[];
  /**
   * A set of flags indicating one or more suppression conditions.
   *
   * @minItems 0
   */
  suppressionStates?: ("suppressedInSource" | "suppressedExternally")[];
  /**
   * The state of a result relative to a baseline of a previous run.
   */
  baselineState?: "new" | "unchanged" | "updated" | "absent";
  /**
   * A number representing the priority or importance of the result.
   */
  rank?: number;
  /**
   * A set of artifacts relevant to the result.
   *
   * @minItems 0
   */
  attachments?: Attachment[];
  /**
   * An absolute URI at which the result can be viewed.
   */
  hostedViewerUri?: string;
  /**
   * The URIs of the work items associated with this result.
   *
   * @minItems 0
   */
  workItemUris?: string[];
  provenance?: ResultProvenance;
  /**
   * An array of 'fix' objects, each of which represents a proposed fix to the problem indicated by the result.
   *
   * @minItems 0
   */
  fixes?: Fix[];
  /**
   * Key/value pairs that provide additional information about the result.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A message that describes the result. The first sentence of the message only will be displayed when visible space is limited.
 */
export interface Message14 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Specifies the location of an artifact.
 */
export interface ArtifactLocation11 {
  /**
   * A string containing a valid relative or absolute URI.
   */
  uri: string;
  /**
   * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
   */
  uriBaseId?: string;
  /**
   * The index within the run artifacts array of the artifact object associated with the artifact location.
   */
  index?: number;
  /**
   * Key/value pairs that provide additional information about the artifact location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A location within a programming artifact.
 */
export interface Location2 {
  physicalLocation?: PhysicalLocation1;
  /**
   * The human-readable fully qualified name of the logical location. If run.logicalLocations is present, this value matches a property name within that object, from which further information about the logical location can be obtained.
   */
  fullyQualifiedLogicalName?: string;
  /**
   * The index within the logical locations array of the logical location associated with the result.
   */
  logicalLocationIndex?: number;
  message?: Message10;
  /**
   * A set of regions relevant to the location.
   *
   * @minItems 0
   */
  annotations?: Region[];
  /**
   * Key/value pairs that provide additional information about the location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A call stack that is relevant to a result.
 */
export interface Stack1 {
  message?: Message9;
  /**
   * An array of stack frames that represents a sequence of calls, rendered in reverse chronological order, that comprise the call stack.
   *
   * @minItems 0
   */
  frames: StackFrame[];
  /**
   * Key/value pairs that provide additional information about the stack.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A set of threadFlows which together describe a pattern of code execution relevant to detecting a result.
 */
export interface CodeFlow {
  message?: Message15;
  /**
   * An array of one or more unique threadFlow objects, each of which describes the progress of a program through a thread of execution.
   *
   * @minItems 1
   */
  threadFlows: [ThreadFlow, ...ThreadFlow[]];
  /**
   * Key/value pairs that provide additional information about the code flow.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A message relevant to the code flow.
 */
export interface Message15 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
export interface ThreadFlow {
  /**
   * An string that uniquely identifies the threadFlow within the codeFlow in which it occurs.
   */
  id?: string;
  message?: Message16;
  /**
   * A temporally ordered array of 'threadFlowLocation' objects, each of which describes a location visited by the tool while producing the result.
   *
   * @minItems 1
   */
  locations: [ThreadFlowLocation, ...ThreadFlowLocation[]];
  /**
   * Key/value pairs that provide additional information about the thread flow.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * A message relevant to the thread flow.
 */
export interface Message16 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A location visited by an analysis tool while simulating or monitoring the execution of a program.
 */
export interface ThreadFlowLocation {
  location?: Location3;
  stack?: Stack2;
  /**
   * A set of distinct strings that categorize the thread flow location. Well-known kinds include acquire, release, enter, exit, call, return, branch, implicit, false, true, caution, danger, unknown, unreachable, taint, function, handler, lock, memory, resource, and scope.
   *
   * @minItems 0
   */
  kinds?: string[];
  /**
   * The name of the module that contains the code that is executing.
   */
  module?: string;
  /**
   * A dictionary, each of whose keys specifies a variable or expression, the associated value of which represents the variable or expression value. For an annotation of kind 'continuation', for example, this dictionary might hold the current assumed values of a set of global variables.
   */
  state?: {
    [k: string]: string;
  };
  /**
   * An integer representing a containment hierarchy within the thread flow.
   */
  nestingLevel?: number;
  /**
   * An integer representing the temporal order in which execution reached this location.
   */
  executionOrder?: number;
  /**
   * The Coordinated Universal Time (UTC) date and time at which this location was executed.
   */
  executionTimeUtc?: string;
  /**
   * Specifies the importance of this location in understanding the code flow in which it occurs. The order from most to least important is "essential", "important", "unimportant". Default: "important".
   */
  importance?: "important" | "essential" | "unimportant";
  /**
   * Key/value pairs that provide additional information about the threadflow location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * The code location.
 */
export interface Location3 {
  physicalLocation?: PhysicalLocation1;
  /**
   * The human-readable fully qualified name of the logical location. If run.logicalLocations is present, this value matches a property name within that object, from which further information about the logical location can be obtained.
   */
  fullyQualifiedLogicalName?: string;
  /**
   * The index within the logical locations array of the logical location associated with the result.
   */
  logicalLocationIndex?: number;
  message?: Message10;
  /**
   * A set of regions relevant to the location.
   *
   * @minItems 0
   */
  annotations?: Region[];
  /**
   * Key/value pairs that provide additional information about the location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * The call stack leading to this location.
 */
export interface Stack2 {
  message?: Message9;
  /**
   * An array of stack frames that represents a sequence of calls, rendered in reverse chronological order, that comprise the call stack.
   *
   * @minItems 0
   */
  frames: StackFrame[];
  /**
   * Key/value pairs that provide additional information about the stack.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Represents a path through a graph.
 */
export interface GraphTraversal {
  /**
   * A string that uniquely identifies that graph being traversed.
   */
  graphId: string;
  description?: Message17;
  /**
   * Values of relevant expressions at the start of the graph traversal.
   */
  initialState?: {
    [k: string]: string;
  };
  /**
   * The sequences of edges traversed by this graph traversal.
   *
   * @minItems 0
   */
  edgeTraversals?: EdgeTraversal[];
  /**
   * Key/value pairs that provide additional information about the graph traversal.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A description of this graph traversal.
 */
export interface Message17 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Represents the traversal of a single edge during a graph traversal.
 */
export interface EdgeTraversal {
  /**
   * Identifies the edge being traversed.
   */
  edgeId: string;
  message?: Message18;
  /**
   * The values of relevant expressions after the edge has been traversed.
   */
  finalState?: {
    [k: string]: string;
  };
  /**
   * The number of edge traversals necessary to return from a nested graph.
   */
  stepOverEdgeCount?: number;
  /**
   * Key/value pairs that provide additional information about the edge traversal.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A message to display to the user as the edge is traversed.
 */
export interface Message18 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Information about how and when the result was detected.
 */
export interface ResultProvenance {
  /**
   * The Coordinated Universal Time (UTC) date and time at which the result was first detected. See "Date/time properties" in the SARIF spec for the required format.
   */
  firstDetectionTimeUtc?: string;
  /**
   * The Coordinated Universal Time (UTC) date and time at which the result was most recently detected. See "Date/time properties" in the SARIF spec for the required format.
   */
  lastDetectionTimeUtc?: string;
  /**
   * A GUID-valued string equal to the id.instanceGuid property of the run in which the result was first detected.
   */
  firstDetectionRunInstanceGuid?: string;
  /**
   * A GUID-valued string equal to the id.instanceGuid property of the run in which the result was most recently detected.
   */
  lastDetectionRunInstanceGuid?: string;
  /**
   * The index within the run.invocations array of the invocation object which describes the tool invocation that detected the result.
   */
  invocationIndex?: number;
  /**
   * An array of physicalLocation objects which specify the portions of an analysis tool's output that a converter transformed into the result.
   *
   * @minItems 0
   */
  conversionSources?: PhysicalLocation2[];
  /**
   * Key/value pairs that provide additional information about the result.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A physical location relevant to a result. Specifies a reference to a programming artifact together with a range of bytes or characters within that artifact.
 */
export interface PhysicalLocation2 {
  /**
   * Value that distinguishes this physical location from all other physical locations in this run object.
   */
  id?: number;
  artifactLocation: ArtifactLocation2;
  region?: Region1;
  contextRegion?: Region2;
  /**
   * Key/value pairs that provide additional information about the physical location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A proposed fix for the problem represented by a result object. A fix specifies a set of artifacts to modify. For each artifact, it specifies a set of bytes to remove, and provides a set of new bytes to replace them.
 */
export interface Fix {
  description?: Message19;
  /**
   * One or more artifact changes that comprise a fix for a result.
   *
   * @minItems 1
   */
  changes: [ArtifactChange, ...ArtifactChange[]];
  /**
   * Key/value pairs that provide additional information about the fix.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A message that describes the proposed fix, enabling viewers to present the proposed change to an end user.
 */
export interface Message19 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A change to a single artifact.
 */
export interface ArtifactChange {
  artifactLocation: ArtifactLocation12;
  /**
   * An array of replacement objects, each of which represents the replacement of a single region in a single artifact specified by 'artifactLocation'.
   *
   * @minItems 1
   */
  replacements: [Replacement, ...Replacement[]];
  /**
   * Key/value pairs that provide additional information about the change.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * The location of the artifact to change.
 */
export interface ArtifactLocation12 {
  /**
   * A string containing a valid relative or absolute URI.
   */
  uri: string;
  /**
   * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
   */
  uriBaseId?: string;
  /**
   * The index within the run artifacts array of the artifact object associated with the artifact location.
   */
  index?: number;
  /**
   * Key/value pairs that provide additional information about the artifact location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * The replacement of a single region of an artifact.
 */
export interface Replacement {
  deletedRegion: Region3;
  insertedContent?: ArtifactContent2;
  /**
   * Key/value pairs that provide additional information about the replacement.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * The region of the artifact to delete.
 */
export interface Region3 {
  /**
   * The line number of the first character in the region.
   */
  startLine?: number;
  /**
   * The column number of the first character in the region.
   */
  startColumn?: number;
  /**
   * The line number of the last character in the region.
   */
  endLine?: number;
  /**
   * The column number of the character following the end of the region.
   */
  endColumn?: number;
  /**
   * The zero-based offset from the beginning of the artifact of the first character in the region.
   */
  charOffset?: number;
  /**
   * The length of the region in characters.
   */
  charLength?: number;
  /**
   * The zero-based offset from the beginning of the artifact of the first byte in the region.
   */
  byteOffset?: number;
  /**
   * The length of the region in bytes.
   */
  byteLength?: number;
  snippet?: ArtifactContent;
  message?: Message5;
  /**
   * Specifies the source language, if any, of the portion of the artifact specified by the region object.
   */
  sourceLanguage?: string;
  /**
   * Key/value pairs that provide additional information about the region.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * The content to insert at the location specified by the 'deletedRegion' property.
 */
export interface ArtifactContent2 {
  /**
   * UTF-8-encoded content from a text artifact.
   */
  text?: string;
  /**
   * MIME Base64-encoded content from a binary artifact, or from a text artifact in its original encoding.
   */
  binary?: string;
  /**
   * Key/value pairs that provide additional information about the artifact content.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Automation details that describe this run.
 */
export interface RunAutomationDetails {
  description?: Message20;
  /**
   * A hierarchical string that uniquely identifies this object's containing run object.
   */
  instanceId?: string;
  /**
   * A stable, unique identifier for this object's containing run object in the form of a GUID.
   */
  instanceGuid?: string;
  /**
   * A stable, unique identifier for the equivalence class of runs to which this object's containing run object belongs in the form of a GUID.
   */
  correlationGuid?: string;
  /**
   * Key/value pairs that provide additional information about the run automation details.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * A description of the identity and role played within the engineering system by this object's containing run object.
 */
export interface Message20 {
  /**
   * A plain text message string.
   */
  text?: string;
  /**
   * A Markdown message string.
   */
  markdown?: string;
  /**
   * The resource id for a plain text or Markdown message string.
   */
  messageId?: string;
  /**
   * An array of strings to substitute into the message string.
   *
   * @minItems 0
   */
  arguments?: string[];
  /**
   * Key/value pairs that provide additional information about the message.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * Information that describes a run's identity and role within an engineering system process.
 */
export interface RunAutomationDetails1 {
  description?: Message20;
  /**
   * A hierarchical string that uniquely identifies this object's containing run object.
   */
  instanceId?: string;
  /**
   * A stable, unique identifier for this object's containing run object in the form of a GUID.
   */
  instanceGuid?: string;
  /**
   * A stable, unique identifier for the equivalence class of runs to which this object's containing run object belongs in the form of a GUID.
   */
  correlationGuid?: string;
  /**
   * Key/value pairs that provide additional information about the run automation details.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * References to external property files that should be inlined with the content of a root log file.
 */
export interface ExternalPropertyFiles {
  conversion?: ExternalPropertyFile;
  graphs?: ExternalPropertyFile1;
  externalizedProperties?: ExternalPropertyFile2;
  /**
   * An array of external property files containing run.artifacts arrays to be merged with the root log file.
   *
   * @minItems 1
   */
  artifacts?: [ExternalPropertyFile3, ...ExternalPropertyFile3[]];
  /**
   * An array of external property files containing run.invocations arrays to be merged with the root log file.
   *
   * @minItems 1
   */
  invocations?: [ExternalPropertyFile3, ...ExternalPropertyFile3[]];
  /**
   * An array of external property files containing run.logicalLocations arrays to be merged with the root log file.
   *
   * @minItems 1
   */
  logicalLocations?: [ExternalPropertyFile3, ...ExternalPropertyFile3[]];
  /**
   * An array of external property files containing run.results arrays to be merged with the root log file.
   *
   * @minItems 1
   */
  results?: [ExternalPropertyFile3, ...ExternalPropertyFile3[]];
  tool?: ExternalPropertyFile4;
}
/**
 * An external property file containing a run.conversion object to be merged with the root log file.
 */
export interface ExternalPropertyFile {
  artifactLocation?: ArtifactLocation13;
  /**
   * A stable, unique identifier for the external property file in the form of a GUID.
   */
  instanceGuid?: string;
  /**
   * A non-negative integer specifying the number of items contained in the external property file.
   */
  itemCount?: number;
  /**
   * Key/value pairs that provide additional information about the external property file.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Specifies the location of an artifact.
 */
export interface ArtifactLocation13 {
  /**
   * A string containing a valid relative or absolute URI.
   */
  uri: string;
  /**
   * A string which indirectly specifies the absolute URI with respect to which a relative URI in the "uri" property is interpreted.
   */
  uriBaseId?: string;
  /**
   * The index within the run artifacts array of the artifact object associated with the artifact location.
   */
  index?: number;
  /**
   * Key/value pairs that provide additional information about the artifact location.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * An external property file containing a run.graphs object to be merged with the root log file.
 */
export interface ExternalPropertyFile1 {
  artifactLocation?: ArtifactLocation13;
  /**
   * A stable, unique identifier for the external property file in the form of a GUID.
   */
  instanceGuid?: string;
  /**
   * A non-negative integer specifying the number of items contained in the external property file.
   */
  itemCount?: number;
  /**
   * Key/value pairs that provide additional information about the external property file.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * An external property file containing a run.properties object to be merged with the root log file.
 */
export interface ExternalPropertyFile2 {
  artifactLocation?: ArtifactLocation13;
  /**
   * A stable, unique identifier for the external property file in the form of a GUID.
   */
  instanceGuid?: string;
  /**
   * A non-negative integer specifying the number of items contained in the external property file.
   */
  itemCount?: number;
  /**
   * Key/value pairs that provide additional information about the external property file.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ExternalPropertyFile3 {
  artifactLocation?: ArtifactLocation13;
  /**
   * A stable, unique identifier for the external property file in the form of a GUID.
   */
  instanceGuid?: string;
  /**
   * A non-negative integer specifying the number of items contained in the external property file.
   */
  itemCount?: number;
  /**
   * Key/value pairs that provide additional information about the external property file.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * An external property file containing a run.tool object to be merged with the root log file.
 */
export interface ExternalPropertyFile4 {
  artifactLocation?: ArtifactLocation13;
  /**
   * A stable, unique identifier for the external property file in the form of a GUID.
   */
  instanceGuid?: string;
  /**
   * A non-negative integer specifying the number of items contained in the external property file.
   */
  itemCount?: number;
  /**
   * Key/value pairs that provide additional information about the external property file.
   */
  properties?: {
    /**
     * A set of distinct strings that provide additional information.
     *
     * @minItems 0
     */
    tags?: string[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
