/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A semantic(?) version
 */
export type Version =
  | string
  | {
      /**
       * Change major version when you make incompatible API changes
       */
      MAJOR: number;
      /**
       * Change minor version when you add functionality in a backwards-compatible manner
       */
      MINOR?: number;
      /**
       * Change patch version when you make backwards-compatible bug fixes
       */
      PATCH?: number;
      /**
       * Build informaion
       */
      BUILD?: number;
      [k: string]: unknown;
    };

/**
 * A KSP-AVC version file's content
 */
export interface AddOnVersionCheckerFile {
  /**
   * The display name for the add-on
   */
  NAME: string;
  /**
   * Location of a remote version file for update checking
   */
  URL?: string;
  /**
   * Web address where the latest version can be downloaded
   */
  DOWNLOAD?: string;
  /**
   * The complete or incremental change log for the add-on
   */
  CHANGE_LOG?: string;
  /**
   * Populates the CHANGE_LOG field using the file at this url
   */
  CHANGE_LOG_URL?: string;
  /**
   * Allows KSP-AVC to do release checks with GitHub including setting a download location if one is not specified. If the latest release version is not equal to the version in the file, an update notification will not appear.
   */
  GITHUB?: {
    /**
     * Your GitHub username
     */
    "USERNAME "?: string;
    /**
     * The name of the source repository
     */
    "REPOSITORY "?: string;
    /**
     * Include pre-releases in the latest release search
     */
    "ALLOW_PRE_RELEASE "?: boolean;
    [k: string]: unknown;
  };
  /**
   * URL to this mod's page on KerbalStuff
   */
  KERBAL_STUFF_URL?: string;
  /**
   * The version of the add-on
   */
  VERSION:
    | string
    | {
        /**
         * Change major version when you make incompatible API changes
         */
        MAJOR: number;
        /**
         * Change minor version when you add functionality in a backwards-compatible manner
         */
        MINOR?: number;
        /**
         * Change patch version when you make backwards-compatible bug fixes
         */
        PATCH?: number;
        /**
         * Build informaion
         */
        BUILD?: number;
        [k: string]: unknown;
      };
  /**
   * Version of KSP that the add-on was made to support
   */
  KSP_VERSION?:
    | string
    | {
        /**
         * Change major version when you make incompatible API changes
         */
        MAJOR: number;
        /**
         * Change minor version when you add functionality in a backwards-compatible manner
         */
        MINOR?: number;
        /**
         * Change patch version when you make backwards-compatible bug fixes
         */
        PATCH?: number;
        /**
         * Build informaion
         */
        BUILD?: number;
        [k: string]: unknown;
      };
  /**
   * Minimum version of KSP that the add-on supports
   */
  KSP_VERSION_MIN?:
    | string
    | {
        /**
         * Change major version when you make incompatible API changes
         */
        MAJOR: number;
        /**
         * Change minor version when you add functionality in a backwards-compatible manner
         */
        MINOR?: number;
        /**
         * Change patch version when you make backwards-compatible bug fixes
         */
        PATCH?: number;
        /**
         * Build informaion
         */
        BUILD?: number;
        [k: string]: unknown;
      };
  /**
   * Maximum version of KSP that the add-on supports
   */
  KSP_VERSION_MAX?:
    | string
    | {
        /**
         * Change major version when you make incompatible API changes
         */
        MAJOR: number;
        /**
         * Change minor version when you add functionality in a backwards-compatible manner
         */
        MINOR?: number;
        /**
         * Change patch version when you make backwards-compatible bug fixes
         */
        PATCH?: number;
        /**
         * Build informaion
         */
        BUILD?: number;
        [k: string]: unknown;
      };
  /**
   * If true, don't trust KSP-AVC's idea of which game versions are compatible with which other game versions, based on user configuration
   */
  DISALLOW_VERSION_OVERRIDE?: boolean;
  /**
   * DO NOT USE, won't work with CKAN; name of a DLL to check for VERSION on the fly
   */
  ASSEMBLY_NAME?: string;
  /**
   * DO NOT USE, won't work with CKAN; a list of versions with which this mod is compatible
   */
  KSP_VERSION_INCLUDE?: Version[];
  /**
   * DO NOT USE, won't work with CKAN; a list of versions with which this mod is incompatible
   */
  KSP_VERSION_EXCLUDE?: Version[];
  /**
   * DO NOT USE, won't work with CKAN; if true, don't override properties using the remote version file
   */
  LOCAL_HAS_PRIORITY?: boolean;
  /**
   * DO NOT USE, won't work with CKAN; if false, don't override properties using the remote version file
   */
  REMOTE_HAS_PRIORITY?: boolean;
  /**
   * Stanza to define file location to check, used by MADLAD
   */
  "INSTALL_LOC|INSTALL_LOC*"?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
