/* eslint-disable */

export interface HttpsJsonSchemastoreOrgSqlc20Json {
  version: '2';
  project?: {
    id?: string;
    [k: string]: unknown | undefined;
  };
  cloud?: {
    organization?: string;
    project?: string;
    hostname?: string;
    [k: string]: unknown | undefined;
  };
  /**
   * @minItems 1
   */
  sql?: [
    {
      /**
       * One of postgresql, mysql or sqlite.
       */
      engine: 'postgresql' | 'mysql' | 'sqlite';
      /**
       * A collection of rule names to run via sqlc vet. See rules for configuration options.
       */
      rules?: string[];
      /**
       * A collection of mappings to configure code generators. See codegen for the supported keys.
       */
      codegen?: {
        /**
         * Output directory for generated code.
         */
        out?: string;
        /**
         * The name of the plugin. Must be defined in the plugins collection.
         */
        plugin?: string;
        /**
         * A mapping of plugin-specific options.
         */
        options?: {
          [k: string]: unknown | undefined;
        };
        [k: string]: unknown | undefined;
      }[];
      /**
       * Directory of SQL migrations or path to single SQL file; or a list of paths.
       */
      schema?: string | string[];
      /**
       * Directory of SQL queries or path to single SQL file; or a list of paths.
       */
      queries?: string | string[];
      /**
       * A mapping to configure database connections. See database for the supported keys.
       *
       *
       */
      database?: {
        /**
         * Database connection URI
         */
        uri?: string;
        [k: string]: unknown | undefined;
      };
      /**
       * If true, return an error if a called SQL function does not exist. Defaults to false.
       */
      strict_function_checks?: boolean;
      strict_order_by?: boolean;
      /**
       * A mapping to configure built-in code generators. See gen for the supported keys.
       */
      gen?: {
        json?: {
          /**
           * Output directory for the generated JSON.
           */
          out?: string;
          /**
           * Indent string to use in the JSON document. Defaults to two spaces.
           */
          indent?: string;
          /**
           * Filename for the generated JSON document. Defaults to codegen_request.json.
           */
          filename?: string;
          [k: string]: unknown | undefined;
        };
        go?: {
          /**
           * If true, output a Querier interface in the generated package. Defaults to false.
           */
          emit_interface?: boolean;
          /**
           * If true, add JSON tags to generated structs. Defaults to false.
           */
          emit_json_tags?: boolean;
          /**
           * If true, “Id” in json tags will be uppercase. If false, will be camelcase. Defaults to false
           */
          json_tags_id_uppercase?: boolean;
          /**
           * If true, add DB tags to generated structs. Defaults to false.
           */
          emit_db_tags?: boolean;
          /**
           * If true, include support for prepared queries. Defaults to false.
           */
          emit_prepared_queries?: boolean;
          /**
           * If true, struct names will mirror table names. Otherwise, sqlc attempts to singularize plural table names. Defaults to false.
           */
          emit_exact_table_names?: boolean;
          /**
           * If true, slices returned by :many queries will be empty instead of nil. Defaults to false.
           */
          emit_empty_slices?: boolean;
          /**
           * If true, autogenerated SQL statement can be exported to be accessed by another package.
           */
          emit_exported_queries?: boolean;
          /**
           * If true, query results are returned as pointers to structs. Queries returning multiple results are returned as slices of pointers. Defaults to false.
           */
          emit_result_struct_pointers?: boolean;
          /**
           * If true, parameters are passed as pointers to structs. Defaults to false.
           */
          emit_params_struct_pointers?: boolean;
          /**
           * If true, generated methods will accept a DBTX argument instead of storing a DBTX on the *Queries struct. Defaults to false.
           */
          emit_methods_with_db_argument?: boolean;
          emit_pointers_for_null_types?: boolean;
          /**
           * If true, generate a Valid method on enum types, indicating whether a string is a valid enum value.
           */
          emit_enum_valid_method?: boolean;
          /**
           * If true, emit a function per enum type that returns all valid enum values.
           */
          emit_all_enum_values?: boolean;
          /**
           * camel for camelCase, pascal for PascalCase, snake for snake_case or none to use the column name in the DB. Defaults to none.
           */
          json_tags_case_style?: string;
          /**
           * The package name to use for the generated code. Defaults to out basename.
           */
          package?: string;
          /**
           * Output directory for generated code.
           */
          out?: string;
          /**
           * https://docs.sqlc.dev/en/stable/reference/config.html#type-overriding
           */
          overrides?: {
            /**
             * A fully qualified name to a Go type to use in the generated code.
             */
            go_type?:
              | {
                  /**
                   * The import path for the package where the type is defined.
                   */
                  import?: string;
                  /**
                   * The package name where the type is defined. This should only be necessary when your import path doesn’t end with the desired package name.
                   */
                  package?: string;
                  /**
                   * The type name itself, without any package prefix.
                   */
                  type?: string;
                  /**
                   * If set to true, generated code will use pointers to the type rather than the type itself.
                   */
                  pointer?: boolean;
                  /**
                   * If set to true, generated code will use a slice of the type rather than the type itself.
                   */
                  slice?: boolean;
                  spec?: string;
                  builtin?: boolean;
                  [k: string]: unknown | undefined;
                }
              | string;
            /**
             * A reflect-style struct tag to use in the generated code, e.g. a:"b" x:"y,z". If you want general json/db tags for all fields, use emit_db_tags and/or emit_json_tags instead.
             */
            go_struct_tag?: string;
            /**
             * The PostgreSQL or MySQL type to override. Find the full list of supported types in postgresql_type.go or mysql_type.go. Note that for Postgres you must use the pg_catalog prefixed names where available. Can’t be used if the column key is defined.
             */
            db_type?: string;
            engine?: 'postgresql' | 'mysql' | 'sqlite';
            /**
             * If true, use this type when a column is nullable. Defaults to false.
             */
            nullable?: boolean;
            unsigned?: boolean;
            /**
             * In case the type overriding should be done on specific a column of a table instead of a type. column should be of the form table.column but you can be even more specific by specifying schema.table.column or catalog.schema.table.column. Can’t be used if the db_type key is defined.
             */
            column?: string;
            [k: string]: unknown | undefined;
          }[];
          /**
           * https://docs.sqlc.dev/en/stable/reference/config.html#renaming-fields
           */
          rename?: {
            /**
             * This interface was referenced by `undefined`'s JSON-Schema definition
             * via the `patternProperty` ".*".
             */
            [k: string]: string;
          };
          /**
           * Either pgx/v4, pgx/v5 or database/sql. Defaults to database/sql.
           */
          sql_package?: string;
          sql_driver?: string;
          /**
           * Customize the name of the batch file. Defaults to batch.go.
           */
          output_batch_file_name?: string;
          /**
           * Customize the name of the db file. Defaults to db.go.
           */
          output_db_file_name?: string;
          /**
           * Customize the name of the models file. Defaults to models.go.
           */
          output_models_file_name?: string;
          /**
           * Customize the name of the querier file. Defaults to querier.go.
           */
          output_querier_file_name?: string;
          /**
           * If specified the suffix will be added to the name of the generated files.
           */
          output_files_suffix?: string;
          inflection_exclude_table_names?: string[];
          /**
           * The number of positional arguments that will be generated for Go functions. To always emit a parameter struct, set this to 0. Defaults to 1.
           */
          query_parameter_limit?: number;
          /**
           * If true, sqlc won’t generate table and enum structs that aren’t used in queries for a given package. Defaults to false.
           */
          omit_unused_structs?: boolean;
          [k: string]: unknown | undefined;
        };
        [k: string]: unknown | undefined;
      };
      [k: string]: unknown | undefined;
    },
    ...{
      /**
       * One of postgresql, mysql or sqlite.
       */
      engine: 'postgresql' | 'mysql' | 'sqlite';
      /**
       * A collection of rule names to run via sqlc vet. See rules for configuration options.
       */
      rules?: string[];
      /**
       * A collection of mappings to configure code generators. See codegen for the supported keys.
       */
      codegen?: {
        /**
         * Output directory for generated code.
         */
        out?: string;
        /**
         * The name of the plugin. Must be defined in the plugins collection.
         */
        plugin?: string;
        /**
         * A mapping of plugin-specific options.
         */
        options?: {
          [k: string]: unknown | undefined;
        };
        [k: string]: unknown | undefined;
      }[];
      /**
       * Directory of SQL migrations or path to single SQL file; or a list of paths.
       */
      schema?: string | string[];
      /**
       * Directory of SQL queries or path to single SQL file; or a list of paths.
       */
      queries?: string | string[];
      /**
       * A mapping to configure database connections. See database for the supported keys.
       *
       *
       */
      database?: {
        /**
         * Database connection URI
         */
        uri?: string;
        [k: string]: unknown | undefined;
      };
      /**
       * If true, return an error if a called SQL function does not exist. Defaults to false.
       */
      strict_function_checks?: boolean;
      strict_order_by?: boolean;
      /**
       * A mapping to configure built-in code generators. See gen for the supported keys.
       */
      gen?: {
        json?: {
          /**
           * Output directory for the generated JSON.
           */
          out?: string;
          /**
           * Indent string to use in the JSON document. Defaults to two spaces.
           */
          indent?: string;
          /**
           * Filename for the generated JSON document. Defaults to codegen_request.json.
           */
          filename?: string;
          [k: string]: unknown | undefined;
        };
        go?: {
          /**
           * If true, output a Querier interface in the generated package. Defaults to false.
           */
          emit_interface?: boolean;
          /**
           * If true, add JSON tags to generated structs. Defaults to false.
           */
          emit_json_tags?: boolean;
          /**
           * If true, “Id” in json tags will be uppercase. If false, will be camelcase. Defaults to false
           */
          json_tags_id_uppercase?: boolean;
          /**
           * If true, add DB tags to generated structs. Defaults to false.
           */
          emit_db_tags?: boolean;
          /**
           * If true, include support for prepared queries. Defaults to false.
           */
          emit_prepared_queries?: boolean;
          /**
           * If true, struct names will mirror table names. Otherwise, sqlc attempts to singularize plural table names. Defaults to false.
           */
          emit_exact_table_names?: boolean;
          /**
           * If true, slices returned by :many queries will be empty instead of nil. Defaults to false.
           */
          emit_empty_slices?: boolean;
          /**
           * If true, autogenerated SQL statement can be exported to be accessed by another package.
           */
          emit_exported_queries?: boolean;
          /**
           * If true, query results are returned as pointers to structs. Queries returning multiple results are returned as slices of pointers. Defaults to false.
           */
          emit_result_struct_pointers?: boolean;
          /**
           * If true, parameters are passed as pointers to structs. Defaults to false.
           */
          emit_params_struct_pointers?: boolean;
          /**
           * If true, generated methods will accept a DBTX argument instead of storing a DBTX on the *Queries struct. Defaults to false.
           */
          emit_methods_with_db_argument?: boolean;
          emit_pointers_for_null_types?: boolean;
          /**
           * If true, generate a Valid method on enum types, indicating whether a string is a valid enum value.
           */
          emit_enum_valid_method?: boolean;
          /**
           * If true, emit a function per enum type that returns all valid enum values.
           */
          emit_all_enum_values?: boolean;
          /**
           * camel for camelCase, pascal for PascalCase, snake for snake_case or none to use the column name in the DB. Defaults to none.
           */
          json_tags_case_style?: string;
          /**
           * The package name to use for the generated code. Defaults to out basename.
           */
          package?: string;
          /**
           * Output directory for generated code.
           */
          out?: string;
          /**
           * https://docs.sqlc.dev/en/stable/reference/config.html#type-overriding
           */
          overrides?: {
            /**
             * A fully qualified name to a Go type to use in the generated code.
             */
            go_type?:
              | {
                  /**
                   * The import path for the package where the type is defined.
                   */
                  import?: string;
                  /**
                   * The package name where the type is defined. This should only be necessary when your import path doesn’t end with the desired package name.
                   */
                  package?: string;
                  /**
                   * The type name itself, without any package prefix.
                   */
                  type?: string;
                  /**
                   * If set to true, generated code will use pointers to the type rather than the type itself.
                   */
                  pointer?: boolean;
                  /**
                   * If set to true, generated code will use a slice of the type rather than the type itself.
                   */
                  slice?: boolean;
                  spec?: string;
                  builtin?: boolean;
                  [k: string]: unknown | undefined;
                }
              | string;
            /**
             * A reflect-style struct tag to use in the generated code, e.g. a:"b" x:"y,z". If you want general json/db tags for all fields, use emit_db_tags and/or emit_json_tags instead.
             */
            go_struct_tag?: string;
            /**
             * The PostgreSQL or MySQL type to override. Find the full list of supported types in postgresql_type.go or mysql_type.go. Note that for Postgres you must use the pg_catalog prefixed names where available. Can’t be used if the column key is defined.
             */
            db_type?: string;
            engine?: 'postgresql' | 'mysql' | 'sqlite';
            /**
             * If true, use this type when a column is nullable. Defaults to false.
             */
            nullable?: boolean;
            unsigned?: boolean;
            /**
             * In case the type overriding should be done on specific a column of a table instead of a type. column should be of the form table.column but you can be even more specific by specifying schema.table.column or catalog.schema.table.column. Can’t be used if the db_type key is defined.
             */
            column?: string;
            [k: string]: unknown | undefined;
          }[];
          /**
           * https://docs.sqlc.dev/en/stable/reference/config.html#renaming-fields
           */
          rename?: {
            /**
             * This interface was referenced by `undefined`'s JSON-Schema definition
             * via the `patternProperty` ".*".
             */
            [k: string]: string;
          };
          /**
           * Either pgx/v4, pgx/v5 or database/sql. Defaults to database/sql.
           */
          sql_package?: string;
          sql_driver?: string;
          /**
           * Customize the name of the batch file. Defaults to batch.go.
           */
          output_batch_file_name?: string;
          /**
           * Customize the name of the db file. Defaults to db.go.
           */
          output_db_file_name?: string;
          /**
           * Customize the name of the models file. Defaults to models.go.
           */
          output_models_file_name?: string;
          /**
           * Customize the name of the querier file. Defaults to querier.go.
           */
          output_querier_file_name?: string;
          /**
           * If specified the suffix will be added to the name of the generated files.
           */
          output_files_suffix?: string;
          inflection_exclude_table_names?: string[];
          /**
           * The number of positional arguments that will be generated for Go functions. To always emit a parameter struct, set this to 0. Defaults to 1.
           */
          query_parameter_limit?: number;
          /**
           * If true, sqlc won’t generate table and enum structs that aren’t used in queries for a given package. Defaults to false.
           */
          omit_unused_structs?: boolean;
          [k: string]: unknown | undefined;
        };
        [k: string]: unknown | undefined;
      };
      [k: string]: unknown | undefined;
    }[]
  ];
  /**
   * https://docs.sqlc.dev/en/latest/reference/config.html#global-overrides
   */
  overrides?: {
    go?: {
      overrides?: {
        go_type?:
          | {
              import?: string;
              package?: string;
              type?: string;
              pointer?: boolean;
              slice?: boolean;
              spec?: string;
              builtin?: boolean;
              [k: string]: unknown | undefined;
            }
          | string;
        go_struct_tag?: string;
        db_type?: string;
        engine?: 'postgresql' | 'mysql' | 'sqlite';
        nullable?: boolean;
        unsigned?: boolean;
        column?: string;
        [k: string]: unknown | undefined;
      }[];
      rename?: {
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` ".*".
         */
        [k: string]: string;
      };
      [k: string]: unknown | undefined;
    };
    [k: string]: unknown | undefined;
  };
  plugins?: {
    /**
     * The name of this plugin.
     */
    name: string;
    env?: string[];
    process?: {
      /**
       * The executable to call when using this plugin
       */
      cmd?: string;
      [k: string]: unknown | undefined;
    };
    /**
     * wasm: A mapping with a two keys url and sha256
     */
    wasm?: {
      /**
       * The URL to fetch the WASM file. Supports the https:// or file:// schemes.
       */
      url?: string;
      /**
       * The SHA256 checksum for the downloaded file.
       */
      sha256?: string;
      [k: string]: unknown | undefined;
    };
    [k: string]: unknown | undefined;
  }[];
  rules?: {
    /**
     * The name of this rule. (Required)
     */
    name?: string;
    /**
     * A Common Expression Language (CEL) expression. Required.
     */
    rule?: string;
    /**
     * An optional message shown when this rule evaluates to true.
     */
    message?: string;
    [k: string]: unknown | undefined;
  }[];
  [k: string]: unknown | undefined;
}
