/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface JSONSchemaForVisualStudioExtensionPackManifests {
  /**
   * A unique identifier for the extension pack. This is to uniquely identify the extension pack and will not be shown to the user.
   */
  id?: string;
  /**
   * The name of the extension pack.
   */
  name?: string;
  /**
   * A short description of the extension pack.
   */
  description?: string;
  /**
   * The version of the extension pack.
   */
  version: string;
  /**
   * A list of extension objects.
   */
  extensions?: {
    /**
     * The name of the extension.
     */
    name?: string;
    /**
     * The unique ID of the extension.
     */
    vsixId: string;
    [k: string]: any;
  }[];
  [k: string]: any;
}
