/* eslint-disable */

export interface HttpsJsonSchemastoreOrgDetekt1220Json {
  build?: {
    maxIssues?: number;
    excludeCorrectable?: boolean;
    weights?: {
      [k: string]: number | undefined;
    };
    [k: string]: unknown | undefined;
  };
  config?: {
    validation?: boolean;
    warningsAsErrors?: boolean;
    checkExhaustiveness?: boolean;
    excludes?: string;
    [k: string]: unknown | undefined;
  };
  processors?: {
    active?: boolean;
    exclude?: string[];
    [k: string]: unknown | undefined;
  };
  'console-reports'?: {
    active?: boolean;
    exclude?: string[];
    [k: string]: unknown | undefined;
  };
  'output-reports'?: {
    active?: boolean;
    exclude?: string[];
    [k: string]: unknown | undefined;
  };
  comments?: {
    active?: boolean;
    AbsentOrWrongFileLicense?: RuleProperties;
    CommentOverPrivateFunction?: RuleProperties;
    CommentOverPrivateProperty?: RuleProperties;
    DeprecatedBlockTag?: RuleProperties;
    EndOfSentenceFormat?: RuleProperties;
    KDocReferencesNonPublicProperty?: RuleProperties;
    OutdatedDocumentation?: RuleProperties;
    UndocumentedPublicClass?: RuleProperties;
    UndocumentedPublicFunction?: RuleProperties;
    UndocumentedPublicProperty?: RuleProperties;
    [k: string]: unknown | undefined;
  };
  complexity?: {
    active?: boolean;
    CognitiveComplexMethod?: RuleProperties;
    ComplexCondition?: RuleProperties;
    ComplexInterface?: RuleProperties;
    CyclomaticComplexMethod?: RuleProperties;
    LabeledExpression?: RuleProperties;
    LargeClass?: RuleProperties;
    LongMethod?: RuleProperties;
    LongParameterList?: RuleProperties;
    MethodOverloading?: RuleProperties;
    NamedArguments?: RuleProperties;
    NestedBlockDepth?: RuleProperties;
    NestedScopeFunctions?: RuleProperties;
    ReplaceSafeCallChainWithRun?: RuleProperties;
    StringLiteralDuplication?: RuleProperties;
    TooManyFunctions?: RuleProperties;
    [k: string]: unknown | undefined;
  };
  coroutines?: {
    active?: boolean;
    GlobalCoroutineUsage?: RuleProperties;
    InjectDispatcher?: RuleProperties;
    RedundantSuspendModifier?: RuleProperties;
    SleepInsteadOfDelay?: RuleProperties;
    SuspendFunWithCoroutineScopeReceiver?: RuleProperties;
    SuspendFunWithFlowReturnType?: RuleProperties;
    [k: string]: unknown | undefined;
  };
  'empty-blocks'?: {
    active?: boolean;
    EmptyCatchBlock?: RuleProperties;
    EmptyClassBlock?: RuleProperties;
    EmptyDefaultConstructor?: RuleProperties;
    EmptyDoWhileBlock?: RuleProperties;
    EmptyElseBlock?: RuleProperties;
    EmptyFinallyBlock?: RuleProperties;
    EmptyForBlock?: RuleProperties;
    EmptyFunctionBlock?: RuleProperties;
    EmptyIfBlock?: RuleProperties;
    EmptyInitBlock?: RuleProperties;
    EmptyKtFile?: RuleProperties;
    EmptySecondaryConstructor?: RuleProperties;
    EmptyTryBlock?: RuleProperties;
    EmptyWhenBlock?: RuleProperties;
    EmptyWhileBlock?: RuleProperties;
    [k: string]: unknown | undefined;
  };
  exceptions?: {
    active?: boolean;
    ExceptionRaisedInUnexpectedLocation?: RuleProperties;
    InstanceOfCheckForException?: RuleProperties;
    NotImplementedDeclaration?: RuleProperties;
    ObjectExtendsThrowable?: RuleProperties;
    PrintStackTrace?: RuleProperties;
    RethrowCaughtException?: RuleProperties;
    ReturnFromFinally?: RuleProperties;
    SwallowedException?: RuleProperties;
    ThrowingExceptionFromFinally?: RuleProperties;
    ThrowingExceptionInMain?: RuleProperties;
    ThrowingExceptionsWithoutMessageOrCause?: RuleProperties;
    ThrowingNewInstanceOfSameException?: RuleProperties;
    TooGenericExceptionCaught?: RuleProperties;
    TooGenericExceptionThrown?: RuleProperties;
    [k: string]: unknown | undefined;
  };
  naming?: {
    active?: boolean;
    BooleanPropertyNaming?: RuleProperties;
    ClassNaming?: RuleProperties;
    ConstructorParameterNaming?: RuleProperties;
    EnumNaming?: RuleProperties;
    ForbiddenClassName?: RuleProperties;
    FunctionMaxLength?: RuleProperties;
    FunctionMinLength?: RuleProperties;
    FunctionNaming?: RuleProperties;
    FunctionParameterNaming?: RuleProperties;
    InvalidPackageDeclaration?: RuleProperties;
    LambdaParameterNaming?: RuleProperties;
    MatchingDeclarationName?: RuleProperties;
    MemberNameEqualsClassName?: RuleProperties;
    NoNameShadowing?: RuleProperties;
    NonBooleanPropertyPrefixedWithIs?: RuleProperties;
    ObjectPropertyNaming?: RuleProperties;
    PackageNaming?: RuleProperties;
    TopLevelPropertyNaming?: RuleProperties;
    VariableMaxLength?: RuleProperties;
    VariableMinLength?: RuleProperties;
    VariableNaming?: RuleProperties;
    [k: string]: unknown | undefined;
  };
  performance?: {
    active?: boolean;
    ArrayPrimitive?: RuleProperties;
    CouldBeSequence?: RuleProperties;
    ForEachOnRange?: RuleProperties;
    SpreadOperator?: RuleProperties;
    UnnecessaryPartOfBinaryExpression?: RuleProperties;
    UnnecessaryTemporaryInstantiation?: RuleProperties;
    [k: string]: unknown | undefined;
  };
  'potential-bugs'?: {
    active?: boolean;
    AvoidReferentialEquality?: RuleProperties;
    CastToNullableType?: RuleProperties;
    Deprecation?: RuleProperties;
    DontDowncastCollectionTypes?: RuleProperties;
    DoubleMutabilityForCollection?: RuleProperties;
    ElseCaseInsteadOfExhaustiveWhen?: RuleProperties;
    EqualsAlwaysReturnsTrueOrFalse?: RuleProperties;
    EqualsWithHashCodeExist?: RuleProperties;
    ExitOutsideMain?: RuleProperties;
    ExplicitGarbageCollectionCall?: RuleProperties;
    HasPlatformType?: RuleProperties;
    IgnoredReturnValue?: RuleProperties;
    ImplicitDefaultLocale?: RuleProperties;
    ImplicitUnitReturnType?: RuleProperties;
    InvalidRange?: RuleProperties;
    IteratorHasNextCallsNextMethod?: RuleProperties;
    IteratorNotThrowingNoSuchElementException?: RuleProperties;
    LateinitUsage?: RuleProperties;
    MapGetWithNotNullAssertionOperator?: RuleProperties;
    MissingPackageDeclaration?: RuleProperties;
    NullCheckOnMutableProperty?: RuleProperties;
    NullableToStringCall?: RuleProperties;
    UnconditionalJumpStatementInLoop?: RuleProperties;
    UnnecessaryNotNullCheck?: RuleProperties;
    UnnecessaryNotNullOperator?: RuleProperties;
    UnnecessarySafeCall?: RuleProperties;
    UnreachableCatchBlock?: RuleProperties;
    UnreachableCode?: RuleProperties;
    UnsafeCallOnNullableType?: RuleProperties;
    UnsafeCast?: RuleProperties;
    UnusedUnaryOperator?: RuleProperties;
    UselessPostfixExpression?: RuleProperties;
    WrongEqualsTypeParameter?: RuleProperties;
    [k: string]: unknown | undefined;
  };
  style?: {
    active?: boolean;
    AlsoCouldBeApply?: RuleProperties;
    CanBeNonNullable?: RuleProperties;
    CascadingCallWrapping?: RuleProperties;
    ClassOrdering?: RuleProperties;
    CollapsibleIfStatements?: RuleProperties;
    DataClassContainsFunctions?: RuleProperties;
    DataClassShouldBeImmutable?: RuleProperties;
    DestructuringDeclarationWithTooManyEntries?: RuleProperties;
    EqualsNullCall?: RuleProperties;
    EqualsOnSignatureLine?: RuleProperties;
    ExplicitCollectionElementAccessMethod?: RuleProperties;
    ExplicitItLambdaParameter?: RuleProperties;
    ExpressionBodySyntax?: RuleProperties;
    ForbiddenComment?: RuleProperties;
    ForbiddenImport?: RuleProperties;
    ForbiddenMethodCall?: RuleProperties;
    ForbiddenSuppress?: RuleProperties;
    ForbiddenVoid?: RuleProperties;
    FunctionOnlyReturningConstant?: RuleProperties;
    LoopWithTooManyJumpStatements?: RuleProperties;
    MagicNumber?: RuleProperties;
    MandatoryBracesIfStatements?: RuleProperties;
    MandatoryBracesLoops?: RuleProperties;
    MaxChainedCallsOnSameLine?: RuleProperties;
    MaxLineLength?: RuleProperties;
    MayBeConst?: RuleProperties;
    ModifierOrder?: RuleProperties;
    MultilineLambdaItParameter?: RuleProperties;
    MultilineRawStringIndentation?: RuleProperties;
    NestedClassesVisibility?: RuleProperties;
    NewLineAtEndOfFile?: RuleProperties;
    NoTabs?: RuleProperties;
    NullableBooleanCheck?: RuleProperties;
    ObjectLiteralToLambda?: RuleProperties;
    OptionalAbstractKeyword?: RuleProperties;
    OptionalUnit?: RuleProperties;
    OptionalWhenBraces?: RuleProperties;
    PreferToOverPairSyntax?: RuleProperties;
    ProtectedMemberInFinalClass?: RuleProperties;
    RedundantExplicitType?: RuleProperties;
    RedundantHigherOrderMapUsage?: RuleProperties;
    RedundantVisibilityModifierRule?: RuleProperties;
    ReturnCount?: RuleProperties;
    SafeCast?: RuleProperties;
    SerialVersionUIDInSerializableClass?: RuleProperties;
    SpacingBetweenPackageAndImports?: RuleProperties;
    ThrowsCount?: RuleProperties;
    TrailingWhitespace?: RuleProperties;
    TrimMultilineRawString?: RuleProperties;
    UnderscoresInNumericLiterals?: RuleProperties;
    UnnecessaryAbstractClass?: RuleProperties;
    UnnecessaryAnnotationUseSiteTarget?: RuleProperties;
    UnnecessaryApply?: RuleProperties;
    UnnecessaryBackticks?: RuleProperties;
    UnnecessaryFilter?: RuleProperties;
    UnnecessaryInheritance?: RuleProperties;
    UnnecessaryInnerClass?: RuleProperties;
    UnnecessaryLet?: RuleProperties;
    UnnecessaryParentheses?: RuleProperties;
    UntilInsteadOfRangeTo?: RuleProperties;
    UnusedImports?: RuleProperties;
    UnusedPrivateClass?: RuleProperties;
    UnusedPrivateMember?: RuleProperties;
    UseAnyOrNoneInsteadOfFind?: RuleProperties;
    UseArrayLiteralsInAnnotations?: RuleProperties;
    UseCheckNotNull?: RuleProperties;
    UseCheckOrError?: RuleProperties;
    UseDataClass?: RuleProperties;
    UseEmptyCounterpart?: RuleProperties;
    UseIfEmptyOrIfBlank?: RuleProperties;
    UseIfInsteadOfWhen?: RuleProperties;
    UseIsNullOrEmpty?: RuleProperties;
    UseOrEmpty?: RuleProperties;
    UseRequire?: RuleProperties;
    UseRequireNotNull?: RuleProperties;
    UseSumOfInsteadOfFlatMapSize?: RuleProperties;
    UselessCallOnNotNull?: RuleProperties;
    UtilityClassWithPublicConstructor?: RuleProperties;
    VarCouldBeVal?: RuleProperties;
    WildcardImport?: RuleProperties;
    [k: string]: unknown | undefined;
  };
  formatting?: {
    active?: boolean;
    android?: boolean;
    autoCorrect?: boolean;
    AnnotationOnSeparateLine?: RuleProperties;
    AnnotationSpacing?: RuleProperties;
    ArgumentListWrapping?: RuleProperties;
    BlockCommentInitialStarAlignment?: RuleProperties;
    ChainWrapping?: RuleProperties;
    CommentSpacing?: RuleProperties;
    CommentWrapping?: RuleProperties;
    DiscouragedCommentLocation?: RuleProperties;
    EnumEntryNameCase?: RuleProperties;
    Filename?: RuleProperties;
    FinalNewline?: RuleProperties;
    FunKeywordSpacing?: RuleProperties;
    FunctionReturnTypeSpacing?: RuleProperties;
    FunctionSignature?: RuleProperties;
    FunctionStartOfBodySpacing?: RuleProperties;
    FunctionTypeReferenceSpacing?: RuleProperties;
    ImportOrdering?: RuleProperties;
    Indentation?: RuleProperties;
    KdocWrapping?: RuleProperties;
    MaximumLineLength?: RuleProperties;
    ModifierListSpacing?: RuleProperties;
    ModifierOrdering?: RuleProperties;
    MultiLineIfElse?: RuleProperties;
    NoBlankLineBeforeRbrace?: RuleProperties;
    NoBlankLinesInChainedMethodCalls?: RuleProperties;
    NoConsecutiveBlankLines?: RuleProperties;
    NoEmptyClassBody?: RuleProperties;
    NoEmptyFirstLineInMethodBlock?: RuleProperties;
    NoLineBreakAfterElse?: RuleProperties;
    NoLineBreakBeforeAssignment?: RuleProperties;
    NoMultipleSpaces?: RuleProperties;
    NoSemicolons?: RuleProperties;
    NoTrailingSpaces?: RuleProperties;
    NoUnitReturn?: RuleProperties;
    NoUnusedImports?: RuleProperties;
    NoWildcardImports?: RuleProperties;
    NullableTypeSpacing?: RuleProperties;
    PackageName?: RuleProperties;
    ParameterListSpacing?: RuleProperties;
    ParameterListWrapping?: RuleProperties;
    SpacingAroundAngleBrackets?: RuleProperties;
    SpacingAroundColon?: RuleProperties;
    SpacingAroundComma?: RuleProperties;
    SpacingAroundCurly?: RuleProperties;
    SpacingAroundDot?: RuleProperties;
    SpacingAroundDoubleColon?: RuleProperties;
    SpacingAroundKeyword?: RuleProperties;
    SpacingAroundOperators?: RuleProperties;
    SpacingAroundParens?: RuleProperties;
    SpacingAroundRangeOperator?: RuleProperties;
    SpacingAroundUnaryOperator?: RuleProperties;
    SpacingBetweenDeclarationsWithAnnotations?: RuleProperties;
    SpacingBetweenDeclarationsWithComments?: RuleProperties;
    SpacingBetweenFunctionNameAndOpeningParenthesis?: RuleProperties;
    StringTemplate?: RuleProperties;
    TrailingCommaOnCallSite?: RuleProperties;
    TrailingCommaOnDeclarationSite?: RuleProperties;
    TypeArgumentListSpacing?: RuleProperties;
    TypeParameterListSpacing?: RuleProperties;
    UnnecessaryParenthesesBeforeTrailingLambda?: RuleProperties;
    Wrapping?: RuleProperties;
    [k: string]: unknown | undefined;
  };
  libraries?: {
    active?: boolean;
    ForbiddenPublicDataClass?: RuleProperties;
    LibraryCodeMustSpecifyReturnType?: RuleProperties;
    LibraryEntitiesShouldNotBePublic?: RuleProperties;
    [k: string]: unknown | undefined;
  };
  ruleauthors?: {
    active?: boolean;
    UseEntityAtName?: RuleProperties;
    ViolatesTypeResolutionRequirements?: RuleProperties;
    [k: string]: unknown | undefined;
  };
  [k: string]: unknown | undefined;
}
export interface RuleProperties {
  active?: boolean;
  excludes?: string[];
  ignoreAnnotated?: string[];
  ignoreFunction?: string[];
  [k: string]: unknown | undefined;
}
