/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GithubAction {
  /**
   * The name of your action. GitHub displays the name in the Actions tab to help visually identify actions in each job.
   */
  name: string;
  /**
   * The name of the action's author.
   */
  author?: string;
  /**
   * A short description of the action.
   */
  description: string;
  /**
   * Input parameters allow you to specify data that the action expects to use during runtime. GitHub stores input parameters as environment variables. Input ids with uppercase letters are converted to lowercase during runtime. We recommended using lowercase input ids.
   */
  inputs?: {
    /**
     * A string identifier to associate with the input. The value of <input_id> is a map of the input's metadata. The <input_id> must be a unique identifier within the inputs object. The <input_id> must start with a letter or _ and contain only alphanumeric characters, -, or _.
     *
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[_a-zA-Z][a-zA-Z0-9_-]*$".
     */
    [k: string]: {
      /**
       * A string description of the input parameter.
       */
      description: string;
      /**
       * A string shown to users using the deprecated input.
       */
      deprecationMessage?: string;
      /**
       * A boolean to indicate whether the action requires the input parameter. Set to true when the parameter is required.
       */
      required: boolean;
      /**
       * A string representing the default value. The default value is used when an input parameter isn't specified in a workflow file.
       */
      default?: string;
    };
  };
  /**
   * Output parameters allow you to specify the data that subsequent actions can use later in the workflow after the action that defines these outputs has run. For example, if you had an action that performed the addition of two inputs (x + y = z), the action could output the sum (z) for other actions to use as an input. Output ids with uppercase letters are converted to lowercase during runtime. We recommended using lowercase output ids.
   */
  outputs?: {
    /**
     * A string identifier to associate with the output. The value of <output_id> is a map of the output's metadata. The <output_id> must be a unique identifier within the outputs object. The <output_id> must start with a letter or _ and contain only alphanumeric characters, -, or _.
     *
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[_a-zA-Z][a-zA-Z0-9_-]*$".
     */
    [k: string]: {
      /**
       * A string description of the output parameter.
       */
      description: string;
    };
  };
  /**
   * The command to run when the action executes.
   */
  runs:
    | {
        using?: {
          [k: string]: any;
        };
        image?: {
          [k: string]: any;
        };
        entrypoint?: {
          [k: string]: any;
        };
        args?: {
          [k: string]: any;
        };
        [k: string]: any;
      }
    | {
        using?: {
          [k: string]: any;
        };
        main?: {
          [k: string]: any;
        };
        [k: string]: any;
      };
  /**
   * You can use a color and Feather icon to create a badge to personalize and distinguish your action in GitHub Marketplace. For more information, see "GitHub Actions in the GitHub Marketplace" in the GitHub Developer documentation.
   */
  branding?: {
    /**
     * The background color of the badge.
     */
    color?: "white" | "yellow" | "blue" | "green" | "orange" | "red" | "purple" | "gray-dark";
    /**
     * The name of the Feather icon to use.
     */
    icon?:
      | "activity"
      | "airplay"
      | "alert-circle"
      | "alert-octagon"
      | "alert-triangle"
      | "align-center"
      | "align-justify"
      | "align-left"
      | "align-right"
      | "anchor"
      | "aperture"
      | "archive"
      | "arrow-down-circle"
      | "arrow-down-left"
      | "arrow-down-right"
      | "arrow-down"
      | "arrow-left-circle"
      | "arrow-left"
      | "arrow-right-circle"
      | "arrow-right"
      | "arrow-up-circle"
      | "arrow-up-left"
      | "arrow-up-right"
      | "arrow-up"
      | "at-sign"
      | "award"
      | "bar-chart-2"
      | "bar-chart"
      | "battery-charging"
      | "battery"
      | "bell-off"
      | "bell"
      | "bluetooth"
      | "bold"
      | "book-open"
      | "book"
      | "bookmark"
      | "box"
      | "briefcase"
      | "calendar"
      | "camera-off"
      | "camera"
      | "cast"
      | "check-circle"
      | "check-square"
      | "check"
      | "chevron-down"
      | "chevron-left"
      | "chevron-right"
      | "chevron-up"
      | "chevrons-down"
      | "chevrons-left"
      | "chevrons-right"
      | "chevrons-up"
      | "circle"
      | "clipboard"
      | "clock"
      | "cloud-drizzle"
      | "cloud-lightning"
      | "cloud-off"
      | "cloud-rain"
      | "cloud-snow"
      | "cloud"
      | "code"
      | "command"
      | "compass"
      | "copy"
      | "corner-down-left"
      | "corner-down-right"
      | "corner-left-down"
      | "corner-left-up"
      | "corner-right-down"
      | "corner-right-up"
      | "corner-up-left"
      | "corner-up-right"
      | "cpu"
      | "credit-card"
      | "crop"
      | "crosshair"
      | "database"
      | "delete"
      | "disc"
      | "dollar-sign"
      | "download-cloud"
      | "download"
      | "droplet"
      | "edit-2"
      | "edit-3"
      | "edit"
      | "external-link"
      | "eye-off"
      | "eye"
      | "facebook"
      | "fast-forward"
      | "feather"
      | "file-minus"
      | "file-plus"
      | "file-text"
      | "file"
      | "film"
      | "filter"
      | "flag"
      | "folder-minus"
      | "folder-plus"
      | "folder"
      | "gift"
      | "git-branch"
      | "git-commit"
      | "git-merge"
      | "git-pull-request"
      | "globe"
      | "grid"
      | "hard-drive"
      | "hash"
      | "headphones"
      | "heart"
      | "help-circle"
      | "home"
      | "image"
      | "inbox"
      | "info"
      | "italic"
      | "layers"
      | "layout"
      | "life-buoy"
      | "link-2"
      | "link"
      | "list"
      | "loader"
      | "lock"
      | "log-in"
      | "log-out"
      | "mail"
      | "map-pin"
      | "map"
      | "maximize-2"
      | "maximize"
      | "menu"
      | "message-circle"
      | "message-square"
      | "mic-off"
      | "mic"
      | "minimize-2"
      | "minimize"
      | "minus-circle"
      | "minus-square"
      | "minus"
      | "monitor"
      | "moon"
      | "more-horizontal"
      | "more-vertical"
      | "move"
      | "music"
      | "navigation-2"
      | "navigation"
      | "octagon"
      | "package"
      | "paperclip"
      | "pause-circle"
      | "pause"
      | "percent"
      | "phone-call"
      | "phone-forwarded"
      | "phone-incoming"
      | "phone-missed"
      | "phone-off"
      | "phone-outgoing"
      | "phone"
      | "pie-chart"
      | "play-circle"
      | "play"
      | "plus-circle"
      | "plus-square"
      | "plus"
      | "pocket"
      | "power"
      | "printer"
      | "radio"
      | "refresh-ccw"
      | "refresh-cw"
      | "repeat"
      | "rewind"
      | "rotate-ccw"
      | "rotate-cw"
      | "rss"
      | "save"
      | "scissors"
      | "search"
      | "send"
      | "server"
      | "settings"
      | "share-2"
      | "share"
      | "shield-off"
      | "shield"
      | "shopping-bag"
      | "shopping-cart"
      | "shuffle"
      | "sidebar"
      | "skip-back"
      | "skip-forward"
      | "slash"
      | "sliders"
      | "smartphone"
      | "speaker"
      | "square"
      | "star"
      | "stop-circle"
      | "sun"
      | "sunrise"
      | "sunset"
      | "tablet"
      | "tag"
      | "target"
      | "terminal"
      | "thermometer"
      | "thumbs-down"
      | "thumbs-up"
      | "toggle-left"
      | "toggle-right"
      | "trash-2"
      | "trash"
      | "trending-down"
      | "trending-up"
      | "triangle"
      | "truck"
      | "tv"
      | "type"
      | "umbrella"
      | "underline"
      | "unlock"
      | "upload-cloud"
      | "upload"
      | "user-check"
      | "user-minus"
      | "user-plus"
      | "user-x"
      | "user"
      | "users"
      | "video-off"
      | "video"
      | "voicemail"
      | "volume-1"
      | "volume-2"
      | "volume-x"
      | "volume"
      | "watch"
      | "wifi-off"
      | "wifi"
      | "wind"
      | "x-circle"
      | "x-square"
      | "x"
      | "zap-off"
      | "zap"
      | "zoom-in"
      | "zoom-out";
  };
}
