/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AnArtifactHubConfigFile {
  /**
   * An identifier of the Artifact Hub repository where the packages will be published to
   */
  repositoryID?: string;
  /**
   * Repository owners
   */
  owners?: Owner[];
  /**
   * Packages that should not be indexed by Artifact Hub
   */
  ignore?: Package[];
}
/**
 * A repository owner
 */
export interface Owner {
  /**
   * A repository owner name
   */
  name?: string;
  /**
   * A repository owner email
   */
  email?: string;
}
/**
 * A package
 */
export interface Package {
  /**
   * A package name
   */
  name: string;
  /**
   * Regular expression
   */
  version?: string;
}
