/* eslint-disable */

/**
 * A `buf.plugin.yaml` file captures metadata about the plugin. It includes mandatory and optional fields that are displayed on the individual plugin page and the BSR plugin homepage at https://buf.build/plugins.
 */
export interface BufPluginYaml {
  /**
   * The YAML configuration version, must be `v1`.
   */
  version: 'v1';
  /**
   * The plugin identity with format `{remote}/{organization_name}/{plugin_name}`.
   */
  name: string;
  /**
   * The plugin version with format `v{semver}`, the `v` prefix is required and the version must be valid [semantic versioning](https://semver.org/).
   */
  plugin_version: string;
  /**
   * URL to the license of the plugin source code.
   */
  license_url?: string;
  /**
   * URL to the source code of the Protobuf plugin.
   */
  source_url?: string;
  /**
   * Description of the plugin.
   */
  description?: string;
  /**
   * The output language types generated by the plugin. See the PluginLanguage enum for existing languages. Open a GitHub issue in the Buf CLI (https://github.com/bufbuild/buf) if the output language isn't found for a plugin.
   */
  output_languages?: (
    | 'go'
    | 'javascript'
    | 'typescript'
    | 'swift'
    | 'cpp'
    | 'java'
    | 'dart'
    | 'rust'
    | 'python'
    | 'ruby'
    | 'kotlin'
    | 'objective_c'
    | 'php'
    | 'csharp'
    | 'scala'
    | 'c'
  )[];
  /**
   * The license id for the plugin from https://spdx.org/licenses.
   */
  spdx_license_id?: string;
  /**
   * The URL to the integration guide for the plugin.
   */
  integration_guide_url?: string;
  /**
   * A list of dependencies on other plugins used by Generated SDKs.
   */
  deps?: {
    /**
     * The reference to the plugin dependency with format `{name}:{plugin_version}`.
     */
    plugin: string;
    /**
     * If specified, the dependency will be to a specific version of a plugin. It is recommended to leave this off (the plugin will depend on the latest revision at time of publishing).
     */
    revision?: number;
  }[];
  /**
   * Configuration to enable a plugin for use with Generated SDKs.
   */
  registry?: {
    /**
     * Options supplied to the plugin when generating code for the SDK.
     */
    opts?: string[];
    /**
     * Generated SDK configuration for a Go plugin.
     */
    go?: {
      /**
       * The minimum Go version required by the plugin (e.g. `1.19`), used as the go directive in the `go.mod` file. See https://go.dev/ref/mod#go-mod-file-go.
       */
      min_version?: string;
      /**
       * A list of Go module requirements. Each requirement corresponds to a require directive in the `go.mod` file. See https://go.dev/ref/mod#go-mod-file-require.
       */
      deps?: {
        /**
         * Go module name.
         */
        module?: string;
        /**
         * Go module version.
         */
        version?: string;
      }[];
    };
    /**
     * Generated SDK configuration for a JavaScript/TypeScript plugin.
     */
    npm?: {
      /**
       * The suffix used in the generated files and their imported dependencies (supported by @bufbuild/protoplugin (https://www.npmjs.com/package/@bufbuild/protoplugin) plugins).
       */
      rewrite_import_path_suffix?: string;
      /**
       * NPM package dependencies for the Generated SDK.
       */
      deps?: {
        /**
         * The name of the NPM package dependency.
         */
        package?: string;
        /**
         * The version of the NPM package dependency (see https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept for more details).
         */
        version?: string;
      }[];
      /**
       * One of either `module` or `commonjs`.
       */
      import_style: 'module' | 'commonjs';
    };
    /**
     * Generated SDK configuration for a Java/Kotlin plugin.
     */
    maven?: {
      compiler?: {
        /**
         * Java compiler settings.
         */
        java?: {
          /**
           * Encoding of source files.
           */
          encoding?: string;
          /**
           * Target Java release.
           */
          release?: number & string;
          /**
           * Source bytecode level.
           */
          source?: number & string;
          /**
           * Target bytecode level.
           */
          target?: number & string;
        };
        /**
         * Kotlin compiler settings.
         */
        kotlin?: {
          /**
           * Kotlin API version.
           */
          api_version?: string;
          /**
           * JVM bytecode target version
           */
          jvm_target?: string;
          /**
           * Kotlin version source compatibility.
           */
          language_version?: string;
          /**
           * Version of the Kotlin compiler
           */
          version: string;
        };
      };
      /**
       * Runtime dependencies of the generated Java/Kotlin code (in GAV format).
       */
      deps?: string[];
      /**
       * Configures additional supported runtimes.
       */
      additional_runtimes?: {
        /**
         * The name of the additional runtime. The only known name at this time is `lite` for Protobuf lite runtime support.
         */
        name: 'lite';
        /**
         * Dependencies for the runtime. These override `registry -> maven -> deps` if specified.
         */
        deps?: string[];
        /**
         * Plugin options for the additional runtime.
         */
        opts?: string[];
      }[];
    };
    /**
     * Generated SDK configuration for a Python plugin.
     */
    python?: {
      /**
       * Runtime dependencies of the generated code.
       */
      deps?: string[];
      /**
       * Specifies the `Requires-Python` of the generated package.
       */
      requires_python?: string;
      /**
       * One of `runtime` or `stub-only`.
       */
      package_type: 'runtime' | 'stub-only';
    };
    /**
     * Generated SDK configuration for a Swift plugin.
     */
    swift?: {
      /**
       * Dependencies of the generated code.
       */
      deps?: {
        /**
         * URL of the Swift package.
         */
        source?: string;
        /**
         * Name of the Swift package.
         */
        package?: string;
        /**
         * Version of the Swift package.
         */
        version?: string;
        /**
         * Products to import.
         */
        products?: string[];
        platforms?: {
          /**
           * Version of the macOS platform.
           */
          macos?: string;
          /**
           * Version of the iOS platform.
           */
          ios?: string;
          /**
           * Version of the tvOS platform.
           */
          tvos?: string;
          /**
           * Version of the watchOS platform.
           */
          watchos?: string;
        };
        /**
         * Versions of Swift the package supports.
         */
        swift_versions?: string[];
      }[];
    };
    /**
     * Generated SDK configuration for a Rust plugin.
     */
    cargo?: {
      /**
       * The rust-version set for the generated crate.
       */
      rust_version?: string;
      /**
       * Crates.io dependencies for the Generated SDK.
       */
      deps?: {
        /**
         * The name of the dependency.
         */
        name?: string;
        /**
         * The version request of the dependency.
         */
        req?: string;
        /**
         * Whether or not to enable default features for the dependency.
         */
        default_features?: boolean;
        /**
         * The features to enable for the dependency.
         */
        features?: string[];
      }[];
    };
    /**
     * Generated SDK configuration for a C# plugin.
     */
    nuget?: {
      /**
       * The target frameworks the generated package supports.
       */
      target_frameworks?: string[];
      /**
       * nuget.org dependencies for the Generated SDK.
       */
      deps?: {
        /**
         * The package ID of the dependency.
         */
        name?: string;
        /**
         * The version range of the dependency.
         */
        version?: string;
        /**
         * The target frameworks the dependency applies to.
         */
        target_frameworks?: string[];
      }[];
    };
    /**
     * Generated SDK configuration for a CMake plugin.
     */
    cmake?: {};
  };
  [k: string]: unknown | undefined;
}
