/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A news item as JSON object -- copyright 2013 IPTC - International Press Telecommunications Council - www.iptc.org - This document is published under the Creative Commons Attribution 3.0 license, see  http://creativecommons.org/licenses/by/3.0/  $$comment: as of 2013-11-07, edited by MS for the IPTC ninjs-dev group
 */
export interface IPTCNinjsNewsInJSONVersion10ApprovedOn23October2013 {
  /**
   * The identifier for this news object
   */
  uri?: string;
  /**
   * The generic news type of this news object
   */
  type?: "text" | "audio" | "video" | "picture" | "graphic" | "composite";
  /**
   * A MIME type which applies to this news object
   */
  mimetype?: string;
  /**
   * Indicates how complete this representation of a news item is
   */
  representationtype?: "complete" | "incomplete";
  /**
   * An identifier for the kind of content of this news object
   */
  profile?: string;
  /**
   * The version of the news object which is identified by the uri property
   */
  version?: string;
  /**
   * The date and time when this version of the news object was created
   */
  versioncreated?: string;
  /**
   * The date and time before which all versions of the news object are embargoed. If absent, this object is not embargoed.
   */
  embargoed?: string;
  /**
   * The publishing status of the news object, its value is *usable* by default.
   */
  pubstatus?: "usable" | "withheld" | "canceled";
  /**
   * The person or organisation claiming the intellectual property for the content.
   */
  copyrightholder?: string;
  /**
   * Any necessary copyright notice for claiming the intellectual property for the content.
   */
  copyrightnotice?: string;
  /**
   * The human language used by the content. The value should follow IETF BCP47
   */
  language?: string;
  /**
   * An individual human being
   */
  person?: {
    /**
     * The name of a person
     */
    name?: string;
    /**
     * The relationship of the content of the news object to the person
     */
    rel?: string;
    /**
     * The identifier of a scheme (= controlled vocabulary) which includes a code for the person
     */
    scheme?: string;
    /**
     * The code for the person in a scheme (= controlled vocabulary) which is identified by the scheme property
     */
    code?: string;
  }[];
  /**
   * An administrative and functional structure which may act as as a business, as a political party or not-for-profit party
   */
  organisation?: {
    /**
     * The name of the organisation
     */
    name?: string;
    /**
     * The relationship of the content of the news object to the organisation
     */
    rel?: string;
    /**
     * The identifier of a scheme (= controlled vocabulary) which includes a code for the organisation
     */
    scheme?: string;
    /**
     * The code for the organisation in a scheme (= controlled vocabulary) which is identified by the scheme property
     */
    code?: string;
    /**
     * Symbols used for a finanical instrument linked to the organisation at a specific market place
     */
    symbols?: {
      /**
       * Ticker symbol used for the financial instrument
       */
      ticker?: string;
      /**
       * Identifier for the marketplace which uses the ticker symbols of the ticker property
       */
      exchange?: string;
    }[];
  }[];
  /**
   * A named location
   */
  place?: {
    /**
     * The name of the place
     */
    name?: string;
    /**
     * The relationship of the content of the news object to the place
     */
    rel?: string;
    /**
     * The identifier of a scheme (= controlled vocabulary) which includes a code for the place
     */
    scheme?: string;
    /**
     * The code for the place in a scheme (= controlled vocabulary) which is identified by the scheme property
     */
    code?: string;
  }[];
  /**
   * A concept with a relationship to the content
   */
  subject?: {
    /**
     * The name of the subject
     */
    name?: string;
    /**
     * The relationship of the content of the news object to the subject
     */
    rel?: string;
    /**
     * The identifier of a scheme (= controlled vocabulary) which includes a code for the subject
     */
    scheme?: string;
    /**
     * The code for the subject in a scheme (= controlled vocabulary) which is identified by the scheme property
     */
    code?: string;
  }[];
  /**
   * Something which happens in a planned or unplanned manner
   */
  event?: {
    /**
     * The name of the event
     */
    name?: string;
    /**
     * The relationship of the content of the news object to the event
     */
    rel?: string;
    /**
     * The identifier of a scheme (= controlled vocabulary) which includes a code for the event
     */
    scheme?: string;
    /**
     * The code for the event in a scheme (= controlled vocabulary) which is identified by the scheme property
     */
    code?: string;
  }[];
  /**
   * Something material, excluding persons
   */
  object?: {
    /**
     * The name of the object
     */
    name?: string;
    /**
     * The relationship of the content of the news object to the object
     */
    rel?: string;
    /**
     * The identifier of a scheme (= controlled vocabulary) which includes a code for the object
     */
    scheme?: string;
    /**
     * The code for the object in a scheme (= controlled vocabulary) which is identified by the scheme property
     */
    code?: string;
  }[];
  /**
   * The name(s) of the creator(s) of the content
   */
  byline?: string;
  /**
   * A brief and snappy introduction to the content, designed to catch the reader's attention
   */
  headline?: string;
  /**
   * The name of the location from which the content originates.
   */
  located?: string;
  /**
   * Wrapper for different renditions of non-textual content of the news object
   */
  renditions?: {
    /**
     * A specific rendition of a non-textual content of the news object.
     *
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9]+".
     */
    [k: string]: {
      /**
       * The URL for accessing the rendition as a resource
       */
      href?: string;
      /**
       * A MIME type which applies to the rendition
       */
      mimetype?: string;
      /**
       * A title for the link to the rendition resource
       */
      title?: string;
      /**
       * For still and moving images: the height of the display area measured in pixels
       */
      height?: number;
      /**
       * For still and moving images: the width of the display area measured in pixels
       */
      width?: number;
      /**
       * The size of the rendition resource in bytes
       */
      sizeinbytes?: number;
    };
  };
  /**
   * Content of news objects which are associated with this news object.
   */
  associations?: {
    [k: string]: IPTCNinjsNewsInJSONVersion10ApprovedOn23October20131;
  };
}
/**
 * A news item as JSON object -- copyright 2013 IPTC - International Press Telecommunications Council - www.iptc.org - This document is published under the Creative Commons Attribution 3.0 license, see  http://creativecommons.org/licenses/by/3.0/  $$comment: as of 2013-11-07, edited by MS for the IPTC ninjs-dev group
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-zA-Z0-9]+".
 */
export interface IPTCNinjsNewsInJSONVersion10ApprovedOn23October20131 {
  /**
   * The identifier for this news object
   */
  uri?: string;
  /**
   * The generic news type of this news object
   */
  type?: "text" | "audio" | "video" | "picture" | "graphic" | "composite";
  /**
   * A MIME type which applies to this news object
   */
  mimetype?: string;
  /**
   * Indicates how complete this representation of a news item is
   */
  representationtype?: "complete" | "incomplete";
  /**
   * An identifier for the kind of content of this news object
   */
  profile?: string;
  /**
   * The version of the news object which is identified by the uri property
   */
  version?: string;
  /**
   * The date and time when this version of the news object was created
   */
  versioncreated?: string;
  /**
   * The date and time before which all versions of the news object are embargoed. If absent, this object is not embargoed.
   */
  embargoed?: string;
  /**
   * The publishing status of the news object, its value is *usable* by default.
   */
  pubstatus?: "usable" | "withheld" | "canceled";
  /**
   * The person or organisation claiming the intellectual property for the content.
   */
  copyrightholder?: string;
  /**
   * Any necessary copyright notice for claiming the intellectual property for the content.
   */
  copyrightnotice?: string;
  /**
   * The human language used by the content. The value should follow IETF BCP47
   */
  language?: string;
  /**
   * An individual human being
   */
  person?: {
    /**
     * The name of a person
     */
    name?: string;
    /**
     * The relationship of the content of the news object to the person
     */
    rel?: string;
    /**
     * The identifier of a scheme (= controlled vocabulary) which includes a code for the person
     */
    scheme?: string;
    /**
     * The code for the person in a scheme (= controlled vocabulary) which is identified by the scheme property
     */
    code?: string;
  }[];
  /**
   * An administrative and functional structure which may act as as a business, as a political party or not-for-profit party
   */
  organisation?: {
    /**
     * The name of the organisation
     */
    name?: string;
    /**
     * The relationship of the content of the news object to the organisation
     */
    rel?: string;
    /**
     * The identifier of a scheme (= controlled vocabulary) which includes a code for the organisation
     */
    scheme?: string;
    /**
     * The code for the organisation in a scheme (= controlled vocabulary) which is identified by the scheme property
     */
    code?: string;
    /**
     * Symbols used for a finanical instrument linked to the organisation at a specific market place
     */
    symbols?: {
      /**
       * Ticker symbol used for the financial instrument
       */
      ticker?: string;
      /**
       * Identifier for the marketplace which uses the ticker symbols of the ticker property
       */
      exchange?: string;
    }[];
  }[];
  /**
   * A named location
   */
  place?: {
    /**
     * The name of the place
     */
    name?: string;
    /**
     * The relationship of the content of the news object to the place
     */
    rel?: string;
    /**
     * The identifier of a scheme (= controlled vocabulary) which includes a code for the place
     */
    scheme?: string;
    /**
     * The code for the place in a scheme (= controlled vocabulary) which is identified by the scheme property
     */
    code?: string;
  }[];
  /**
   * A concept with a relationship to the content
   */
  subject?: {
    /**
     * The name of the subject
     */
    name?: string;
    /**
     * The relationship of the content of the news object to the subject
     */
    rel?: string;
    /**
     * The identifier of a scheme (= controlled vocabulary) which includes a code for the subject
     */
    scheme?: string;
    /**
     * The code for the subject in a scheme (= controlled vocabulary) which is identified by the scheme property
     */
    code?: string;
  }[];
  /**
   * Something which happens in a planned or unplanned manner
   */
  event?: {
    /**
     * The name of the event
     */
    name?: string;
    /**
     * The relationship of the content of the news object to the event
     */
    rel?: string;
    /**
     * The identifier of a scheme (= controlled vocabulary) which includes a code for the event
     */
    scheme?: string;
    /**
     * The code for the event in a scheme (= controlled vocabulary) which is identified by the scheme property
     */
    code?: string;
  }[];
  /**
   * Something material, excluding persons
   */
  object?: {
    /**
     * The name of the object
     */
    name?: string;
    /**
     * The relationship of the content of the news object to the object
     */
    rel?: string;
    /**
     * The identifier of a scheme (= controlled vocabulary) which includes a code for the object
     */
    scheme?: string;
    /**
     * The code for the object in a scheme (= controlled vocabulary) which is identified by the scheme property
     */
    code?: string;
  }[];
  /**
   * The name(s) of the creator(s) of the content
   */
  byline?: string;
  /**
   * A brief and snappy introduction to the content, designed to catch the reader's attention
   */
  headline?: string;
  /**
   * The name of the location from which the content originates.
   */
  located?: string;
  /**
   * Wrapper for different renditions of non-textual content of the news object
   */
  renditions?: {
    /**
     * A specific rendition of a non-textual content of the news object.
     *
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9]+".
     */
    [k: string]: {
      /**
       * The URL for accessing the rendition as a resource
       */
      href?: string;
      /**
       * A MIME type which applies to the rendition
       */
      mimetype?: string;
      /**
       * A title for the link to the rendition resource
       */
      title?: string;
      /**
       * For still and moving images: the height of the display area measured in pixels
       */
      height?: number;
      /**
       * For still and moving images: the width of the display area measured in pixels
       */
      width?: number;
      /**
       * The size of the rendition resource in bytes
       */
      sizeinbytes?: number;
    };
  };
  /**
   * Content of news objects which are associated with this news object.
   */
  associations?: {
    [k: string]: IPTCNinjsNewsInJSONVersion10ApprovedOn23October20131;
  };
}
