/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Used to configure any part of AnyWork automation.
 */
export type AnyWorkAutomationConfigurationSchema = AnyWorkAutomationConfigurationSchema1 &
  AnyWorkAutomationConfigurationSchema2;
export type AnyWorkAutomationConfigurationSchema1 = {
  [k: string]: unknown;
};

export interface AnyWorkAutomationConfigurationSchema2 {
  /**
   * type of configuration, means who will use this configuration.
   */
  ctype: string;
  /**
   * Version of configuration. The reader will parse configuration based on this.
   */
  cversion: number;
  [k: string]: unknown;
}
