/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describes a format for specifying how to replay single compilations independently of the build system
 */
export type LLVMCompilationDatabase = CommandObject[];

export interface CommandObject {
  /**
   * The working directory of the compilation
   */
  directory?: string;
  /**
   * The main translation unit source processed by this compilation step
   */
  file?: string;
  /**
   * The compile command executed
   */
  command?: string;
  /**
   * The compile command executed as list of strings
   */
  arguments?: string;
  /**
   * The name of the output created by this compilation step
   */
  output?: string;
  [k: string]: any;
}
