/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SchemaForAWSCDKContextFilesCdkJson {
  app?: string;
  build?: string;
  versionReporting?: boolean;
  watch?: {
    include?: string[];
    exclude?: string[];
    [k: string]: unknown | undefined;
  };
  context?: {
    [k: string]: unknown | undefined;
  };
  [k: string]: unknown | undefined;
}
