/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Omnisharp {
  /**
   * Used to control C# formatting
   */
  FormattingOptions?: {
    EnableEditorConfigSupport?: boolean;
    NewLine?: string;
    UseTabs?: boolean;
    TabSize?: number;
    IndentationSize?: number;
    SpacingAfterMethodDeclarationName?: boolean;
    SpaceWithinMethodDeclarationParenthesis?: boolean;
    SpaceBetweenEmptyMethodDeclarationParentheses?: boolean;
    SpaceAfterMethodCallName?: boolean;
    SpaceWithinMethodCallParentheses?: boolean;
    SpaceBetweenEmptyMethodCallParentheses?: boolean;
    SpaceAfterControlFlowStatementKeyword?: boolean;
    SpaceWithinExpressionParentheses?: boolean;
    SpaceWithinCastParentheses?: boolean;
    SpaceWithinOtherParentheses?: boolean;
    SpaceAfterCast?: boolean;
    SpacesIgnoreAroundVariableDeclaration?: boolean;
    SpaceBeforeOpenSquareBracket?: boolean;
    SpaceBetweenEmptySquareBrackets?: boolean;
    SpaceWithinSquareBrackets?: boolean;
    SpaceAfterColonInBaseTypeDeclaration?: boolean;
    SpaceAfterComma?: boolean;
    SpaceAfterDot?: boolean;
    SpaceAfterSemicolonsInForStatement?: boolean;
    SpaceBeforeColonInBaseTypeDeclaration?: boolean;
    SpaceBeforeComma?: boolean;
    SpaceBeforeDot?: boolean;
    SpaceBeforeSemicolonsInForStatement?: boolean;
    SpacingAroundBinaryOperator?: string;
    IndentBraces?: boolean;
    IndentBlock?: boolean;
    IndentSwitchSection?: boolean;
    IndentSwitchCaseSection?: boolean;
    IndentSwitchCaseSectionWhenBlock?: boolean;
    LabelPositioning?: string;
    WrappingPreserveSingleLine?: boolean;
    WrappingKeepStatementsOnSingleLine?: boolean;
    NewLinesForBracesInTypes?: boolean;
    NewLinesForBracesInMethods?: boolean;
    NewLinesForBracesInProperties?: boolean;
    NewLinesForBracesInAccessors?: boolean;
    NewLinesForBracesInAnonymousMethods?: boolean;
    NewLinesForBracesInControlBlocks?: boolean;
    NewLinesForBracesInAnonymousTypes?: boolean;
    NewLinesForBracesInObjectCollectionArrayInitializers?: boolean;
    NewLinesForBracesInLambdaExpressionBody?: boolean;
    NewLineForElse?: boolean;
    NewLineForCatch?: boolean;
    NewLineForFinally?: boolean;
    NewLineForMembersInObjectInit?: boolean;
    NewLineForMembersInAnonymousTypes?: boolean;
    NewLineForClausesInQuery?: boolean;
    [k: string]: unknown;
  };
  /**
   * Used to define refactorings, code actions and analyzer locations that OmniSharp should use (i.e. Roslynator)
   */
  RoslynExtensionsOptions?: {
    EnableDecompilationSupport?: boolean;
    /**
     * If set to false, only refactorings are available
     */
    EnableAnalyzersSupport?: boolean;
    DocumentAnalysisTimeoutMs?: number;
    LocationPaths?: string[];
    [k: string]: unknown;
  };
  /**
   * Used to define which directories and files should be included in OmniSharp's project file / solution file discovery process. Not individual .cs files.
   */
  FileOptions?: {
    /**
     * Recommended for manual editing
     */
    SystemExcludeSearchPatterns?: string[];
    /**
     * Can be used by tools such as VS Code to automatically share its exclusion settings with OmniSharp
     */
    ExcludeSearchPatterns?: string[];
    [k: string]: unknown;
  };
  RenameOptions?: {
    RenameOverloads?: boolean;
    RenameInStrings?: boolean;
    RenameInComments?: boolean;
    [k: string]: unknown;
  };
  ImplementTypeOptions?: {
    InsertionBehavior?: "WithOtherMembersOfTheSameKind" | "AtTheEnd";
    PropertyGenerationBehavior?: "PreferThrowingProperties" | "PreferAutoProperties";
    [k: string]: unknown;
  };
  Plugins?: {
    LocationPaths?: string[];
    [k: string]: unknown;
  };
  /**
   * Used to configure MSBuild solutions and projects
   */
  msbuild?: {
    enabled?: boolean;
    /**
     * Value of ToolsVersion to use when building projects passed to this task
     */
    ToolsVersion?: (("Current" | "2.0" | "3.5" | "4.0" | "15.0") | string) & string;
    VisualStudioVersion?: string;
    /**
     * Build configuration used for project evaluation
     */
    Configuration?: ("Debug" | "Release") | string;
    /**
     * Specifies which version of the Common Language Runtime (CLR) use for project evaluation
     */
    Platform?: ("AnyCPU" | "x86" | "x64" | "ARM" | "ARM64" | "Itanium") | string;
    EnablePackageAutoRestore?: boolean;
    /**
     * MSBuild extensions path. On Standalone this defaults to the MSBuild folder. In VisualStudio mode this folder will be %VSINSTALLDIR%\MSBuild
     */
    MSBuildExtensionsPath?: string;
    /**
     * Root directory where the target framework will be looked for. Uses default path if this is null
     */
    TargetFrameworkRootPath?: string;
    /**
     * Path to the Sdks folder for this MSBuild instance
     */
    MSBuildSDKsPath?: string;
    RoslynTargetsPath?: string;
    /**
     * Local Roslyn path (e.g. <MSBuildPath>/Current/Bin/Roslyn)
     */
    CscToolPath?: string;
    /**
     * FileName of C# compiler
     */
    CscToolExe?: string;
    /**
     * If true, MSBuild project system will only be loading projects for files that were opened in the editor as well as referenced projects, recursively
     */
    loadProjectsOnDemand?: boolean;
    [k: string]: unknown;
  };
  /**
   * Used to configure C# scripting (CSX files)
   */
  script?: {
    enabled?: boolean;
    defaultTargetFramework?: (
      | (
          | "netstandard1.0"
          | "netstandard1.1"
          | "netstandard1.2"
          | "netstandard1.3"
          | "netstandard1.4"
          | "netstandard1.5"
          | "netstandard1.6"
          | "netstandard2.0"
          | "netstandard2.1"
          | "netcoreapp1.0"
          | "netcoreapp1.1"
          | "netcoreapp2.0"
          | "netcoreapp2.1"
          | "netcoreapp2.2"
          | "netcoreapp3.0"
          | "netcoreapp3.1"
          | "net11"
          | "net20"
          | "net35"
          | "net40"
          | "net403"
          | "net45"
          | "net451"
          | "net452"
          | "net46"
          | "net461"
          | "net462"
          | "net47"
          | "net471"
          | "net472"
          | "net48"
        )
      | string
    ) &
      string;
    enableScriptNuGetReferences?: boolean;
    /**
     * A response file (.rsp) is used to provide the command line arguments that are used to run the roslyn script compiler process. You can use this to override the default namespace includes among other things.
     */
    rspFilePath?: string;
    [k: string]: unknown;
  };
  /**
   * Used to configure Cake (cake files)
   */
  cake?: {
    enabled?: boolean;
    bakeryPath?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
