/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type JSONSchemaForAzureFunctionsHostJsonFiles = Version1 | Version2;
/**
 * The list of functions the host should load.
 */
export type Functions = string[];
/**
 * Value indicating the timeout duration for all functions.
 */
export type FunctionTimeout = string | null;
/**
 * Set of shared code directories that should be monitored for changes to ensure that when code in these directories is changed, it is picked up by your functions
 */
export type WatchDirectories = string[];

export interface Version1 {
  aggregator?: Aggregator;
  /**
   * Configuration settings for Application Insights logging.
   */
  applicationInsights?: {
    /**
     * Configuration settings for Application Insights client-side adaptive sampling.
     */
    sampling?: {
      /**
       * If true, client-side adaptive sampling is enabled.
       */
      isEnabled?: boolean;
      /**
       * The target rate that the adaptive algorithm aims for on each instance
       */
      maxTelemetryItemsPerSecond?: number;
      [k: string]: unknown;
    };
  };
  functions?: Functions;
  functionTimeout?: FunctionTimeout;
  healthMonitor?: HealthMonitor;
  /**
   * The unique ID for this job host. Can be a lower case GUID with dashes removed
   */
  id?: string;
  /**
   * Configuration settings for logging.
   */
  logger?: {
    /**
     * The default level for logging. If a category level is not specified, this value is used.
     */
    defaultLevel?: "Critical" | "Debug" | "Error" | "Information" | "None" | "Trace" | "Warning";
    /**
     * Log levels for specific categories.
     */
    categoryLevels?: {
      [k: string]: "Critical" | "Debug" | "Error" | "Information" | "None" | "Trace" | "Warning";
    };
    [k: string]: unknown;
  };
  singleton?: Singleton;
  watchDirectories?: WatchDirectories;
  /**
   * Configuration settings for logging/tracing behavior.
   */
  tracing?: {
    /**
     * The tracing level used for console logging.
     */
    consoleLevel?: "off" | "error" | "warning" | "info" | "verbose";
    /**
     * Value determining what level of file logging is enabled.
     */
    fileLoggingMode?: "never" | "always" | "debugOnly";
  };
  http?: HttpExtension;
  queues?: QueuesExtension;
  /**
   * Configuration settings for 'serviceBus' triggers.
   */
  serviceBus?: {
    /**
     * The maximum number of concurrent calls to the callback the message pump should initiate.
     */
    maxConcurrentCalls?: number;
    /**
     * The default PrefetchCount that will be used by the underlying MessageReceiver.
     */
    prefetchCount?: number;
    /**
     * The maximum duration within which the Service Bus message lock will be renewed automatically.
     */
    autoRenewTimeout?: string;
    /**
     * Specifies whether messages should be automatically completed after successful processing.
     */
    autoComplete?: boolean;
  };
  /**
   * Configuration settings for 'eventHub' triggers.
   */
  eventHub?: {
    /**
     * The maximum event count received per receive loop.
     */
    maxBatchSize?: number;
    /**
     * The default PrefetchCount that will be used by the underlying EventProcessorHost.
     */
    prefetchCount?: number;
    /**
     * The number of batches to process before creating an EventHub cursor checkpoint
     */
    batchCheckpointFrequency?: number;
  };
  durableTask?: DurableTaskExtension;
  documentDB?: CosmosDBExtension;
}
/**
 * Configuration settings for the function result aggregator.
 */
export interface Aggregator {
  /**
   * The maximum batch size for aggregations. If this value is reached before the 'flushTimeout', all values will be flushed.
   */
  batchSize?: number;
  /**
   * The aggregation duration. The aggregator will flush periodically based on this value.
   */
  flushTimeout?: string;
}
/**
 * Configuration settings for the Functions host health monitor
 */
export interface HealthMonitor {
  /**
   * Specifies whether the feature is enabled.
   */
  enabled?: boolean;
  /**
   * The time interval between the periodic background health checks
   */
  healthCheckInterval?: string;
  /**
   * A sliding time window used in conjunction with the healthCheckThreshold setting.
   */
  healthCheckWindow?: string;
  /**
   * Maximum number of times the health check can fail before a host recycle is initiated.
   */
  healthCheckThreshold?: number;
  /**
   * The threshold at which a performance counter will be considered unhealthy.
   */
  counterThreshold?: number;
}
/**
 * Configuration settings for Singleton lock behavior.
 */
export interface Singleton {
  /**
   * The period that function level locks are taken for (they will auto renew).
   */
  lockPeriod?: string;
  /**
   * The period that listener locks are taken for.
   */
  listenerLockPeriod?: string;
  /**
   * The time interval used for listener lock recovery if a listener lock couldn't be acquired on startup.
   */
  listenerLockRecoveryPollingInterval?: string;
  /**
   * The maximum amount of time the runtime will try to acquire a lock.
   */
  lockAcquisitionTimeout?: string;
  /**
   * The interval between lock acquisition attempts.
   */
  lockAcquisitionPollingInterval?: {
    [k: string]: unknown;
  };
}
/**
 * Configuration settings for 'http' triggers.
 */
export interface HttpExtension {
  /**
   * Defines the default route prefix that applies to all routes. Use an empty string to remove the prefix.
   */
  routePrefix: string;
  /**
   * Defines the the maximum number of http functions that will execute in parallel.
   */
  maxConcurrentRequests?: number;
  /**
   * Defines the maximum number of outstanding requests that will be held at any given time.
   */
  maxOutstandingRequests?: number;
  /**
   * Indicates whether dynamic host counter checks should be enabled.
   */
  dynamicThrottlesEnabled?: boolean;
  /**
   * Configuration settings for Strict-Transport-Security
   */
  hsts?: {
    /**
     * Indicates whether the hsts configuration should be applied
     */
    isEnabled?: boolean;
    /**
     * Defines the list of host names that will not add the HSTS header.
     */
    excludedHosts?: string[];
    /**
     * Indicates whether the includeSubDomain parameter of the Strict-Transport-Security header should be enabled.
     */
    includeSubDomains?: boolean;
    /**
     * Defines the max-age parameter of the Strict-Transport-Security header.
     */
    maxAge?: string;
    /**
     * Indicates whether the preload parameter of the Strict-Transport-Security header should be enabled.
     */
    preload?: boolean;
  };
  /**
   * Allows you to set custom headers in the HTTP response, ex. X-Content-Type-Options.
   */
  customHeaders?: {
    [k: string]: unknown;
  };
}
/**
 * Configuration settings for 'queue' triggers.
 */
export interface QueuesExtension {
  /**
   * The maximum interval in milliseconds between queue polls.
   */
  maxPollingInterval?: number;
  /**
   * The number of queue messages to retrieve and process in parallel (per job function).
   */
  batchSize?: number;
  /**
   * The number of times to try processing a message before moving it to the poison queue
   */
  maxDequeueCount?: number;
  /**
   * The threshold at which a new batch of messages will be fetched. The default is batchSize/2.
   */
  newBatchThreshold?: number;
  /**
   * The visibility timeout that will be applied to messages that fail processing.
   */
  visibilityTimeout?: string;
}
/**
 * Configuration settings for 'orchestration'/'activity' triggers.
 */
export interface DurableTaskExtension {
  /**
   * Alternate task hub names can be used to isolate multiple Durable Functions applications from each other, even if they're using the same storage backend.
   */
  hubName?: string;
  storageProvider?: {
    connectionStringName?: string;
    /**
     * The number of messages to pull from the control queue at a time.
     */
    controlQueueBatchSize?: number;
    /**
     * The number of control queue messages that can be buffered in memory at a time, at which point the dispatcher will wait before dequeuing any additional messages.
     */
    controlQueueBufferThreshold?: number;
    /**
     * The visibility timeout of dequeued control queue messages.
     */
    controlQueueVisibilityTimeout?: string;
    /**
     * The maximum control and work-item queue polling interval in the hh:mm:ss format. Higher values can result in higher message processing latencies. Lower values can result in higher storage costs because of increased storage transactions.
     */
    maxQueuePollingInterval?: string;
    /**
     * The partition count for the control queue. May be a positive integer between 1 and 16.
     */
    partitionCount?: number;
    /**
     * The name of a connection string to use for the History and Instances tables. If not specified, the azureStorageConnectionStringName connection is used.
     */
    trackingStoreConnectionStringName?: string;
    /**
     * The prefix to use for the History and Instances tables when trackingStoreConnectionStringName is specified. If not set, the default prefix value will be DurableTask. If trackingStoreConnectionStringName is not specified, then the History and Instances tables will use the hubName value as their prefix, and any setting for trackingStoreNamePrefix will be ignored.
     */
    trackingStoreNamePrefix?: string;
    /**
     * When set to false, uses a partition management algorithm that reduces the possibility of duplicate function execution when scaling out.
     */
    useLegacyPartitionManagement?: boolean;
    /**
     * The visibility timeout of dequeued work item queue messages.
     */
    workItemQueueVisibilityTimeout?: string;
  };
  tracing?: {
    /**
     * A value indicating whether to trace the inputs and outputs of function calls. The default behavior when tracing function execution events is to include the number of bytes in the serialized inputs and outputs for function calls. This behavior provides minimal information about what the inputs and outputs look like without bloating the logs or inadvertently exposing sensitive information. Setting this property to true causes the default function logging to log the entire contents of function inputs and outputs.
     */
    traceInputsAndOutputs?: boolean;
    /**
     * A value indicating whether to write orchestration replay events to Application Insights.
     */
    traceReplayEvents?: boolean;
  };
  notifications?: {
    eventGrid?: {
      /**
       * The URL of an Azure Event Grid custom topic endpoint. When this property is set, orchestration life-cycle notification events are published to this endpoint. This property supports App Settings resolution.
       */
      topicEndpoint?: string;
      /**
       * The name of the app setting containing the key used for authenticating with the Azure Event Grid custom topic at EventGridTopicEndpoint.
       */
      keySettingName?: string;
      /**
       * The number of times to retry if publishing to the Event Grid Topic fails.
       */
      publishRetryCount?: number;
      /**
       * The Event Grid publishes retry interval in the hh:mm:ss format.
       */
      publishRetryInterval?: string;
      /**
       * A list of event types to publish to Event Grid. If not specified, all event types will be published.
       */
      publishEventTypes?: ("Started" | "Pending" | "Completed" | "Failed" | "Terminated")[];
    };
  };
  /**
   * The maximum number of activity functions that can be processed concurrently on a single host instance.
   */
  maxConcurrentActivityFunctions?: number;
  /**
   * The maximum number of orchestrator functions that can be processed concurrently on a single host instance.
   */
  maxConcurrentOrchestratorFunctions?: number;
  extendedSessionsEnabled?: boolean;
  extendedSessionIdleTimeoutInSeconds?: number;
  /**
   * When set to true, apps will require acquiring an app-level blob lease before processing task hub messages.
   */
  useAppLease?: boolean;
  /**
   * Enable gracefully shutting down to reduce the chance of host shutdowns failing in-process function executions.
   */
  useGracefulShutdown?: boolean;
  /**
   * The maximum number of entity operations that are processed as a batch. If set to 1, batching is disabled, and each operation message is processed by a separate function invocation.
   */
  maxEntityOperationBatchSize?: number;
}
/**
 * Configuration settings for Azure Cosmos DB bindings and triggers.
 */
export interface CosmosDBExtension {
  /**
   * ConnectionMode to be used on the DocumentClients.
   */
  connectionMode?: "Gateway" | "Direct";
  /**
   * Protocol to be used on the DocumentClients.
   */
  protocol?: "Https" | "Tcp";
}
export interface Version2 {
  /**
   * Configuration settings for extension bundle
   */
  extensionBundle?: {
    /**
     * The id of the extension bundle
     */
    id?: string;
    /**
     * The version of the extension bundle.
     */
    version?: string;
  };
  aggregator?: Aggregator;
  functions?: Functions;
  functionTimeout?: FunctionTimeout;
  healthMonitor?: HealthMonitor;
  /**
   * Configuration settings for Language Workers.
   */
  languageWorker?: {
    /**
     * Specifies full path of the directory for language workers
     */
    workersDirectory?: string;
  };
  /**
   * Configuration settings for logging.
   */
  logging?: {
    /**
     * Log levels for specific categories.
     */
    logLevel?: {
      /**
       * The default level for logging. If a category level is not specified, this value is used.
       */
      default?: "Critical" | "Debug" | "Error" | "Information" | "None" | "Trace" | "Warning";
      [k: string]: "Critical" | "Debug" | "Error" | "Information" | "None" | "Trace" | "Warning";
    };
    /**
     * Configuration settings for Application Insights logging.
     */
    applicationInsights?: {
      /**
       * Configuration settings for Application Insights client-side adaptive sampling.
       */
      samplingSettings?: {
        /**
         * If true, client-side adaptive sampling is enabled.
         */
        isEnabled?: boolean;
        /**
         * The target rate that the adaptive algorithm aims for on each instance
         */
        maxTelemetryItemsPerSecond?: number;
        /**
         * The interval at which the current rate of telemetry is reevaluated.
         */
        evaluationInterval?: string;
        /**
         * The initial sampling percentage applied at the start of the sampling process to dynamically vary the percentage.
         */
        initialSamplingPercentage?: number;
        /**
         * When the sampling percentage value changes, this property determines how soon afterwards Application Insights is allowed to raise sampling percentage again to capture more data.
         */
        samplingPercentageIncreaseTimeout?: string;
        /**
         * When the sampling percentage value changes, this property determines how soon afterwards Application Insights is allowed to lower sampling percentage again to capture less data.
         */
        samplingPercentageDecreaseTimeout?: string;
        /**
         * As sampling percentage varies, this property determines the minimum allowed sampling percentage.
         */
        minSamplingPercentage?: number;
        /**
         * As sampling percentage varies, this property determines the maximum allowed sampling percentage.
         */
        maxSamplingPercentage?: number;
        /**
         * In the calculation of the moving average, the weight assigned to the most recent value. Use a value equal to or less than 1. Smaller values make the algorithm less reactive to sudden changes.
         */
        movingAverageRatio?: number;
        /**
         * A semi-colon delimited list of types excluded from sampling. Recognized: Dependency, Event, Exception, PageView, Request, Trace.
         */
        excludedTypes?: string;
        /**
         * A semi-colon delimited list of types that you want to be sampled. Recognized: Dependency, Event, Exception, PageView, Request, and Trace.
         */
        includedTypes?: string;
        [k: string]: unknown;
      };
      /**
       * Enables live metrics collection.
       */
      enableLiveMetrics?: boolean;
      /**
       * Enables dependency tracking
       */
      enableDependencyTracking?: boolean;
      /**
       * Enables Kudu performance counters collection.
       */
      enablePerformanceCountersCollection?: boolean;
      httpAutoCollectionOptions?: {
        /**
         * Enables or disables extended HTTP request information for HTTP triggers.
         */
        enableHttpTriggerExtendedInfoCollection?: boolean;
        /**
         * Enables or disables support of W3C distributed tracing protocol (and turns on legacy correlation schema). Enabled by default if enableHttpTriggerExtendedInfoCollection is true. If enableHttpTriggerExtendedInfoCollection is false, this flag applies to outgoing requests only, not incoming requests
         */
        enableW3CDistributedTracing?: boolean;
        /**
         * Enables or disables injection of multi-component correlation headers into responses. Enabling injection allows Application Insights to construct an Application Map to when several instrumentation keys are used.
         */
        enableResponseHeaderInjection?: boolean;
      };
      snapshotConfiguration?: {
        /**
         * The endpoint used to connect to the Application Insights Snapshot Debugger service.
         */
        agentEndpoint?: string | null;
        /**
         * The weight given to the current process memory size when checking if there's enough memory to take a snapshot.
         */
        captureSnapshotMemoryWeight?: number;
        /**
         * The limit on the number of failed requests to request snapshots before the telemetry processor is disabled.
         */
        failedRequestLimit?: number;
        /**
         * Enables or disables tracking of exceptions that aren't tracked by Application Insights telemetry.
         */
        handleUntrackedExceptions?: boolean;
        /**
         * Enables or disables snapshot collection.
         */
        isEnabled?: boolean;
        /**
         * Enables or disables snapshot collection is enabled in developer mode.
         */
        isEnabledInDeveloperMode?: boolean;
        /**
         * Enables or disables snapshot creation even if the Application Insights Profiler is collecting a detailed profiling session.
         */
        isEnabledWhenProfiling?: boolean;
        /**
         * Enables or disables filtering of exceptions.
         */
        isExceptionSnappointsEnabled?: boolean;
        /**
         * Determines whether to run the SnapshotUploader process at below normal priority.
         */
        isLowPrioritySnapshotUploader?: boolean;
        /**
         * The maximum number of problems that we can track at any time.
         */
        maximumCollectionPlanSize?: number;
        /**
         * The maximum number of snapshots collected for a single problem.
         */
        maximumSnapshotsRequired?: number;
        /**
         * How often to reset the problem counters in a range from one minute to seven days.
         */
        problemCounterResetInterval?: string;
        /**
         * Determines whether to send anonymous usage and error telemetry to Microsoft. This telemetry may be used if you contact Microsoft to help troubleshoot problems with the Snapshot Debugger
         */
        provideAnonymousTelemetry?: boolean;
        /**
         * How often we reconnect to the Snapshot Debugger endpoint. Allowable range is one minute to one day.
         */
        reconnectInterval?: string;
        /**
         * Specifies the folder to use for shadow copying binaries. If not set, the folders specified by the following environment variables are tried in order: Fabric_Folder_App_Temp, LOCALAPPDATA, APPDATA, TEMP.
         */
        shadowCopyFolder?: string | null;
        /**
         * If true, only one instance of SnapshotUploader will collect and upload snapshots for multiple apps that share the InstrumentationKey. If set to false, the SnapshotUploader will be unique for each (ProcessName, InstrumentationKey) tuple.
         */
        shareUploaderProcess?: boolean;
        /**
         * Determines whether or not to process snapshots in a low IO priority thread.
         */
        snapshotInLowPriorityThread?: boolean;
        /**
         * The maximum number of snapshots allowed in one day (24 hours). This limit is also enforced on the Application Insights service side.
         */
        snapshotsPerDayLimit?: number;
        /**
         * The maximum number of snapshots allowed in 10 minutes. Although there is no upper bound on this value, exercise caution increasing it on production workloads because it could impact the performance of your application.
         */
        snapshotsPerTenMinutesLimit?: number;
        /**
         * Specifies the folder to write minidumps and uploader log files. If not set, then %TEMP%\Dumps is used.
         */
        tempFolder?: string | null;
        /**
         * How many times Application Insights needs to see an exception before it asks for snapshots.
         */
        thresholdForSnapshotting?: number;
        /**
         * Overrides the proxy server used in the Snapshot Uploader process. You may need to use this setting if your application connects to the internet via a proxy server. The Snapshot Collector runs within your application's process and will use the same proxy settings.
         */
        uploaderProxy?: string | null;
      };
    };
    /**
     * Value determining what level of file logging is enabled.
     */
    fileLoggingMode?: "never" | "always" | "debugOnly";
    [k: string]: unknown;
  };
  /**
   * Managed dependency is a feature that is currently only supported with PowerShell based functions. It enables dependencies to be automatically managed by the service.
   */
  managedDependency?: {
    /**
     * If true, the requirements.psd1 file is processed
     */
    enabled?: boolean;
  };
  /**
   * Retry policy of function execution failures at the app level. Retry policy applies to all the functions in the function app.
   */
  retry?: {
    /**
     * Retry strategy to use for retrying function executions
     */
    strategy?: "exponentialBackoff" | "fixedDelay";
    /**
     * The maximum number of retries allowed per function execution. -1 means to retry indefinitely.
     */
    maxRetryCount?: number;
    /**
     * Value indicating the delayInterval for function execution retries when using FixedDelay strategy.
     */
    delayInterval?: string | null;
    /**
     * Value indicating the minimumInterval for function execution retries when using ExponentialBackoff strategy.
     */
    minimumInterval?: string | null;
    /**
     * Value indicating the maximumInterval for function execution retries when using ExponentialBackoff strategy.
     */
    maximumInterval?: string | null;
    [k: string]: unknown;
  };
  /**
   * Configuration settings for Custom Handler.
   */
  customHandler?: {
    /**
     * Configuration settings for Custom Handler process
     */
    description?: {
      /**
       * Name or path to the Custom Handler process
       */
      defaultExecutablePath?: string;
      /**
       * WorkingDirectory to be used by the Custom Handler process. If not set, defaults to function app root folder.
       */
      workingDirectory?: string;
      /**
       * Arguments to be passed to the Custom Handler process. Can use environment variables following pattern %envVarName%
       */
      arguments?: string[];
      [k: string]: unknown;
    };
    /**
     * Forward HttpTrigger request to the custom handler
     */
    enableForwardingHttpRequest?: boolean;
  };
  singleton?: Singleton;
  watchDirectories?: WatchDirectories;
  /**
   * An array of one or more names of files that are monitored for changes that require your app to restart. This guarantees that when code in these files are changed, the updates are picked up by your functions
   */
  watchFiles?: string[];
  /**
   * The version of the Azure Functions host.json schema. This is NOT the version of the Azure Functions host.
   */
  version: "2.0";
  extensions?: {
    http?: HttpExtension;
    queues?: QueuesExtensionV2;
    sendGrid?: {
      /**
       * The sender's email address across all functions.
       */
      from?: string;
    };
    /**
     * Configuration settings for 'serviceBus' triggers.
     */
    serviceBus?: {
      /**
       * The default PrefetchCount that will be used by the underlying MessageReceiver.
       */
      prefetchCount?: number;
      /**
       * The options that will be used for the message handler registered with the MessageReceiver.
       */
      messageHandlerOptions?: {
        /**
         * The maximum number of concurrent calls to the callback the message pump should initiate.
         */
        maxConcurrentCalls?: number;
        /**
         * The maximum duration within which the Service Bus message lock will be renewed automatically.
         */
        maxAutoRenewDuration?: string;
        /**
         * Value determining whether messages will be completed automatically, or whether the function will take responsibility message completion.
         */
        autoComplete?: boolean;
      };
      sessionHandlerOptions?: {
        /**
         * The maximum duration within which the Service Bus message lock will be renewed automatically.
         */
        maxAutoRenewDuration?: string;
        /**
         * Value determining whether messages will be completed automatically, or whether the function will take responsibility message completion.
         */
        autoComplete?: boolean;
        /**
         * The maximum number of sessions that can be handled concurrently per scaled instance.
         */
        maxConcurrentSessions?: number;
        messageWaitTimeout?: string;
      };
      batchOptions?: {
        /**
         * The maximum number of messages sent to the function when triggered.
         */
        maxMessageCount?: number;
        /**
         * A time span value expressed in hh:mm:ss.
         */
        operationTimeout?: string;
        /**
         * Whether the trigger should automatically call complete after processing, or if the function code will manually call complete.
         */
        autoComplete?: boolean;
      };
    };
    /**
     * Configuration settings for 'eventHub' triggers.
     */
    eventHubs?:
      | {
          /**
           * The maximum number of events that will be included in a batch for a single invocation.
           */
          maxEventBatchSize?: number;
          /**
           * The number of batches to process before creating a checkpoint for the Event Hub.
           */
          batchCheckpointFrequency?: number;
          /**
           * The number of events that will be eagerly requested from Event Hubs and held in a local cache to allow reads to avoid waiting on a network operation.
           */
          prefetchCount?: number;
          /**
           * The protocol and transport that is used for communicating with Event Hubs.
           */
          transportType?: "amqpTcp" | "amqpWebSockets";
          /**
           * The proxy to use for communicating with Event Hubs over web sockets. A proxy cannot be used with the amqpTcp transport.
           */
          webProxy?: string;
          /**
           * The address to use when establishing a connection to Event Hubs, allowing network requests to be routed through an application gateway or other path needed for the host environment.
           */
          customEndpointAddress?: string;
          initialOffsetOptions?: {
            /**
             * The location in the event stream to start processing when a checkpoint does not exist in storage. Applies to all partitions.
             */
            type?: "fromStart" | "fromEnd" | "fromEnqueuedTime";
            /**
             * Specifies the enqueued time of the event in the stream from which to start processing. When initialOffsetOptions/type is configured as fromEnqueuedTime, this setting is mandatory. Supports time in any format supported by DateTime.Parse(), such as 2020-10-26T20:31Z.
             */
            enqueuedTimeUtc?: string;
          };
          clientRetryOptions?: {
            /**
             * The approach to use for calculating retry delays. Exponential mode will retry attempts with a delay based on a back-off strategy where each attempt will increase the duration that it waits before retrying.
             */
            mode?: "exponential" | "fixed";
            /**
             * The maximum duration to wait for an Event Hubs operation to complete, per attempt.
             */
            tryTimeout?: string;
            /**
             * The maximum duration to wait for an Event Hubs operation to complete, per attempt.
             */
            delay?: string;
            /**
             * The maximum delay to allow between retry attempts.
             */
            maxDelay?: string;
            /**
             * The maximum number of retry attempts before considering the associated operation to have failed.
             */
            maxRetries?: number;
          };
        }
      | {
          /**
           * The number of batches to process before creating an EventHub cursor checkpoint.
           */
          batchCheckpointFrequency?: number;
          /**
           * Configuration on processing event hub events.
           */
          eventProcessorOptions?: {
            /**
             * The maximum event count received per receive loop.
             */
            maxBatchSize?: number;
            /**
             * The default PrefetchCount that will be used by the underlying EventProcessorHost.
             */
            prefetchCount?: number;
          };
          initialOffsetOptions?: {
            /**
             * The location in the event stream from which to start processing when a checkpoint doesn't exist in storage.
             */
            type?: "fromStart" | "fromEnd" | "fromEnqueuedTime";
          };
        }
      | {
          /**
           * The maximum event count received per receive loop.
           */
          maxBatchSize?: number;
          /**
           * The default prefetch that will be used by the underlying EventProcessorHost.
           */
          prefetchCount?: number;
          /**
           * The number of event batches to process before creating an EventHub cursor checkpoint.
           */
          batchCheckpointFrequency?: number;
        };
    durableTask?: DurableTaskExtension;
    cosmosDB?: CosmosDBExtensionV2;
    blobs?: {
      /**
       * The number of concurrent invocations allowed for each blob-triggered function.
       */
      maxDegreeOfParallelism?: number;
    };
    [k: string]: unknown;
  };
  /**
   * Configuration settings for dynamic concurrency
   */
  concurrency?: {
    /**
     * Enables or disables dynamic concurrency for function apps.
     */
    dynamicConcurrencyEnabled?: boolean;
    /**
     * Enables or disables the learned concurrency values persisting in storage.
     */
    snapshotPersistenceEnabled?: boolean;
  };
}
/**
 * Configuration settings for 'queue' triggers.
 */
export interface QueuesExtensionV2 {
  /**
   * The maximum interval between queue polls. Minimum is 00:00:00.100 (100 ms).
   */
  maxPollingInterval?: string;
  /**
   * The time interval between retries when processing of a message fails.
   */
  visibilityTimeout?: string;
  /**
   * The number of queue messages that the Functions runtime retrieves simultaneously and processes in parallel. When the number being processed gets down to the `newBatchThreshold`, the runtime gets another batch and starts processing those messages. So the maximum number of concurrent messages being processed per function is `batchSize` plus `newBatchThreshold`. This limit applies separately to each queue-triggered function.
   */
  batchSize?: number;
  /**
   * The number of times to try processing a message before moving it to the poison queue
   */
  maxDequeueCount?: number;
  /**
   * The threshold at which a new batch of messages will be fetched. The default is batchSize/2.
   */
  newBatchThreshold?: number;
  /**
   * This setting is only available in extension version 5.0.0 and higher. It represents the encoding format for messages.
   */
  messageEncoding?: "base64" | "none";
}
/**
 * Configuration settings for Azure Cosmos DB bindings and triggers.
 */
export interface CosmosDBExtensionV2 {
  /**
   * ConnectionMode to be used on the DocumentClients.
   */
  connectionMode?: "Gateway" | "Direct";
  /**
   * Protocol to be used on the DocumentClients.
   */
  protocol?: "Https" | "Tcp";
  leaseOptions?: {
    /**
     * Lease prefix to use across all functions in an app.
     */
    leasePrefix?: string;
  };
}
