/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HardwareSentryConfigurationFile {
  /**
   * Sets the collect period that Hardware Sentry uses to collects metrics from the monitored hosts (Default: 2m).
   */
  collectPeriod?: number | string;
  /**
   * Disables Hardware Sentry's alerts for all the monitored hosts (Default: false).
   */
  disableAlerts?: boolean;
  /**
   * Sets the cycle that Hardware Sentry uses to perform discoveries and detect new components in your monitored environment. By default, Hardware Sentry runs a discovery after 30 collects.
   */
  discoveryCycle?: number & string;
  /**
   * Sets Hardware Sentry's internal Exporter configuration.
   */
  exporter?: {
    /**
     * Overrides Hardware Sentry's internal OTLP Exporter configuration.
     */
    otlp?: {
      /**
       * Sets Hardware Sentry's OTLP Exporter headers, such as the `Authorization` header used to authenticate the Exporter with the OTLP gRPC Receiver.
       */
      headers?: {
        [k: string]: unknown;
      };
      /**
       * Sets Hardware Sentry's OTLP Exporter trusted certificates file (Default: security/otel.crt).
       */
      trustedCertificatesFile?: string;
      /**
       * Configures the OTLP Receiver endpoint (Default: https://localhost:4317).
       */
      endpoint?: string;
      [k: string]: unknown;
    } | null;
    [k: string]: unknown;
  };
  extraLabels?: KeyValuePairVariables;
  /**
   * Adds additional static metrics to be exposed by Hardware Sentry.
   */
  extraMetrics?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` ".*".
     */
    [k: string]: number;
  };
  /**
   * Overrides the default hardware problem template used to build the alert body for all the monitored hosts.
   */
  hardwareProblemTemplate?: string;
  /**
   * Configures the hosts to monitor.
   */
  hosts?: (
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
  )[];
  /**
   * Sets the number of jobs that Hardware Sentry can run simultaneously (Default: 20).
   */
  jobPoolSize?: number & string;
  /**
   * Enables the debug mode of the core engine (Default: off).
   */
  loggerLevel?: "all" | "trace" | "debug" | "info" | "warn" | "error" | "fatal" | "off";
  /**
   * Customizes the OpenTelemetry Collector sub-process.
   */
  otelCollector?: {
    /**
     * Overrides the OpenTelemetry Collector command line.
     */
    commandLine?: string[];
    environment?: KeyValuePairVariables1;
    /**
     * Configures where to print the OpenTelemetry Collector's output (Default: log).
     */
    output?: "log" | "console" | "silent";
    /**
     * Configures the working directory of the OpenTelemetry Collector.
     */
    workingDir?: string;
    /**
     * Disables the OpenTelemetry Collector (Default: false).
     */
    disabled?: boolean;
    [k: string]: unknown;
  };
  /**
   * Sets the debug output directory for all the monitored hosts. By default, the debug output files are saved in the `logs` directory under the Hardware Sentry's home directory.
   */
  outputDirectory?: string;
  /**
   * Displays the configured hostname in the Host Resource `host.name` attribute instead of the resolved FQDN (Default: false).
   */
  resolveHostnameToFqdn?: boolean;
  /**
   * Forces all the network calls to be executed in sequential order for all the monitored hosts - NOT RECOMMENDED (Default: false).
   */
  sequential?: boolean;
}
/**
 * Adds or overrides the attributes for all the monitored hosts. It is recommended to specify a different `site` label value for each OpenTelemetry Collector running the Hardware Sentry Agent.
 */
export interface KeyValuePairVariables {
  /**
   * This interface was referenced by `KeyValuePairVariables`'s JSON-Schema definition
   * via the `patternProperty` ".*".
   *
   * This interface was referenced by `KeyValuePairVariables1`'s JSON-Schema definition
   * via the `patternProperty` ".*".
   */
  [k: string]: number | string | boolean;
}
/**
 * Configures the OpenTelemetry Collector environment variables.
 */
export interface KeyValuePairVariables1 {
  /**
   * This interface was referenced by `KeyValuePairVariables`'s JSON-Schema definition
   * via the `patternProperty` ".*".
   *
   * This interface was referenced by `KeyValuePairVariables1`'s JSON-Schema definition
   * via the `patternProperty` ".*".
   */
  [k: string]: number | string | boolean;
}
