/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * These permissions apply to all environments defined in this deployment project
 */
export type DefaultEnvironmentPermissions = Permission[];
export type Deployment = string | DeploymentProjects;
/**
 * These permissions apply to the deployment project
 */
export type DeploymentPermissions = Permission[];
/**
 * Builds and deployments are normally run on the Bamboo agent’s native operating system
 */
export type Docker =
  | string
  | {
      image: string;
      volumes?: {
        [k: string]: unknown;
      };
      "use-default-volumes"?: boolean;
      "docker-run-arguments"?: string[];
      [k: string]: unknown;
    };
/**
 * Permissions specific to an environment
 */
export type EnvironmentPermissions = {
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "[a-zA-Z0-9\s+_-]".
   */
  [k: string]: Permission[];
}[];
export type Events =
  | "plan-failed"
  | "plan-completed"
  | "plan-status-changed"
  | "plan-comment-added"
  | "plan-responsibility-changed"
  | "job-completed"
  | "job-status-changed"
  | "job-failed"
  | "job-error"
  | "job-first-failed"
  | "job-hung"
  | "job-queue-timeout"
  | "job-queued-without-capable-agents";
export type PlanPermissions = Permission[];
export type Triggers = (Polling | Cron | Remote | string)[];
export type PredefinedTask = "inject-variables" | "clean" | "checkout" | "artifact-download";
export type Script =
  | string
  | {
      script?: string;
      [k: string]: unknown;
    };
export type TestParser = "junit" | "mstest" | "nunit" | "mocha" | "testng";

/**
 * Full spec reference: https://docs.atlassian.com/bamboo-specs-docs/7.2.4/specs.html
 */
export interface BambooCISpecification {
  "default-environment-permissions"?: DefaultEnvironmentPermissions;
  deployment?: Deployment;
  "deployment-permissions"?: DeploymentPermissions;
  docker?: Docker;
  "environment-permissions"?: EnvironmentPermissions;
  /**
   * An environment represents the servers or groups of servers where the software release has been deployed to, and the tasks that are needed for the deployment to work smoothly
   */
  environments?: string[];
  labels?: string[];
  notifications?: {
    recipients?: (
      | string
      | {
          users?: string[];
          emails?: string[];
          [k: string]: unknown;
        }
    )[];
    events?: (
      | Events
      | {
          [k: string]: unknown;
        }
    )[];
    [k: string]: unknown;
  }[];
  plan?: Plan;
  "plan-permissions"?: PlanPermissions;
  /**
   * You can define how releases should be named when they are created by Bamboo
   */
  "release-naming"?: ReleaseNaming | string;
  repositories?: (
    | string
    | {
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "[a-zA-Z0-9_]".
         */
        [k: string]: {
          scope?: "project" | "global";
          type?: string;
          slug?: string;
          url?: string;
          branch?: string;
          viewer?: string;
          "ssh-key"?: string;
          "ssh-key-passphrase"?: string;
          username?: string;
          password?: string;
          "shared-credentials"?: string;
          lfs?: boolean;
          "use-shallow-clones"?: boolean;
          submodules?: boolean;
          "change-detection"?: {
            "quiet-period"?: {
              "quiet-period-seconds"?: number;
              "max-retries"?: number;
              [k: string]: unknown;
            };
            "exclude-changeset-pattern"?: string;
            "file-filter-type"?: string;
            "file-filter-pattern"?: string;
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
      }
  )[];
  /**
   * Stages group jobs to individual steps within a plan’s build process.
   */
  stages?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "[a-zA-Z0-9\s+_-]".
     */
    [k: string]: string[] | Stage;
  }[];
  triggers?: Triggers;
  variables?: KeyValue;
  version?: number;
  other?: {
    [k: string]: unknown;
  };
  [k: string]: Job;
}
/**
 * Plan permissions allow a user to control access to the functions of the build plan.
 */
export interface Permission {
  groups?: string | string[];
  permissions?:
    | ("view" | "edit" | "build" | "admin" | "clone" | "deploy")[]
    | ("view" | "edit" | "build" | "admin" | "clone" | "deploy");
  roles?: string[];
  users?: string[];
  [k: string]: unknown;
}
/**
 * A deployment project in Bamboo is a container for holding the software project you are deploying: releases that have been built and tested, and the environments to which releases are deployed
 */
export interface DeploymentProjects {
  name?: string;
  "source-plan"?: string;
  [k: string]: unknown;
}
/**
 * A plan defines everything about your continuous integration build process in Bamboo.
 */
export interface Plan {
  "project-key"?: string;
  key?: string;
  name?: string;
  [k: string]: unknown;
}
export interface ReleaseNaming {
  "next-version-name"?: string;
  "applies-to-branches"?: boolean;
  "auto-increment"?: boolean;
  "auto-increment-variables"?: string | string[];
  [k: string]: unknown;
}
/**
 * Stages group jobs to individual steps within a plan’s build process.
 */
export interface Stage {
  /**
   * Will await for execution by user
   */
  manual?: boolean;
  /**
   * Will be executed regardless of other stages state (pass or fail)
   */
  final?: boolean;
  jobs?: string[];
}
export interface Polling {
  polling?:
    | number
    | {
        period?: number;
        conditions?: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "[a-zA-Z0-9\s+_-]".
           */
          [k: string]: {
            [k: string]: boolean;
          };
        }[];
      };
}
/**
 * Execute deployment by schedule.
 */
export interface Cron {
  cron?:
    | string
    | {
        expression?: string;
        [k: string]: unknown;
      };
}
export interface Remote {
  remote?:
    | string
    | {
        ip?: string;
        [k: string]: unknown;
      };
}
/**
 * Variables can be used to make values available when building plans in Bamboo.
 */
export interface KeyValue {
  /**
   * This interface was referenced by `KeyValue`'s JSON-Schema definition
   * via the `patternProperty` "[a-zA-Z0-9_]".
   */
  [k: string]: string | number | boolean;
}
/**
 * A job is a single build unit within a plan and is made up of one or more tasks.
 */
export interface Job {
  docker?: Docker;
  "final-tasks"?: unknown[];
  key?: string;
  other?: {
    "clean-working-dir"?: boolean;
    [k: string]: unknown;
  };
  requirements?: (
    | string
    | {
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` ".".
         */
        [k: string]: string;
      }
  )[];
  tasks?: (PredefinedTask | Script | Task)[];
  [k: string]: unknown;
}
/**
 * A task is a small unit of work, such as source code checkout, or running a script
 */
export interface Task {
  interpreter?: string;
  clean?: {
    [k: string]: unknown;
  };
  checkout?: {
    repository?: string;
    path?: string;
    "force-clean-build"?: boolean & string;
    [k: string]: unknown;
  };
  "inject-variables"?:
    | string
    | {
        file?: string;
        scope?: string;
        namespace?: string;
      };
  /**
   * The Test Results Parser task in Bamboo parses test data
   */
  "test-parser"?:
    | TestParser
    | {
        type: TestParser;
        "ignore-time"?: boolean;
        "test-results"?: string[];
        [k: string]: unknown;
      };
  /**
   * @minItems 1
   */
  scripts?: [Script, ...Script[]];
  [k: string]: unknown;
}
