name: Force Release

permissions: {}

on:
  workflow_dispatch:

jobs:
  force-release:
    name: Force release
    permissions:
      issues: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: ffflorian/actions/force-release@b479e690751ea7150a7efa6f48afb0b735800d46
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          git_authorship: 'Florian Imdahl <git@ffflorian.de>'
