name: Force Release

permissions: {}

on:
  workflow_dispatch:

jobs:
  force-release:
    name: Force release
    permissions:
      issues: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: ffflorian/actions/force-release@9c7842ec0251a5890f0ca9ef22deed8dbc4ea9fa
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          git_authorship: 'Florian Imdahl <git@ffflorian.de>'
