name: Force Release

permissions: {}
on:
  workflow_dispatch:

jobs:
  force-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: ffflorian/actions/force-release@1e18e0151098ada365eb82a7e79efdadfd19a86e
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          git_authorship: 'Florian Imdahl <git@ffflorian.de>'
