name: Force Release

permissions: {}

on:
  workflow_dispatch:

jobs:
  force-release:
    name: Force release
    permissions:
      issues: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - uses: ffflorian/actions/force-release@c9a3071b2d17985d88f3bbaeab838871d9b61bdd
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          git_authorship: 'Florian Imdahl <git@ffflorian.de>'
