name: Mirror to Codeberg and GitLab

permissions: {}

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mirror:
    name: Mirror to Codeberg and GitLab
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: ffflorian/actions/git-mirror@4c122eeb3b90a673d33573e7a688a099433b59bd
        with:
          GITLAB_REMOTE: 'git@gitlab.com:${{ github.repository }}.git'
          GITLAB_SECRET: ${{ secrets.GITLAB_SECRET }}
          GITLAB_PUSH_ALL_REFS: 'false'
          CODEBERG_REMOTE: 'git@codeberg.org:${{ github.repository }}.git'
          CODEBERG_SECRET: ${{ secrets.CODEBERG_SECRET }}
          CODEBERG_PUSH_ALL_REFS: 'false'
