name: Mirror to Codeberg and GitLab

permissions: {}

on:
  push:
    branches: [main]

jobs:
  mirror:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: ffflorian/actions/git-mirror@baf8fb2e65ebe6564870f56315a09bc01ab7e0f7
        with:
          GITLAB_REMOTE: 'git@gitlab.com:ffflorian/schemastore-updater.git'
          GITLAB_SECRET: ${{ secrets.GITLAB_SECRET }}
          GITLAB_PUSH_ALL_REFS: 'false'
          CODEBERG_REMOTE: 'git@codeberg.org:ffflorian/schemastore-updater.git'
          CODEBERG_SECRET: ${{ secrets.CODEBERG_SECRET }}
          CODEBERG_PUSH_ALL_REFS: 'false'
