name: Check for yarn updates

permissions: {}

on:
  schedule:
    - cron: '0 5 1 * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/yarn_update.yml'
  workflow_dispatch:

jobs:
  yarn-update-check:
    name: Yarn update check
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Update yarn
        uses: ffflorian/actions/yarn-update@395dd69a8fe27cbaaf9ee09ebfaeefaf92dfdda5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          git_authorship: 'Florian Imdahl <git@ffflorian.de>'
          release_cooldown_days: '5'
          assignees: 'ffflorian'
